## Architectural principles

The FE pipeline should follow these rules:

1. **One canonical raster space**
   - source-aligned features
   - modeling-ready raster stack
   - patch export / chunk manifests

2. **One canonical object space**
   - shrub objects from labeling
   - aggregated feature summaries
   - provenance / confidence / QA fields

3. **Chunk is the primary compute unit**
   - not whole-site full-raster computation by default

4. **Manifest-first resume**
   - stages and families write manifests
   - large artifacts may be pushed remotely and pruned locally

5. **Source-agnostic processing**
   - each source follows the same ingest → align → family → finalize contract

6. **Notebook functions should migrate cleanly to pipeline.py**

# Setup

In [13]:
#!pip install -r requirements.txt

In [38]:
import sys
from pathlib import Path

repo_root = Path.cwd()
while not ((repo_root / "Final").exists() and (repo_root / "Sprint 3").exists()):
    if repo_root.parent == repo_root:
        raise RuntimeError("Could not locate repo root.")
    repo_root = repo_root.parent

if str(repo_root) not in sys.path:
    sys.path.insert(0, str(repo_root))


from __future__ import annotations

import json
import math
import os
import logging
import shutil
import tempfile
import time
import warnings
from collections import defaultdict
from contextlib import contextmanager
from dataclasses import dataclass, field, asdict
from pathlib import Path
from typing import Any, Iterable

import numpy as np
import pandas as pd
import rasterio
from rasterio.enums import Resampling
from rasterio.transform import Affine
from rasterio.windows import Window
from rasterio.warp import reproject

pd.set_option("display.max_columns", 200)
pd.set_option("display.max_rows", 200)
warnings.filterwarnings("ignore", category=RuntimeWarning)
warnings.filterwarnings("ignore", category=UserWarning)

from Final.config import default_config
from Final.models import (
    PipelineDomain,
    RepresentationTarget,
    SpatialScope,
    ResolutionScope,
    AvailabilityTier,
    RuntimeTier,
    ModuleCard,
    PipelineSpec,
    StageSpec,
    ModuleSpec,
    SearchAxis,
    CachePolicy,
    CacheRetentionMode,
    ArtifactSpec,
    StorageTier,
    CanonicalRasterOutputs,
    CanonicalObjectOutputs,
)
from Final.pipeline_caching import (
    hash_payload,
    write_stage_cache_manifest,
    read_stage_cache_manifest,
    is_valid_stage_cache,
)
from Final.artifact_store import (
    LocalArtifactStore,
    DriveRegistryArtifactStore,
    HybridArtifactStore,
)

from Final.labeling.io import download_file, extract_als_metadata
from Final.labeling.manifests import list_files_with_suffix, site_to_remote_base, site_to_tif_name

from Final.features.fe_2d import (
    get_color_diff,
    get_entropy_feature,
    get_fast_lbp_texture,
    get_fractal_dimension_map,
    get_granulometry_features,
    get_ldp_feature,
    get_uniform_blur,
    get_wavelet_features,
    fast_cpu_gabor,
)
from scipy.ndimage import grey_opening, grey_closing

cfg = default_config()
cfg.ensure_dirs()


LOGGER = logging.getLogger("features.notebook")
if not LOGGER.handlers:
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s | %(levelname)-8s | %(name)s | %(message)s",
    )

cfg.output.features_root.mkdir(parents=True, exist_ok=True)
cfg.output.logs_root.mkdir(parents=True, exist_ok=True)

print("Sites:", cfg.sites)
print("Project root:", cfg.data.project_root)
print("Features root:", cfg.output.features_root)
print("Canonical grid source:", cfg.features.canonical_grid_source)
print("Object table enabled:", cfg.features.object_table_enabled)

Sites: ['calaveras-big-trees', 'dl-bliss', 'independence-lake', 'pacific-union-college', 'sedgwick', 'shaver-lake']
Project root: /home/jovyan/work/Dry-shRub/shrub
Features root: /home/jovyan/work/Dry-shRub/shrub/Final/artifacts/features
Canonical grid source: naip
Object table enabled: True

# Run Context

In [5]:
NOTEBOOK_VERSION = "fe_notebook"

DEFAULT_SOURCE_ORDER = ("naip", "als", "3dep", "rap")

DEFAULT_FAMILY_ORDER = {
    "naip": (
        "raw",
        "veg_idx",
        "texture",
        "multiscale",
        "color_diff",
        "granulometry",
        "fractal",
        "wavelet",
        "gabor",
        "ldp",
        "morphology",
    ),
    "als": ("height", "structure", "canopy_context"),
    "3dep": ("terrain", "terrain_context"),
    "rap": ("prior",),
}

@dataclass
class TimingConfig:
    enabled: bool = True
    log_start_end: bool = True
    warn_if_seconds_over: float = 30.0
    enable_rate_tracking: bool = True
    extrapolation_unit: str = "megapixels"


@dataclass
class ChunkingConfig:
    enabled: bool = True
    chunk_size_px: int = 1024
    halo_px_default: int = 32
    allow_full_raster_fallback: bool = True
    materialize_full_rasters_by_default: bool = False


@dataclass
class StorageConfig:
    enable_local_store: bool = True
    enable_drive_store: bool = False
    use_hybrid_store: bool = False

    local_storage_root: Path = cfg.output.features_root / "artifact_store_local"
    drive_registry_path: Path = cfg.data.project_root / "Final" / "artifact_registry.yaml"
    drive_config_path: Path = cfg.data.project_root / "drive_config.yaml"
    client_secrets_path: Path = cfg.data.project_root / "client_secrets.json"
    credentials_path: Path = cfg.data.project_root / "pydrive_credentials.json"

    fail_if_drive_missing: bool = False


@dataclass
class PersistenceConfig:
    persist_manifests: bool = True
    persist_chunk_outputs: bool = True
    persist_family_outputs: bool = True
    persist_stack_registry: bool = True
    persist_object_tables: bool = True
    write_runtime_csv: bool = True
    write_summary_csvs: bool = True

    push_large_artifacts_to_remote: bool = False
    prune_local_after_remote_push: bool = False
    verify_remote_before_prune: bool = True


@dataclass
class ObjectAggregationConfig:
    enabled: bool = True
    include_centroid_sample: bool = True
    centroid_only: bool = False
    square_window_radius_px: int = 3
    use_radius_scaled_window: bool = True
    min_radius_px: int = 2
    max_radius_px: int = 12
    stats: tuple[str, ...] = ("mean", "std", "min", "max")


@dataclass
class NAIPFamilyConfig:
    enabled_families: tuple[str, ...] = ("raw", "veg_idx", "texture", "multiscale")
    heavy_families_enabled: tuple[str, ...] = ()

    texture_entropy_window: int = 9
    texture_lbp_radius: int = 2
    texture_blur_sizes: tuple[int, ...] = (5, 11)

    multiscale_sizes: tuple[int, ...] = (3, 7, 15)

    granulometry_scales: tuple[int, ...] = (3, 5, 7, 11)
    fractal_scales: tuple[int, ...] = (3, 5, 7, 9)
    wavelet_type: str = "db2"
    wavelet_level: int = 2
    gabor_frequencies: tuple[float, ...] = (0.1, 0.2)
    gabor_thetas: tuple[float, ...] = (0.0, math.pi / 4, math.pi / 2, 3 * math.pi / 4)
    ldp_k: int = 3
    morphology_window_sizes: tuple[int, ...] = (3, 7, 11)

    quantize_for_texture: bool = True
    quantize_levels: int = 256
    base_band_preference: tuple[str, ...] = ("nir", "green", "red", "blue")


@dataclass
class ALSFamilyConfig:
    enabled_families: tuple[str, ...] = ("height",)
    heavy_families_enabled: tuple[str, ...] = ()

    canopy_height_resolution_m: float = 1.0
    distance_to_tall_canopy_threshold_m: float = 5.0
    local_relief_window_px: int = 5
    knn_k: int = 30


@dataclass
class TerrainFamilyConfig:
    enabled_families: tuple[str, ...] = ("terrain",)
    heavy_families_enabled: tuple[str, ...] = ()
    ruggedness_kernel_radius: int = 3
    tpi_radius_meters: int = 150
    hillshade_azimuth: int = 270
    hillshade_zenith: int = 45


@dataclass
class RAPFamilyConfig:
    enabled_families: tuple[str, ...] = ("prior",)
    context_radius_meters: int = 500


@dataclass
class NotebookFEConfig:
    sites: list[str] = field(default_factory=lambda: list(cfg.sites))
    enabled_sources: dict[str, bool] = field(
        default_factory=lambda: {k: True for k in DEFAULT_SOURCE_ORDER}
    )
    source_order: tuple[str, ...] = DEFAULT_SOURCE_ORDER

    canonical_grid_source: str = cfg.features.canonical_grid_source
    object_table_enabled: bool = cfg.features.object_table_enabled

    force_refresh_assets: bool = False
    force_refresh_features: bool = False
    force_refresh_objects: bool = False
    force_rebuild_chunk_manifest: bool = False

    timing: TimingConfig = field(default_factory=TimingConfig)
    chunking: ChunkingConfig = field(default_factory=ChunkingConfig)
    storage: StorageConfig = field(default_factory=StorageConfig)
    persistence: PersistenceConfig = field(default_factory=PersistenceConfig)
    object_agg: ObjectAggregationConfig = field(default_factory=ObjectAggregationConfig)

    naip: NAIPFamilyConfig = field(default_factory=NAIPFamilyConfig)
    als: ALSFamilyConfig = field(default_factory=ALSFamilyConfig)
    terrain: TerrainFamilyConfig = field(default_factory=TerrainFamilyConfig)
    rap: RAPFamilyConfig = field(default_factory=RAPFamilyConfig)

    cache_root: Path = cfg.output.features_root / "notebook_cache"
    summary_root: Path = cfg.output.features_root / "notebook_summaries"
    qa_root: Path = cfg.output.features_root / "notebook_qa"

    version: str = NOTEBOOK_VERSION

    def resolve(self) -> "NotebookFEConfig":
        self.cache_root = Path(self.cache_root).resolve()
        self.summary_root = Path(self.summary_root).resolve()
        self.qa_root = Path(self.qa_root).resolve()
        self.storage.local_storage_root = Path(self.storage.local_storage_root).resolve()

        for root in [
            self.cache_root,
            self.summary_root,
            self.qa_root,
            self.storage.local_storage_root,
        ]:
            root.mkdir(parents=True, exist_ok=True)

        return self


fe_cfg = NotebookFEConfig().resolve()
LOGGER.info("Resolved notebook FE config")
print(fe_cfg)

2026-04-14 21:15:28,319 | INFO     | features.notebook | Resolved notebook FE config

NotebookFEConfig(sites=['calaveras-big-trees', 'dl-bliss', 'independence-lake', 'pacific-union-college', 'sedgwick', 'shaver-lake'], enabled_sources={'naip': True, 'als': True, '3dep': True, 'rap': True}, source_order=('naip', 'als', '3dep', 'rap'), canonical_grid_source='naip', object_table_enabled=True, force_refresh_assets=False, force_refresh_features=False, force_refresh_objects=False, force_rebuild_chunk_manifest=False, timing=TimingConfig(enabled=True, log_start_end=True, warn_if_seconds_over=30.0, enable_rate_tracking=True, extrapolation_unit='megapixels'), chunking=ChunkingConfig(enabled=True, chunk_size_px=1024, halo_px_default=32, allow_full_raster_fallback=True, materialize_full_rasters_by_default=False), storage=StorageConfig(enable_local_store=True, enable_drive_store=False, use_hybrid_store=False, local_storage_root=PosixPath('/home/jovyan/work/Dry-shRub/shrub/Final/artifacts/features/artifact_store_local'), drive_registry_path=PosixPath('/home/jovyan/work/Dry-shRub/shrub/Final/artifact_registry.yaml'), drive_config_path=PosixPath('/home/jovyan/work/Dry-shRub/shrub/drive_config.yaml'), client_secrets_path=PosixPath('/home/jovyan/work/Dry-shRub/shrub/client_secrets.json'), credentials_path=PosixPath('/home/jovyan/work/Dry-shRub/shrub/pydrive_credentials.json'), fail_if_drive_missing=False), persistence=PersistenceConfig(persist_manifests=True, persist_chunk_outputs=True, persist_family_outputs=True, persist_stack_registry=True, persist_object_tables=True, write_runtime_csv=True, write_summary_csvs=True, push_large_artifacts_to_remote=False, prune_local_after_remote_push=False, verify_remote_before_prune=True), object_agg=ObjectAggregationConfig(enabled=True, include_centroid_sample=True, centroid_only=False, square_window_radius_px=3, use_radius_scaled_window=True, min_radius_px=2, max_radius_px=12, stats=('mean', 'std', 'min', 'max')), naip=NAIPFamilyConfig(enabled_families=('raw', 'veg_idx', 'texture', 'multiscale'), heavy_families_enabled=(), texture_entropy_window=9, texture_lbp_radius=2, texture_blur_sizes=(5, 11), multiscale_sizes=(3, 7, 15), granulometry_scales=(3, 5, 7, 11), fractal_scales=(3, 5, 7, 9), wavelet_type='db2', wavelet_level=2, gabor_frequencies=(0.1, 0.2), gabor_thetas=(0.0, 0.7853981633974483, 1.5707963267948966, 2.356194490192345), ldp_k=3, morphology_window_sizes=(3, 7, 11), quantize_for_texture=True, quantize_levels=256, base_band_preference=('nir', 'green', 'red', 'blue')), als=ALSFamilyConfig(enabled_families=('height',), heavy_families_enabled=(), canopy_height_resolution_m=1.0, distance_to_tall_canopy_threshold_m=5.0, local_relief_window_px=5, knn_k=30), terrain=TerrainFamilyConfig(enabled_families=('terrain',), heavy_families_enabled=(), ruggedness_kernel_radius=3, tpi_radius_meters=150, hillshade_azimuth=270, hillshade_zenith=45), rap=RAPFamilyConfig(enabled_families=('prior',), context_radius_meters=500), cache_root=PosixPath('/home/jovyan/work/Dry-shRub/shrub/Final/artifacts/features/notebook_cache'), summary_root=PosixPath('/home/jovyan/work/Dry-shRub/shrub/Final/artifacts/features/notebook_summaries'), qa_root=PosixPath('/home/jovyan/work/Dry-shRub/shrub/Final/artifacts/features/notebook_qa'), version='fe_notebook')

In [6]:
RUNTIME_LOGS: list[dict[str, Any]] = []
RUNTIME_ACCUM = defaultdict(list)


def log_info(msg: str, *args):
    LOGGER.info(msg, *args)


def stable_json(payload: dict[str, Any]) -> str:
    return json.dumps(payload, sort_keys=True, default=str)


def config_signature(payload: dict[str, Any]) -> str:
    return hash_payload(payload)


def fe_config_signature() -> str:
    return config_signature(asdict(fe_cfg))


def runtime_frame() -> pd.DataFrame:
    return pd.DataFrame(RUNTIME_LOGS) if RUNTIME_LOGS else pd.DataFrame()


def array_megapixels(arr: np.ndarray) -> float:
    return float(arr.shape[0] * arr.shape[1]) / 1_000_000.0


def estimate_remaining_time(stage_name: str, remaining_units: float) -> float | None:
    rows = RUNTIME_ACCUM.get(stage_name, [])
    rates = [
        r["sec_per_unit"]
        for r in rows
        if np.isfinite(r.get("sec_per_unit", np.nan))
    ]
    if not rates:
        return None
    return float(np.mean(rates) * remaining_units)


@contextmanager
def timed_stage(
    stage_name: str,
    *,
    site_id: str | None = None,
    source_name: str | None = None,
    family_name: str | None = None,
    unit_amount: float | None = None,
    extra: dict[str, Any] | None = None,
):
    start = time.perf_counter()

    if fe_cfg.timing.log_start_end:
        log_info(
            "START | stage=%s | site=%s | source=%s | family=%s",
            stage_name, site_id, source_name, family_name
        )

    try:
        yield
    finally:
        duration = time.perf_counter() - start
        sec_per_unit = duration / unit_amount if (unit_amount is not None and unit_amount > 0) else np.nan

        row = {
            "stage_name": stage_name,
            "site_id": site_id,
            "source_name": source_name,
            "family_name": family_name,
            "duration_sec": duration,
            "unit_amount": unit_amount,
            "sec_per_unit": sec_per_unit,
            **(extra or {}),
        }
        RUNTIME_LOGS.append(row)
        RUNTIME_ACCUM[stage_name].append(row)

        suffix = ""
        if np.isfinite(sec_per_unit):
            suffix = f" | sec_per_unit={sec_per_unit:.4f}"

        log_info(
            "END   | stage=%s | site=%s | source=%s | family=%s | duration=%.2fs%s",
            stage_name, site_id, source_name, family_name, duration, suffix
        )

        if duration >= fe_cfg.timing.warn_if_seconds_over:
            log_info(
                "SLOW  | stage=%s | duration=%.2fs exceeded threshold=%.2fs",
                stage_name, duration, fe_cfg.timing.warn_if_seconds_over
            )


print("FE config signature:", fe_config_signature())

FE config signature: 02dd149b925aa1d9

## Artifact Storage

In [7]:
def validate_drive_files(storage_cfg: StorageConfig) -> pd.DataFrame:
    rows = []
    for label, path in [
        ("client_secrets.json", storage_cfg.client_secrets_path),
        ("drive_config.yaml", storage_cfg.drive_config_path),
        ("pydrive_credentials.json", storage_cfg.credentials_path),
    ]:
        rows.append(
            {
                "file": label,
                "path": str(path),
                "exists": Path(path).exists(),
            }
        )
    return pd.DataFrame(rows)


def build_local_artifact_store(storage_cfg: StorageConfig) -> LocalArtifactStore:
    return LocalArtifactStore(
        repo_root=cfg.data.project_root,
        storage_root=storage_cfg.local_storage_root,
    )


def maybe_build_drive_artifact_store(storage_cfg: StorageConfig) -> DriveRegistryArtifactStore | None:
    if not storage_cfg.enable_drive_store:
        return None

    missing = []
    for p in [storage_cfg.client_secrets_path, storage_cfg.drive_config_path]:
        if not Path(p).exists():
            missing.append(str(p))

    if missing:
        msg = f"Missing Drive config files: {missing}"
        if storage_cfg.fail_if_drive_missing:
            raise FileNotFoundError(msg)
        LOGGER.warning(msg)
        return None

    return DriveRegistryArtifactStore(
        repo_root=cfg.data.project_root,
        registry_path=storage_cfg.drive_registry_path,
        drive_config_path=storage_cfg.drive_config_path,
        client_secrets_path=storage_cfg.client_secrets_path,
        credentials_path=storage_cfg.credentials_path,
    )


def build_artifact_store(storage_cfg: StorageConfig):
    local_store = build_local_artifact_store(storage_cfg)
    drive_store = maybe_build_drive_artifact_store(storage_cfg)

    if storage_cfg.use_hybrid_store and drive_store is not None:
        LOGGER.info("Using HybridArtifactStore")
        return HybridArtifactStore(local_store=local_store, remote_store=drive_store)

    if drive_store is not None and not storage_cfg.enable_local_store:
        LOGGER.info("Using DriveRegistryArtifactStore only")
        return drive_store

    LOGGER.info("Using LocalArtifactStore only")
    return local_store


artifact_store = build_artifact_store(fe_cfg.storage)

display(validate_drive_files(fe_cfg.storage))
print("Artifact store type:", type(artifact_store).__name__)

2026-04-14 21:16:34,870 | INFO     | features.notebook | Using LocalArtifactStore only

,file,path,exists
0,client_secrets.json,/home/jovyan/work/Dry-shRub/shrub/client_secre...,True
1,drive_config.yaml,/home/jovyan/work/Dry-shRub/shrub/drive_config...,True
2,pydrive_credentials.json,/home/jovyan/work/Dry-shRub/shrub/pydrive_cred...,True

Artifact store type: LocalArtifactStore

In [12]:
def drive_root_id_from_config(path: str | Path) -> str | None:
    path = Path(path)
    if not path.exists():
        return None
    try:
        import yaml
        payload = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
        return payload.get("drive_root_folder_id")
    except Exception as e:
        LOGGER.warning("Failed reading drive config %s: %s", path, e)
        return None


def drive_status_frame(storage_cfg: StorageConfig) -> pd.DataFrame:
    rows = []

    rows.append(
        {
            "check": "client_secrets_exists",
            "value": Path(storage_cfg.client_secrets_path).exists(),
            "detail": str(storage_cfg.client_secrets_path),
        }
    )
    rows.append(
        {
            "check": "drive_config_exists",
            "value": Path(storage_cfg.drive_config_path).exists(),
            "detail": str(storage_cfg.drive_config_path),
        }
    )
    rows.append(
        {
            "check": "credentials_exists",
            "value": Path(storage_cfg.credentials_path).exists(),
            "detail": str(storage_cfg.credentials_path),
        }
    )
    rows.append(
        {
            "check": "drive_root_folder_id_present",
            "value": drive_root_id_from_config(storage_cfg.drive_config_path) is not None,
            "detail": str(drive_root_id_from_config(storage_cfg.drive_config_path)),
        }
    )

    return pd.DataFrame(rows)


display(drive_status_frame(fe_cfg.storage))

,check,value,detail
0,client_secrets_exists,True,/home/jovyan/work/Dry-shRub/shrub/client_secre...
1,drive_config_exists,True,/home/jovyan/work/Dry-shRub/shrub/drive_config...
2,credentials_exists,True,/home/jovyan/work/Dry-shRub/shrub/pydrive_cred...
3,drive_root_folder_id_present,True,1F9AtiUfx_z48tQIkNbDpzZUpH6R5uoCN

In [15]:
def smoke_test_artifact_store_roundtrip(store, *, rel_path: str = "features/_smoke_test/roundtrip.txt") -> dict[str, Any]:
    temp_dir = Path(tempfile.mkdtemp(prefix="fe_artifact_smoke_"))
    local_path = temp_dir / "roundtrip.txt"
    local_path.write_text("artifact store smoke test", encoding="utf-8")

    result = {
        "store_type": type(store).__name__,
        "rel_path": rel_path,
        "push_ok": False,
        "pull_ok": False,
        "content_match": False,
        "remote_ref": None,
        "pulled_path": None,
    }

    try:
        remote_ref = store.push(local_path, rel_path=rel_path)
        result["push_ok"] = True
        result["remote_ref"] = remote_ref

        local_path.unlink(missing_ok=True)

        pulled_path = store.pull(rel_path, local_path=local_path)
        result["pull_ok"] = True
        result["pulled_path"] = str(pulled_path)

        content = Path(pulled_path).read_text(encoding="utf-8")
        result["content_match"] = (content == "artifact store smoke test")
    except Exception as e:
        result["error"] = str(e)
    finally:
        try:
            shutil.rmtree(temp_dir, ignore_errors=True)
        except Exception:
            pass

    return result


#smoke_result = smoke_test_artifact_store_roundtrip(artifact_store)
#display(pd.DataFrame([smoke_result]))

,store_type,rel_path,push_ok,pull_ok,content_match,remote_ref,pulled_path
0,LocalArtifactStore,features/_smoke_test/roundtrip.txt,True,True,True,/home/jovyan/work/Dry-shRub/shrub/Final/artifa...,/tmp/fe_artifact_smoke_3kotypaf/roundtrip.txt

# Contracts

In [8]:
@dataclass
class SiteAssetBundle:
    site_id: str
    source_assets: dict[str, Any] = field(default_factory=dict)
    notes: list[str] = field(default_factory=list)


@dataclass
class CanonicalGrid:
    site_id: str
    width: int
    height: int
    transform: Affine
    crs: Any
    source_name: str
    nodata: float | int | None = None

    @property
    def pixel_size(self) -> tuple[float, float]:
        return abs(self.transform.a), abs(self.transform.e)

    def profile(self, *, dtype: str = "float32", count: int = 1, nodata: float | int | None = None) -> dict[str, Any]:
        return {
            "driver": "GTiff",
            "width": self.width,
            "height": self.height,
            "count": count,
            "dtype": dtype,
            "crs": self.crs,
            "transform": self.transform,
            "nodata": self.nodata if nodata is None else nodata,
        }


@dataclass
class ChunkRecord:
    site_id: str
    chunk_id: str
    row_start: int
    row_end: int
    col_start: int
    col_end: int
    halo_px: int

    @property
    def height(self) -> int:
        return self.row_end - self.row_start

    @property
    def width(self) -> int:
        return self.col_end - self.col_start


@dataclass
class ChunkManifest:
    site_id: str
    chunk_size_px: int
    halo_px_default: int
    records: list[ChunkRecord]


@dataclass
class SourceRasterBundle:
    site_id: str
    source_name: str
    arrays: dict[str, np.ndarray]
    transform: Affine
    crs: Any
    nodata: float | int | None = None
    metadata: dict[str, Any] = field(default_factory=dict)

    @property
    def shape(self) -> tuple[int, int]:
        first = next(iter(self.arrays.values()))
        return first.shape


@dataclass
class FeatureFamilyResult:
    site_id: str
    source_name: str
    family_name: str
    arrays: dict[str, np.ndarray]
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass
class RasterLayerRecord:
    site_id: str
    source_name: str
    family_name: str
    layer_name: str
    local_path: str | None = None
    remote_ref: str | None = None
    chunked: bool = True
    dtype: str | None = None
    shape: tuple[int, int] | None = None
    notes: list[str] = field(default_factory=list)


@dataclass
class RasterStackRegistry:
    site_id: str
    config_signature: str
    layers: list[RasterLayerRecord] = field(default_factory=list)


@dataclass
class ObjectFeatureRegistry:
    site_id: str
    config_signature: str
    object_table_path: str | None = None
    notes: list[str] = field(default_factory=list)

In [9]:
def ensure_dir(path: str | Path) -> Path:
    path = Path(path)
    path.mkdir(parents=True, exist_ok=True)
    return path


def notebook_cache_root() -> Path:
    return ensure_dir(fe_cfg.cache_root)


def notebook_stage_cache_root(stage_name: str) -> Path:
    return ensure_dir(notebook_cache_root() / stage_name)


def stage_cache_dir(
    *,
    stage_name: str,
    site_id: str,
    source_name: str | None = None,
    data_signature: str | None = None,
    config_signature: str | None = None,
) -> Path:
    root = ensure_dir(notebook_stage_cache_root(stage_name) / site_id)
    if source_name is not None:
        root = ensure_dir(root / source_name)
    if data_signature is not None and config_signature is not None:
        root = ensure_dir(root / f"{data_signature}__{config_signature}")
    return root


def write_json(path: str | Path, payload: dict[str, Any]) -> Path:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, default=str), encoding="utf-8")
    return path


def read_json(path: str | Path) -> dict[str, Any]:
    return json.loads(Path(path).read_text(encoding="utf-8"))


def summarize_array(name: str, arr: np.ndarray) -> dict[str, Any]:
    finite = np.isfinite(arr)
    return {
        "name": name,
        "shape": arr.shape,
        "finite_fraction": float(finite.mean()) if finite.size else np.nan,
        "min": float(np.nanmin(arr)) if finite.any() else np.nan,
        "max": float(np.nanmax(arr)) if finite.any() else np.nan,
        "mean": float(np.nanmean(arr)) if finite.any() else np.nan,
        "std": float(np.nanstd(arr)) if finite.any() else np.nan,
    }


def feature_stack_frame(layer_dict: dict[str, np.ndarray]) -> pd.DataFrame:
    return pd.DataFrame([summarize_array(k, v) for k, v in layer_dict.items()]).sort_values("name").reset_index(drop=True)

In [10]:
def build_feature_pipeline_spec() -> PipelineSpec:
    modules = {
        "features.site_assets": ModuleSpec(
            key="features.site_assets",
            stage_name="site_assets",
        ),
        "features.canonical_grid": ModuleSpec(
            key="features.canonical_grid",
            stage_name="canonical_grid",
            param_keys=("canonical_grid_source",),
        ),
        "features.chunk_manifest": ModuleSpec(
            key="features.chunk_manifest",
            stage_name="chunk_manifest",
            enabled_key=None,
            param_keys=("chunking",),
        ),
        "features.source_ingest": ModuleSpec(
            key="features.source_ingest",
            stage_name="source_ingest",
            param_keys=("enabled_sources",),
        ),
        "features.source_align": ModuleSpec(
            key="features.source_align",
            stage_name="source_align",
        ),
        "features.family_compute": ModuleSpec(
            key="features.family_compute",
            stage_name="family_compute",
        ),
        "features.stack_finalize": ModuleSpec(
            key="features.stack_finalize",
            stage_name="stack_finalize",
        ),
        "features.object_aggregate": ModuleSpec(
            key="features.object_aggregate",
            stage_name="object_aggregate",
            enabled_key="object_table_enabled",
        ),
        "features.qa_summary": ModuleSpec(
            key="features.qa_summary",
            stage_name="qa_summary",
        ),
    }

    stages = [
        StageSpec(
            name="site_assets",
            module_keys=["features.site_assets"],
            cache_policy=CachePolicy(
                require_manifest=True,
                allow_legacy_reuse=False,
                retention_mode=CacheRetentionMode.LEAN,
            ),
        ),
        StageSpec(
            name="canonical_grid",
            module_keys=["features.canonical_grid"],
            cache_policy=CachePolicy(
                require_manifest=True,
                allow_legacy_reuse=False,
                retention_mode=CacheRetentionMode.LEAN,
            ),
        ),
        StageSpec(
            name="chunk_manifest",
            module_keys=["features.chunk_manifest"],
            cache_policy=CachePolicy(
                require_manifest=True,
                allow_legacy_reuse=False,
                retention_mode=CacheRetentionMode.LEAN,
            ),
        ),
        StageSpec(
            name="source_ingest",
            module_keys=["features.source_ingest"],
            cache_policy=CachePolicy(
                require_manifest=True,
                allow_legacy_reuse=False,
                retention_mode=CacheRetentionMode.LEAN,
            ),
        ),
        StageSpec(
            name="source_align",
            module_keys=["features.source_align"],
            cache_policy=CachePolicy(
                require_manifest=True,
                allow_legacy_reuse=False,
                retention_mode=CacheRetentionMode.LEAN,
            ),
        ),
        StageSpec(
            name="family_compute",
            module_keys=["features.family_compute"],
            cache_policy=CachePolicy(
                require_manifest=True,
                allow_legacy_reuse=False,
                retention_mode=CacheRetentionMode.LEAN,
            ),
        ),
        StageSpec(
            name="stack_finalize",
            module_keys=["features.stack_finalize"],
            cache_policy=CachePolicy(
                require_manifest=True,
                allow_legacy_reuse=False,
                retention_mode=CacheRetentionMode.LEAN,
            ),
        ),
        StageSpec(
            name="object_aggregate",
            module_keys=["features.object_aggregate"],
            cache_policy=CachePolicy(
                require_manifest=True,
                allow_legacy_reuse=False,
                retention_mode=CacheRetentionMode.LEAN,
            ),
        ),
        StageSpec(
            name="qa_summary",
            module_keys=["features.qa_summary"],
            cache_policy=CachePolicy(
                require_manifest=True,
                allow_legacy_reuse=False,
                retention_mode=CacheRetentionMode.MANIFEST_ONLY,
            ),
        ),
    ]

    search_axes = [
        SearchAxis(
            key="canonical_grid_source",
            values=["naip"],
            stage_name="canonical_grid",
            module_key="features.canonical_grid",
        ),
        SearchAxis(
            key="naip_enabled_families",
            values=[("raw", "veg_idx", "texture", "multiscale")],
            stage_name="family_compute",
            module_key="features.family_compute",
        ),
        SearchAxis(
            key="chunk_size_px",
            values=[512, 1024],
            stage_name="chunk_manifest",
            module_key="features.chunk_manifest",
        ),
    ]

    return PipelineSpec(
        pipeline_name="features",
        domain=PipelineDomain.FEATURES,
        stages=stages,
        modules=modules,
        search_axes=search_axes,
    )


FE_PIPELINE_SPEC = build_feature_pipeline_spec()

print("Pipeline:", FE_PIPELINE_SPEC.pipeline_name)
print("Stages:", [s.name for s in FE_PIPELINE_SPEC.stages])
print("Modules:", list(FE_PIPELINE_SPEC.modules.keys()))

Pipeline: features
Stages: ['site_assets', 'canonical_grid', 'chunk_manifest', 'source_ingest', 'source_align', 'family_compute', 'stack_finalize', 'object_aggregate', 'qa_summary']
Modules: ['features.site_assets', 'features.canonical_grid', 'features.chunk_manifest', 'features.source_ingest', 'features.source_align', 'features.family_compute', 'features.stack_finalize', 'features.object_aggregate', 'features.qa_summary']

In [11]:
def pipeline_spec_frame(spec: PipelineSpec) -> pd.DataFrame:
    rows = []
    for stage in spec.stages:
        rows.append(
            {
                "stage_name": stage.name,
                "module_keys": ", ".join(stage.module_keys),
                "require_manifest": stage.cache_policy.require_manifest,
                "allow_legacy_reuse": stage.cache_policy.allow_legacy_reuse,
                "retention_mode": stage.cache_policy.retention_mode.value,
                "prune_after_success": stage.cache_policy.prune_after_success,
            }
        )
    return pd.DataFrame(rows)


display(pipeline_spec_frame(FE_PIPELINE_SPEC))

,stage_name,module_keys,require_manifest,allow_legacy_reuse,retention_mode,prune_after_success
0,site_assets,features.site_assets,True,False,lean,False
1,canonical_grid,features.canonical_grid,True,False,lean,False
2,chunk_manifest,features.chunk_manifest,True,False,lean,False
3,source_ingest,features.source_ingest,True,False,lean,False
4,source_align,features.source_align,True,False,lean,False
5,family_compute,features.family_compute,True,False,lean,False
6,stack_finalize,features.stack_finalize,True,False,lean,False
7,object_aggregate,features.object_aggregate,True,False,lean,False
8,qa_summary,features.qa_summary,True,False,manifest_only,False

# Chunking

In [16]:
def chunk_manifest_cache_dir(site_id: str, data_signature: str, config_signature: str) -> Path:
    return stage_cache_dir(
        stage_name="chunk_manifest",
        site_id=site_id,
        source_name="canonical_grid",
        data_signature=data_signature,
        config_signature=config_signature,
    )


def chunk_manifest_signature(site_id: str, grid: CanonicalGrid) -> tuple[str, str]:
    data_sig = hash_payload(
        {
            "site_id": site_id,
            "width": grid.width,
            "height": grid.height,
            "transform": tuple(grid.transform)[:6],
            "crs": str(grid.crs),
            "source_name": grid.source_name,
        }
    )
    config_sig = hash_payload(
        {
            "chunk_size_px": fe_cfg.chunking.chunk_size_px,
            "halo_px_default": fe_cfg.chunking.halo_px_default,
            "version": fe_cfg.version,
        }
    )
    return data_sig, config_sig

In [17]:
def build_chunk_manifest(grid: CanonicalGrid, *, force_refresh: bool = False) -> ChunkManifest:
    data_sig, config_sig = chunk_manifest_signature(grid.site_id, grid)
    cache_dir = chunk_manifest_cache_dir(grid.site_id, data_sig, config_sig)
    manifest_json = cache_dir / "chunk_manifest.json"
    stage_manifest = cache_dir / "stage_cache_manifest.json"

    if (not force_refresh) and is_valid_stage_cache(
        stage_cache_dir=cache_dir,
        expected_stage_name="chunk_manifest",
        expected_data_signature=data_sig,
        expected_config_signature=config_sig,
    ) and manifest_json.exists():
        payload = read_json(manifest_json)
        records = [ChunkRecord(**row) for row in payload["records"]]
        LOGGER.info(
            "Using cached chunk manifest | site=%s | n_chunks=%d",
            grid.site_id, len(records)
        )
        return ChunkManifest(
            site_id=payload["site_id"],
            chunk_size_px=payload["chunk_size_px"],
            halo_px_default=payload["halo_px_default"],
            records=records,
        )

    with timed_stage(
        "chunk_manifest",
        site_id=grid.site_id,
        source_name=grid.source_name,
        unit_amount=(grid.height * grid.width) / 1_000_000.0,
    ):
        chunk_size = fe_cfg.chunking.chunk_size_px
        halo = fe_cfg.chunking.halo_px_default

        records: list[ChunkRecord] = []
        chunk_idx = 0

        for row_start in range(0, grid.height, chunk_size):
            for col_start in range(0, grid.width, chunk_size):
                row_end = min(row_start + chunk_size, grid.height)
                col_end = min(col_start + chunk_size, grid.width)

                records.append(
                    ChunkRecord(
                        site_id=grid.site_id,
                        chunk_id=f"chunk_{chunk_idx:05d}",
                        row_start=row_start,
                        row_end=row_end,
                        col_start=col_start,
                        col_end=col_end,
                        halo_px=halo,
                    )
                )
                chunk_idx += 1

        chunk_manifest = ChunkManifest(
            site_id=grid.site_id,
            chunk_size_px=chunk_size,
            halo_px_default=halo,
            records=records,
        )

        write_json(
            manifest_json,
            {
                "site_id": chunk_manifest.site_id,
                "chunk_size_px": chunk_manifest.chunk_size_px,
                "halo_px_default": chunk_manifest.halo_px_default,
                "records": [asdict(r) for r in chunk_manifest.records],
            },
        )

        write_stage_cache_manifest(
            stage_cache_dir=cache_dir,
            stage_name="chunk_manifest",
            data_signature=data_sig,
            config_signature=config_sig,
            module_variants=[],
            artifact_paths={"chunk_manifest_json": str(manifest_json)},
            success=True,
            notes=[f"Built chunk manifest with {len(records)} chunks."],
        )

        LOGGER.info(
            "Built chunk manifest | site=%s | chunk_size=%d | n_chunks=%d",
            grid.site_id, chunk_size, len(records)
        )
        return chunk_manifest

In [18]:
def chunk_manifest_frame(manifest: ChunkManifest) -> pd.DataFrame:
    return pd.DataFrame([asdict(r) for r in manifest.records])


def expanded_chunk_bounds(record: ChunkRecord, *, height: int, width: int, halo_px: int | None = None) -> dict[str, int]:
    halo = record.halo_px if halo_px is None else halo_px
    return {
        "row_start": max(0, record.row_start - halo),
        "row_end": min(height, record.row_end + halo),
        "col_start": max(0, record.col_start - halo),
        "col_end": min(width, record.col_end + halo),
    }


def chunk_window(record: ChunkRecord) -> Window:
    return Window(
        col_off=record.col_start,
        row_off=record.row_start,
        width=record.width,
        height=record.height,
    )


def expanded_chunk_window(record: ChunkRecord, *, height: int, width: int, halo_px: int | None = None) -> Window:
    b = expanded_chunk_bounds(record, height=height, width=width, halo_px=halo_px)
    return Window(
        col_off=b["col_start"],
        row_off=b["row_start"],
        width=b["col_end"] - b["col_start"],
        height=b["row_end"] - b["row_start"],
    )

## Site assets and labeling bridges

In [19]:
def site_asset_cache_root(site_id: str) -> Path:
    return ensure_dir(fe_cfg.cache_root / "site_assets" / site_id)


def site_naip_cache_root(site_id: str) -> Path:
    return ensure_dir(site_asset_cache_root(site_id) / "naip")


def site_als_cache_root(site_id: str) -> Path:
    return ensure_dir(site_asset_cache_root(site_id) / "als_metadata")


def site_3dep_cache_root(site_id: str) -> Path:
    return ensure_dir(site_asset_cache_root(site_id) / "3dep")


def site_rap_cache_root(site_id: str) -> Path:
    return ensure_dir(site_asset_cache_root(site_id) / "rap")


def validate_cached_raster(path: str | Path) -> bool:
    path = Path(path)
    if not path.exists():
        return False
    try:
        with rasterio.open(path) as src:
            h = max(1, min(16, src.height))
            w = max(1, min(16, src.width))
            src.read([1], window=Window(0, 0, w, h))
        return True
    except Exception as e:
        LOGGER.warning("Cached raster validation failed for %s: %s", path, e)
        return False

In [20]:
def prepare_naip_asset(site_id: str, *, force_refresh: bool = False) -> Path:
    site_base = site_to_remote_base(cfg, site_id)
    naip_name = site_to_tif_name(site_id)
    naip_url = f"{site_base}/{cfg.data.naip_3dep_dir}/{naip_name}"

    local_path = site_naip_cache_root(site_id) / naip_name

    if (not force_refresh) and local_path.exists() and validate_cached_raster(local_path):
        LOGGER.info("Using cached NAIP | site=%s | path=%s", site_id, local_path)
        return local_path

    if local_path.exists():
        local_path.unlink(missing_ok=True)

    LOGGER.info("Downloading NAIP | site=%s | url=%s", site_id, naip_url)
    download_file(naip_url, local_path)

    if not validate_cached_raster(local_path):
        raise RuntimeError(f"Downloaded NAIP is unreadable for site={site_id}: {local_path}")

    return local_path


def prepare_als_metadata(site_id: str, *, force_refresh: bool = False) -> list[dict[str, Any]]:
    out_json = site_als_cache_root(site_id) / "als_metadata.json"

    if (not force_refresh) and out_json.exists():
        LOGGER.info("Using cached ALS metadata | site=%s | path=%s", site_id, out_json)
        return json.loads(out_json.read_text(encoding="utf-8"))

    site_base = site_to_remote_base(cfg, site_id)
    als_url = f"{site_base}/{cfg.data.als_dir}"
    als_files = list_files_with_suffix(als_url, (".las", ".laz", ".copc.laz"))

    if not als_files:
        LOGGER.warning("No ALS files discovered | site=%s | url=%s", site_id, als_url)
        return []

    LOGGER.info("Discovered %d ALS files | site=%s", len(als_files), site_id)

    tmp_dir = Path(tempfile.mkdtemp(prefix=f"als_meta_{site_id}_"))
    rows = []

    try:
        for entry in als_files:
            local_file = tmp_dir / entry["name"]
            LOGGER.info("Downloading ALS for metadata | site=%s | file=%s", site_id, entry["name"])
            download_file(entry["url"], local_file)

            meta = extract_als_metadata(local_file)
            meta["source_file"] = entry["name"]
            rows.append(meta)

            local_file.unlink(missing_ok=True)
    finally:
        shutil.rmtree(tmp_dir, ignore_errors=True)

    out_json.write_text(json.dumps(rows, indent=2), encoding="utf-8")
    LOGGER.info("Wrote ALS metadata | site=%s | path=%s", site_id, out_json)
    return rows

In [21]:
def prepare_site_assets(site_id: str, *, force_refresh: bool = False) -> SiteAssetBundle:
    with timed_stage("site_assets", site_id=site_id):
        bundle = SiteAssetBundle(site_id=site_id)

        try:
            bundle.source_assets["naip"] = prepare_naip_asset(site_id, force_refresh=force_refresh)
        except Exception as e:
            bundle.notes.append(f"NAIP unavailable: {e}")

        try:
            bundle.source_assets["als_metadata"] = prepare_als_metadata(site_id, force_refresh=force_refresh)
        except Exception as e:
            bundle.notes.append(f"ALS metadata unavailable: {e}")

        # Placeholders until the 3DEP/RAP adapters are connected.
        bundle.source_assets["3dep"] = None
        bundle.source_assets["rap"] = None

        LOGGER.info(
            "Prepared site assets | site=%s | keys=%s | notes=%d",
            site_id, list(bundle.source_assets.keys()), len(bundle.notes)
        )
        return bundle

## Labeling bridge

In [22]:
def labeling_summary_dir() -> Path:
    return cfg.output.labeling_root / "summaries"


def labeling_manifest_dir() -> Path:
    return cfg.output.labeling_root / "manifests"


def load_labeling_objects_summary() -> pd.DataFrame:
    obj_csv = labeling_summary_dir() / "objects_all.csv"
    if obj_csv.exists():
        df = pd.read_csv(obj_csv)
        LOGGER.info("Loaded labeling objects summary | rows=%d | path=%s", len(df), obj_csv)
        return df

    LOGGER.warning("No labeling object summary found at %s", obj_csv)
    return pd.DataFrame()


def load_labeling_artifacts_summary() -> pd.DataFrame:
    art_csv = labeling_summary_dir() / "artifacts_all.csv"
    if art_csv.exists():
        df = pd.read_csv(art_csv)
        LOGGER.info("Loaded labeling artifacts summary | rows=%d | path=%s", len(df), art_csv)
        return df

    manifest_csv = labeling_manifest_dir() / "sprint4_artifacts.csv"
    if manifest_csv.exists():
        df = pd.read_csv(manifest_csv)
        LOGGER.info("Loaded labeling artifact manifest | rows=%d | path=%s", len(df), manifest_csv)
        return df

    LOGGER.warning("No labeling artifact summary or manifest found.")
    return pd.DataFrame()


LABEL_OBJECTS_DF = load_labeling_objects_summary()
LABEL_ARTIFACTS_DF = load_labeling_artifacts_summary()

print("LABEL_OBJECTS_DF:", LABEL_OBJECTS_DF.shape)
print("LABEL_ARTIFACTS_DF:", LABEL_ARTIFACTS_DF.shape)

2026-04-14 21:24:04,351 | INFO     | features.notebook | Loaded labeling objects summary | rows=274 | path=/home/jovyan/work/Dry-shRub/shrub/Final/artifacts/labeling/summaries/objects_all.csv
2026-04-14 21:24:04,354 | INFO     | features.notebook | Loaded labeling artifacts summary | rows=68 | path=/home/jovyan/work/Dry-shRub/shrub/Final/artifacts/labeling/summaries/artifacts_all.csv

LABEL_OBJECTS_DF: (274, 45)
LABEL_ARTIFACTS_DF: (68, 17)

In [23]:
def label_objects_for_site(site_id: str) -> pd.DataFrame:
    if LABEL_OBJECTS_DF.empty:
        return pd.DataFrame()
    return LABEL_OBJECTS_DF[LABEL_OBJECTS_DF["site_id"] == site_id].copy()


def label_artifacts_for_site(site_id: str) -> pd.DataFrame:
    if LABEL_ARTIFACTS_DF.empty:
        return pd.DataFrame()
    return LABEL_ARTIFACTS_DF[LABEL_ARTIFACTS_DF["site_id"] == site_id].copy()


def best_label_artifact_for_site(site_id: str, resolution_m: float = 1.0) -> pd.Series | None:
    site_df = label_artifacts_for_site(site_id)
    if site_df.empty:
        return None

    if "resolution_m" in site_df.columns:
        site_df = site_df[np.isclose(site_df["resolution_m"].astype(float), float(resolution_m))].copy()

    if site_df.empty:
        return None

    sort_cols = [c for c in ["plot_id", "source_version"] if c in site_df.columns]
    if sort_cols:
        site_df = site_df.sort_values(sort_cols)

    return site_df.iloc[0]

# Canonical Grid Setup

In [24]:
def infer_naip_band_names(path: str | Path) -> list[str]:
    path = Path(path)
    with rasterio.open(path) as src:
        count = src.count

    if count == 4:
        return ["red", "green", "blue", "nir"]
    if count == 3:
        return ["red", "green", "blue"]
    return [f"band_{i}" for i in range(1, count + 1)]


def read_raster_bundle(
    path: str | Path,
    *,
    site_id: str,
    source_name: str,
    band_names: list[str] | None = None,
) -> SourceRasterBundle:
    path = Path(path)

    with rasterio.open(path) as src:
        arr = src.read().astype(np.float32)
        nodata = src.nodata

        if nodata is not None:
            arr = np.where(arr == nodata, np.nan, arr)

        if band_names is None:
            band_names = [f"{source_name}_band_{i}" for i in range(1, src.count + 1)]

        if len(band_names) != src.count:
            raise ValueError(f"Band name count mismatch for {path}: expected {src.count}, got {len(band_names)}")

        arrays = {band_names[i]: arr[i] for i in range(src.count)}

        return SourceRasterBundle(
            site_id=site_id,
            source_name=source_name,
            arrays=arrays,
            transform=src.transform,
            crs=src.crs,
            nodata=nodata,
            metadata={
                "path": str(path),
                "width": src.width,
                "height": src.height,
                "count": src.count,
            },
        )


def canonical_grid_cache_dir(site_id: str, data_signature: str, config_signature: str) -> Path:
    return stage_cache_dir(
        stage_name="canonical_grid",
        site_id=site_id,
        source_name="naip",
        data_signature=data_signature,
        config_signature=config_signature,
    )

In [25]:
def build_canonical_grid_for_site(site_id: str, assets: SiteAssetBundle | None = None, *, force_refresh: bool = False) -> CanonicalGrid:
    if assets is None:
        assets = prepare_site_assets(site_id, force_refresh=force_refresh)

    naip_path = assets.source_assets.get("naip")
    if naip_path is None:
        raise ValueError(f"No NAIP asset available for site={site_id}; cannot build canonical grid.")

    data_sig = hash_payload(
        {
            "site_id": site_id,
            "naip_path": str(naip_path),
            "canonical_grid_source": fe_cfg.canonical_grid_source,
        }
    )
    config_sig = hash_payload(
        {
            "canonical_grid_source": fe_cfg.canonical_grid_source,
            "version": fe_cfg.version,
        }
    )
    cache_dir = canonical_grid_cache_dir(site_id, data_sig, config_sig)
    grid_json = cache_dir / "canonical_grid.json"

    if (not force_refresh) and is_valid_stage_cache(
        stage_cache_dir=cache_dir,
        expected_stage_name="canonical_grid",
        expected_data_signature=data_sig,
        expected_config_signature=config_sig,
    ) and grid_json.exists():
        payload = read_json(grid_json)
        LOGGER.info("Using cached canonical grid | site=%s", site_id)
        return CanonicalGrid(
            site_id=payload["site_id"],
            width=payload["width"],
            height=payload["height"],
            transform=Affine(*payload["transform"]),
            crs=payload["crs"],
            source_name=payload["source_name"],
            nodata=payload["nodata"],
        )

    with timed_stage("canonical_grid", site_id=site_id, source_name="naip"):
        bundle = read_raster_bundle(
            naip_path,
            site_id=site_id,
            source_name="naip",
            band_names=infer_naip_band_names(naip_path),
        )

        h, w = next(iter(bundle.arrays.values())).shape
        grid = CanonicalGrid(
            site_id=site_id,
            width=w,
            height=h,
            transform=bundle.transform,
            crs=bundle.crs,
            source_name="naip",
            nodata=np.nan,
        )

        write_json(
            grid_json,
            {
                "site_id": grid.site_id,
                "width": grid.width,
                "height": grid.height,
                "transform": list(grid.transform)[:6],
                "crs": grid.crs,
                "source_name": grid.source_name,
                "nodata": grid.nodata,
            },
        )

        write_stage_cache_manifest(
            stage_cache_dir=cache_dir,
            stage_name="canonical_grid",
            data_signature=data_sig,
            config_signature=config_sig,
            module_variants=[],
            artifact_paths={"canonical_grid_json": str(grid_json)},
            success=True,
            notes=["Built canonical grid from NAIP asset."],
        )

        LOGGER.info(
            "Built canonical grid | site=%s | shape=(%d, %d) | pixel_size=%s",
            site_id, grid.height, grid.width, grid.pixel_size
        )
        return grid

## Specs

In [26]:
@dataclass(frozen=True)
class SourceSpec:
    name: str
    native_kind: str
    default_resampling: Resampling
    notes: str = ""


SOURCE_SPECS = {
    "naip": SourceSpec(
        name="naip",
        native_kind="multiband_raster",
        default_resampling=Resampling.nearest,
        notes="Canonical appearance source and default canonical grid anchor.",
    ),
    "als": SourceSpec(
        name="als",
        native_kind="point_cloud_or_rasterized_structure",
        default_resampling=Resampling.bilinear,
        notes="Structural source for height, canopy context, and roughness.",
    ),
    "3dep": SourceSpec(
        name="3dep",
        native_kind="terrain_raster",
        default_resampling=Resampling.bilinear,
        notes="Terrain/site context source.",
    ),
    "rap": SourceSpec(
        name="rap",
        native_kind="coarse_vegetation_raster",
        default_resampling=Resampling.bilinear,
        notes="Coarse ecological prior source.",
    ),
}


def source_spec_frame() -> pd.DataFrame:
    rows = []
    for key, spec in SOURCE_SPECS.items():
        rows.append(
            {
                "source": key,
                "native_kind": spec.native_kind,
                "default_resampling": spec.default_resampling.name,
                "notes": spec.notes,
            }
        )
    return pd.DataFrame(rows)


display(source_spec_frame())

,source,native_kind,default_resampling,notes
0,naip,multiband_raster,nearest,Canonical appearance source and default canoni...
1,als,point_cloud_or_rasterized_structure,bilinear,"Structural source for height, canopy context, ..."
2,3dep,terrain_raster,bilinear,Terrain/site context source.
3,rap,coarse_vegetation_raster,bilinear,Coarse ecological prior source.

In [27]:
FE_ARTIFACT_SPECS = {
    "chunk_manifest": ArtifactSpec(
        key="chunk_manifest",
        rel_path_template="features/{site_id}/{config_signature}/chunk_manifest/chunk_manifest.json",
        storage_tier=StorageTier.LOCAL_ONLY,
        required_for_resume=True,
        prune_local_after_push=False,
    ),
    "canonical_grid": ArtifactSpec(
        key="canonical_grid",
        rel_path_template="features/{site_id}/{config_signature}/canonical_grid/canonical_grid.json",
        storage_tier=StorageTier.LOCAL_ONLY,
        required_for_resume=True,
        prune_local_after_push=False,
    ),
    "family_chunk_npz": ArtifactSpec(
        key="family_chunk_npz",
        rel_path_template="features/{site_id}/{config_signature}/{source_name}/{family_name}/{chunk_id}.npz",
        storage_tier=StorageTier.LOCAL_THEN_REMOTE,
        required_for_resume=False,
        prune_local_after_push=True,
    ),
    "stack_registry": ArtifactSpec(
        key="stack_registry",
        rel_path_template="features/{site_id}/{config_signature}/stack/stack_registry.json",
        storage_tier=StorageTier.LOCAL_THEN_REMOTE,
        required_for_resume=True,
        prune_local_after_push=False,
    ),
    "object_feature_table": ArtifactSpec(
        key="object_feature_table",
        rel_path_template="features/{site_id}/{config_signature}/objects/object_features.csv",
        storage_tier=StorageTier.LOCAL_THEN_REMOTE,
        required_for_resume=True,
        prune_local_after_push=False,
    ),
    "runtime_log": ArtifactSpec(
        key="runtime_log",
        rel_path_template="features/{site_id}/{config_signature}/qa/runtime_log.csv",
        storage_tier=StorageTier.LOCAL_ONLY,
        required_for_resume=False,
        prune_local_after_push=False,
    ),
}

In [28]:
def artifact_spec_frame() -> pd.DataFrame:
    rows = []
    for key, spec in FE_ARTIFACT_SPECS.items():
        rows.append(
            {
                "key": key,
                "rel_path_template": spec.rel_path_template,
                "storage_tier": spec.storage_tier.value,
                "required_for_resume": spec.required_for_resume,
                "prune_local_after_push": spec.prune_local_after_push,
            }
        )
    return pd.DataFrame(rows)


display(artifact_spec_frame())

,key,rel_path_template,storage_tier,required_for_resume,prune_local_after_push
0,chunk_manifest,features/{site_id}/{config_signature}/chunk_ma...,local_only,True,False
1,canonical_grid,features/{site_id}/{config_signature}/canonica...,local_only,True,False
2,family_chunk_npz,features/{site_id}/{config_signature}/{source_...,local_then_remote,False,True
3,stack_registry,features/{site_id}/{config_signature}/stack/st...,local_then_remote,True,False
4,object_feature_table,features/{site_id}/{config_signature}/objects/...,local_then_remote,True,False
5,runtime_log,features/{site_id}/{config_signature}/qa/runti...,local_only,False,False

In [29]:
# Small end-to-end dry-run of the new generic runtime pieces for one site.
TEST_SITE = fe_cfg.sites[0]

site_assets = prepare_site_assets(TEST_SITE, force_refresh=fe_cfg.force_refresh_assets)
canonical_grid = build_canonical_grid_for_site(TEST_SITE, assets=site_assets, force_refresh=fe_cfg.force_refresh_features)
chunk_manifest = build_chunk_manifest(canonical_grid, force_refresh=fe_cfg.force_rebuild_chunk_manifest)

print("TEST_SITE:", TEST_SITE)
print("Asset keys:", list(site_assets.source_assets.keys()))
print("Notes:", site_assets.notes)
print("Canonical grid shape:", (canonical_grid.height, canonical_grid.width))
print("Pixel size:", canonical_grid.pixel_size)
print("Chunk count:", len(chunk_manifest.records))

display(chunk_manifest_frame(chunk_manifest).head(10))

2026-04-14 21:25:52,539 | INFO     | features.notebook | START | stage=site_assets | site=calaveras-big-trees | source=None | family=None
2026-04-14 21:25:52,884 | INFO     | features.notebook | Downloading NAIP | site=calaveras-big-trees | url=https://wifire-data.sdsc.edu/nc/public.php/dav/files/ucca-calaveras-big-trees/NAIP_3DEP_product/calaveras_big_trees.tif
2026-04-14 21:25:56,120 | INFO     | features.notebook | Discovered 10 ALS files | site=calaveras-big-trees
2026-04-14 21:25:56,121 | INFO     | features.notebook | Downloading ALS for metadata | site=calaveras-big-trees | file=USGS_LPC_CA_SierraNevada_B22_10SGH3935.laz
2026-04-14 21:26:19,097 | INFO     | features.notebook | Downloading ALS for metadata | site=calaveras-big-trees | file=USGS_LPC_CA_SierraNevada_B22_10SGH4035.laz
2026-04-14 21:26:42,189 | INFO     | features.notebook | Downloading ALS for metadata | site=calaveras-big-trees | file=USGS_LPC_CA_SierraNevada_B22_10SGH4036.laz
2026-04-14 21:27:07,014 | INFO     | features.notebook | Downloading ALS for metadata | site=calaveras-big-trees | file=USGS_LPC_CA_SierraNevada_B22_10SGH4136.laz
2026-04-14 21:27:32,364 | INFO     | features.notebook | Downloading ALS for metadata | site=calaveras-big-trees | file=USGS_LPC_CA_SierraNevada_B22_10SGH4137.laz
2026-04-14 21:27:56,296 | INFO     | features.notebook | Downloading ALS for metadata | site=calaveras-big-trees | file=USGS_LPC_CA_SierraNevada_B22_10SGH4236.laz
2026-04-14 21:28:16,472 | INFO     | features.notebook | Downloading ALS for metadata | site=calaveras-big-trees | file=USGS_LPC_CA_SierraNevada_B22_10SGH4237.laz
2026-04-14 21:28:40,360 | INFO     | features.notebook | Downloading ALS for metadata | site=calaveras-big-trees | file=USGS_LPC_CA_SierraNevada_B22_10SGH4238.laz
2026-04-14 21:29:05,367 | INFO     | features.notebook | Downloading ALS for metadata | site=calaveras-big-trees | file=USGS_LPC_CA_SierraNevada_B22_10SGH4337.laz
2026-04-14 21:29:25,456 | INFO     | features.notebook | Downloading ALS for metadata | site=calaveras-big-trees | file=USGS_LPC_CA_SierraNevada_B22_10SGH4338.laz
2026-04-14 21:29:47,984 | INFO     | features.notebook | Wrote ALS metadata | site=calaveras-big-trees | path=/home/jovyan/work/Dry-shRub/shrub/Final/artifacts/features/notebook_cache/site_assets/calaveras-big-trees/als_metadata/als_metadata.json
2026-04-14 21:29:47,985 | INFO     | features.notebook | Prepared site assets | site=calaveras-big-trees | keys=['naip', 'als_metadata', '3dep', 'rap'] | notes=0
2026-04-14 21:29:47,985 | INFO     | features.notebook | END   | stage=site_assets | site=calaveras-big-trees | source=None | family=None | duration=235.45s
2026-04-14 21:29:47,986 | INFO     | features.notebook | SLOW  | stage=site_assets | duration=235.45s exceeded threshold=30.00s
2026-04-14 21:29:48,068 | INFO     | features.notebook | START | stage=canonical_grid | site=calaveras-big-trees | source=naip | family=None
2026-04-14 21:29:49,070 | INFO     | features.notebook | Built canonical grid | site=calaveras-big-trees | shape=(5375, 7398) | pixel_size=(0.6000000000000063, 0.6)
2026-04-14 21:29:49,070 | INFO     | features.notebook | END   | stage=canonical_grid | site=calaveras-big-trees | source=naip | family=None | duration=1.00s
2026-04-14 21:29:49,156 | INFO     | features.notebook | START | stage=chunk_manifest | site=calaveras-big-trees | source=naip | family=None
2026-04-14 21:29:49,178 | INFO     | features.notebook | Built chunk manifest | site=calaveras-big-trees | chunk_size=1024 | n_chunks=48
2026-04-14 21:29:49,179 | INFO     | features.notebook | END   | stage=chunk_manifest | site=calaveras-big-trees | source=naip | family=None | duration=0.02s | sec_per_unit=0.0006

TEST_SITE: calaveras-big-trees
Asset keys: ['naip', 'als_metadata', '3dep', 'rap']
Notes: []
Canonical grid shape: (5375, 7398)
Pixel size: (0.6000000000000063, 0.6)
Chunk count: 48

,site_id,chunk_id,row_start,row_end,col_start,col_end,halo_px
0,calaveras-big-trees,chunk_00000,0,1024,0,1024,32
1,calaveras-big-trees,chunk_00001,0,1024,1024,2048,32
2,calaveras-big-trees,chunk_00002,0,1024,2048,3072,32
3,calaveras-big-trees,chunk_00003,0,1024,3072,4096,32
4,calaveras-big-trees,chunk_00004,0,1024,4096,5120,32
5,calaveras-big-trees,chunk_00005,0,1024,5120,6144,32
6,calaveras-big-trees,chunk_00006,0,1024,6144,7168,32
7,calaveras-big-trees,chunk_00007,0,1024,7168,7398,32
8,calaveras-big-trees,chunk_00008,1024,2048,0,1024,32
9,calaveras-big-trees,chunk_00009,1024,2048,1024,2048,32

## Remote Artifact Management

In [30]:
def render_artifact_rel_path(
    artifact_key: str,
    *,
    site_id: str,
    config_signature: str,
    source_name: str | None = None,
    family_name: str | None = None,
    chunk_id: str | None = None,
) -> str:
    spec = FE_ARTIFACT_SPECS[artifact_key]
    return spec.rel_path_template.format(
        site_id=site_id,
        config_signature=config_signature,
        source_name=source_name or "unknown_source",
        family_name=family_name or "unknown_family",
        chunk_id=chunk_id or "whole",
    )


def artifact_spec_for_key(artifact_key: str) -> ArtifactSpec:
    return FE_ARTIFACT_SPECS[artifact_key]


def local_artifact_abs_path(rel_path: str) -> Path:
    if isinstance(artifact_store, LocalArtifactStore):
        return artifact_store.storage_root / rel_path
    if isinstance(artifact_store, HybridArtifactStore):
        return artifact_store.local_store.storage_root / rel_path
    # Remote-only fallback: use notebook cache as staging
    return ensure_dir(fe_cfg.cache_root / "_remote_stage") / rel_path

In [31]:
@dataclass
class PersistedArtifactRecord:
    artifact_key: str
    rel_path: str
    local_path: str | None = None
    remote_ref: str | None = None
    storage_tier: str | None = None
    exists_local: bool = False
    exists_remote: bool = False
    pruned_local: bool = False
    notes: list[str] = field(default_factory=list)


def push_artifact_if_needed(
    local_path: str | Path,
    *,
    artifact_key: str,
    rel_path: str,
) -> PersistedArtifactRecord:
    spec = artifact_spec_for_key(artifact_key)
    local_path = Path(local_path)

    rec = PersistedArtifactRecord(
        artifact_key=artifact_key,
        rel_path=rel_path,
        local_path=str(local_path),
        storage_tier=spec.storage_tier.value,
        exists_local=local_path.exists(),
    )

    if not local_path.exists():
        rec.notes.append("Local artifact missing before push.")
        return rec

    should_push_remote = (
        fe_cfg.persistence.push_large_artifacts_to_remote
        and spec.storage_tier in {StorageTier.LOCAL_THEN_REMOTE, StorageTier.REMOTE_ONLY}
        and isinstance(artifact_store, (HybridArtifactStore, DriveRegistryArtifactStore))
    )

    if should_push_remote:
        LOGGER.info(
            "PUSH ARTIFACT | key=%s | rel_path=%s | local_path=%s",
            artifact_key, rel_path, local_path
        )
        remote_ref = artifact_store.push(local_path, rel_path=rel_path)
        rec.remote_ref = remote_ref
        rec.exists_remote = True
    else:
        rec.notes.append("Remote push skipped by policy or store type.")

    return rec


def remote_artifact_exists(rel_path: str) -> bool:
    if isinstance(artifact_store, LocalArtifactStore):
        return False
    if isinstance(artifact_store, HybridArtifactStore):
        if artifact_store.remote_store is None:
            return False
        return artifact_store.remote_store.exists(rel_path)
    return artifact_store.exists(rel_path)


def prune_local_artifact_if_allowed(
    rec: PersistedArtifactRecord,
    *,
    local_path: str | Path,
) -> PersistedArtifactRecord:
    spec = artifact_spec_for_key(rec.artifact_key)
    local_path = Path(local_path)

    if not fe_cfg.persistence.prune_local_after_remote_push:
        rec.notes.append("Local pruning disabled by config.")
        return rec

    if not spec.prune_local_after_push:
        rec.notes.append("Artifact spec does not allow local prune.")
        return rec

    if fe_cfg.persistence.verify_remote_before_prune:
        remote_ok = remote_artifact_exists(rec.rel_path)
        if not remote_ok:
            rec.notes.append("Remote artifact not verified; skipping prune.")
            return rec

    if local_path.exists():
        local_path.unlink()
        rec.pruned_local = True
        rec.exists_local = False
        rec.notes.append("Local artifact pruned after verified remote push.")
        LOGGER.info("PRUNED LOCAL ARTIFACT | rel_path=%s", rec.rel_path)

    return rec

In [32]:
def persist_json_artifact(
    payload: dict[str, Any],
    *,
    artifact_key: str,
    site_id: str,
    config_sig: str,
    source_name: str | None = None,
    family_name: str | None = None,
    chunk_id: str | None = None,
) -> PersistedArtifactRecord:
    rel_path = render_artifact_rel_path(
        artifact_key,
        site_id=site_id,
        config_signature=config_sig,
        source_name=source_name,
        family_name=family_name,
        chunk_id=chunk_id,
    )
    local_path = local_artifact_abs_path(rel_path)
    write_json(local_path, payload)

    rec = push_artifact_if_needed(local_path, artifact_key=artifact_key, rel_path=rel_path)
    rec = prune_local_artifact_if_allowed(rec, local_path=local_path)
    return rec


def persist_npz_artifact(
    arrays: dict[str, np.ndarray],
    *,
    artifact_key: str,
    site_id: str,
    config_sig: str,
    source_name: str,
    family_name: str,
    chunk_id: str,
) -> PersistedArtifactRecord:
    rel_path = render_artifact_rel_path(
        artifact_key,
        site_id=site_id,
        config_signature=config_sig,
        source_name=source_name,
        family_name=family_name,
        chunk_id=chunk_id,
    )
    local_path = local_artifact_abs_path(rel_path)
    local_path.parent.mkdir(parents=True, exist_ok=True)
    np.savez_compressed(local_path, **arrays)

    rec = push_artifact_if_needed(local_path, artifact_key=artifact_key, rel_path=rel_path)
    rec = prune_local_artifact_if_allowed(rec, local_path=local_path)
    return rec

## Generic family and chunk registries

In [33]:
@dataclass(frozen=True)
class FeatureFamilySpec:
    key: str
    source_name: str
    runtime_tier: RuntimeTier
    required_halo_px: int
    representation_target: RepresentationTarget
    outputs_dense_layers: bool = True
    outputs_object_fields: bool = False
    notes: str = ""


NAIP_FAMILY_SPECS = {
    "raw": FeatureFamilySpec(
        key="raw",
        source_name="naip",
        runtime_tier=RuntimeTier.CHEAP,
        required_halo_px=0,
        representation_target=RepresentationTarget.RASTER,
        notes="Raw NAIP channels.",
    ),
    "veg_idx": FeatureFamilySpec(
        key="veg_idx",
        source_name="naip",
        runtime_tier=RuntimeTier.CHEAP,
        required_halo_px=0,
        representation_target=RepresentationTarget.RASTER,
        notes="Vegetation indices like NDVI / VARI.",
    ),
    "texture": FeatureFamilySpec(
        key="texture",
        source_name="naip",
        runtime_tier=RuntimeTier.MODERATE,
        required_halo_px=max(fe_cfg.naip.texture_entropy_window, max(fe_cfg.naip.texture_blur_sizes, default=0)),
        representation_target=RepresentationTarget.RASTER,
        notes="Entropy / LBP / blur / local structure features.",
    ),
    "multiscale": FeatureFamilySpec(
        key="multiscale",
        source_name="naip",
        runtime_tier=RuntimeTier.MODERATE,
        required_halo_px=max(fe_cfg.naip.multiscale_sizes, default=0),
        representation_target=RepresentationTarget.RASTER,
        notes="Multi-neighborhood statistics.",
    ),
    "color_diff": FeatureFamilySpec(
        key="color_diff",
        source_name="naip",
        runtime_tier=RuntimeTier.MODERATE,
        required_halo_px=1,
        representation_target=RepresentationTarget.RASTER,
    ),
    "granulometry": FeatureFamilySpec(
        key="granulometry",
        source_name="naip",
        runtime_tier=RuntimeTier.EXPENSIVE,
        required_halo_px=max(fe_cfg.naip.granulometry_scales, default=0),
        representation_target=RepresentationTarget.RASTER,
    ),
    "fractal": FeatureFamilySpec(
        key="fractal",
        source_name="naip",
        runtime_tier=RuntimeTier.EXPENSIVE,
        required_halo_px=max(fe_cfg.naip.fractal_scales, default=0),
        representation_target=RepresentationTarget.RASTER,
    ),
    "wavelet": FeatureFamilySpec(
        key="wavelet",
        source_name="naip",
        runtime_tier=RuntimeTier.EXPENSIVE,
        required_halo_px=16,
        representation_target=RepresentationTarget.RASTER,
    ),
    "gabor": FeatureFamilySpec(
        key="gabor",
        source_name="naip",
        runtime_tier=RuntimeTier.EXPENSIVE,
        required_halo_px=32,
        representation_target=RepresentationTarget.RASTER,
    ),
    "ldp": FeatureFamilySpec(
        key="ldp",
        source_name="naip",
        runtime_tier=RuntimeTier.MODERATE,
        required_halo_px=1,
        representation_target=RepresentationTarget.RASTER,
    ),
    "morphology": FeatureFamilySpec(
        key="morphology",
        source_name="naip",
        runtime_tier=RuntimeTier.EXPENSIVE,
        required_halo_px=max(fe_cfg.naip.morphology_window_sizes, default=0),
        representation_target=RepresentationTarget.RASTER,
    ),
}

In [34]:
def family_spec_frame(specs: dict[str, FeatureFamilySpec]) -> pd.DataFrame:
    rows = []
    for key, spec in specs.items():
        rows.append(
            {
                "family": key,
                "source_name": spec.source_name,
                "runtime_tier": spec.runtime_tier.value,
                "required_halo_px": spec.required_halo_px,
                "target": spec.representation_target.value,
                "notes": spec.notes,
            }
        )
    return pd.DataFrame(rows).sort_values("family").reset_index(drop=True)


display(family_spec_frame(NAIP_FAMILY_SPECS))

,family,source_name,runtime_tier,required_halo_px,target,notes
0,color_diff,naip,moderate,1,raster,
1,fractal,naip,expensive,9,raster,
2,gabor,naip,expensive,32,raster,
3,granulometry,naip,expensive,11,raster,
4,ldp,naip,moderate,1,raster,
5,morphology,naip,expensive,11,raster,
6,multiscale,naip,moderate,15,raster,Multi-neighborhood statistics.
7,raw,naip,cheap,0,raster,Raw NAIP channels.
8,texture,naip,moderate,11,raster,Entropy / LBP / blur / local structure features.
9,veg_idx,naip,cheap,0,raster,Vegetation indices like NDVI / VARI.
10,wavelet,naip,expensive,16,raster,

In [35]:
def reproject_band_to_grid(
    src_band: np.ndarray,
    *,
    src_transform: Affine,
    src_crs: Any,
    dst_grid: CanonicalGrid,
    resampling: Resampling = Resampling.bilinear,
    dst_nodata: float = np.nan,
) -> np.ndarray:
    dst = np.full((dst_grid.height, dst_grid.width), dst_nodata, dtype=np.float32)

    reproject(
        source=src_band.astype(np.float32),
        destination=dst,
        src_transform=src_transform,
        src_crs=src_crs,
        dst_transform=dst_grid.transform,
        dst_crs=dst_grid.crs,
        src_nodata=np.nan,
        dst_nodata=dst_nodata,
        resampling=resampling,
    )
    return dst


def align_bundle_to_grid(
    bundle: SourceRasterBundle,
    *,
    dst_grid: CanonicalGrid,
    resampling: Resampling,
) -> SourceRasterBundle:
    aligned = {}
    for name, band in bundle.arrays.items():
        aligned[name] = reproject_band_to_grid(
            band,
            src_transform=bundle.transform,
            src_crs=bundle.crs,
            dst_grid=dst_grid,
            resampling=resampling,
        )

    return SourceRasterBundle(
        site_id=bundle.site_id,
        source_name=bundle.source_name,
        arrays=aligned,
        transform=dst_grid.transform,
        crs=dst_grid.crs,
        nodata=np.nan,
        metadata={**bundle.metadata, "aligned_to": dst_grid.source_name},
    )

In [36]:
def slice_chunk_from_arrays(
    arrays: dict[str, np.ndarray],
    record: ChunkRecord,
    *,
    full_height: int,
    full_width: int,
    halo_px: int | None = None,
) -> tuple[dict[str, np.ndarray], dict[str, int]]:
    bounds = expanded_chunk_bounds(record, height=full_height, width=full_width, halo_px=halo_px)
    out = {}
    for name, arr in arrays.items():
        out[name] = arr[
            bounds["row_start"]:bounds["row_end"],
            bounds["col_start"]:bounds["col_end"]
        ]
    return out, bounds


def crop_chunk_interior(
    expanded_arrays: dict[str, np.ndarray],
    record: ChunkRecord,
    expanded_bounds: dict[str, int],
) -> dict[str, np.ndarray]:
    row0 = record.row_start - expanded_bounds["row_start"]
    row1 = row0 + record.height
    col0 = record.col_start - expanded_bounds["col_start"]
    col1 = col0 + record.width

    cropped = {}
    for name, arr in expanded_arrays.items():
        cropped[name] = arr[row0:row1, col0:col1]
    return cropped

## NAIP

In [40]:
def nan_to_num_copy(arr: np.ndarray, fill_value: float = 0.0) -> np.ndarray:
    out = arr.astype(np.float32, copy=True)
    out[~np.isfinite(out)] = fill_value
    return out


def safe_divide(num: np.ndarray, denom: np.ndarray, fill_value: float = 0.0) -> np.ndarray:
    out = np.full_like(num, fill_value, dtype=np.float32)
    mask = np.isfinite(num) & np.isfinite(denom) & (np.abs(denom) > 1e-12)
    out[mask] = (num[mask] / denom[mask]).astype(np.float32)
    return out


def quantize_image(arr: np.ndarray, levels: int = 256) -> np.ndarray:
    arr = nan_to_num_copy(arr)
    vmin = np.nanmin(arr)
    vmax = np.nanmax(arr)
    if abs(vmax - vmin) < 1e-12:
        return np.zeros_like(arr, dtype=np.uint8)
    scaled = (arr - vmin) / (vmax - vmin)
    scaled = np.clip(scaled, 0, 1)
    return (scaled * (levels - 1)).astype(np.uint8)


def gradient_magnitude(arr: np.ndarray) -> np.ndarray:
    arr = nan_to_num_copy(arr)
    gy, gx = np.gradient(arr)
    return np.sqrt(gx**2 + gy**2).astype(np.float32)


def local_std(arr: np.ndarray, size: int = 5) -> np.ndarray:
    arr = nan_to_num_copy(arr)
    mean = get_uniform_blur(arr, neighborhood_size=size)
    mean_sq = get_uniform_blur(arr**2, neighborhood_size=size)
    var = np.maximum(mean_sq - mean**2, 0.0)
    return np.sqrt(var).astype(np.float32)


def choose_base_band(arrays: dict[str, np.ndarray]) -> tuple[str, np.ndarray]:
    for name in fe_cfg.naip.base_band_preference:
        if name in arrays:
            return name, arrays[name]
    first = next(iter(arrays.keys()))
    return first, arrays[first]


def get_simple_color_diff_kernels() -> dict[str, np.ndarray]:
    return {
        "sobel_x_like": np.array([[-1, 0, 1], [-2, 0, 2], [-1, 0, 1]], dtype=np.float32),
        "sobel_y_like": np.array([[-1, -2, -1], [0, 0, 0], [1, 2, 1]], dtype=np.float32),
        "laplacian_like": np.array([[0, 1, 0], [1, -4, 1], [0, 1, 0]], dtype=np.float32),
    }

In [41]:
def active_naip_family_names() -> tuple[str, ...]:
    enabled = set(fe_cfg.naip.enabled_families) | set(fe_cfg.naip.heavy_families_enabled)
    ordered = []
    for key in NAIP_FAMILY_SPECS:
        if key in enabled:
            ordered.append(key)
    return tuple(ordered)


def compute_naip_family_on_chunk(
    family_name: str,
    arrays: dict[str, np.ndarray],
) -> dict[str, np.ndarray]:
    out = {}

    if family_name == "raw":
        for name, arr in arrays.items():
            out[f"naip_raw_{name}"] = arr.astype(np.float32)
        return out

    if family_name == "veg_idx":
        red = arrays.get("red")
        green = arrays.get("green")
        blue = arrays.get("blue")
        nir = arrays.get("nir")
        if red is not None and nir is not None:
            out["naip_idx_ndvi"] = safe_divide(nir - red, nir + red)
        if red is not None and green is not None and blue is not None:
            out["naip_idx_vari"] = safe_divide(green - red, green + red - blue)
        if red is not None and green is not None:
            out["naip_idx_g_minus_r"] = (green - red).astype(np.float32)
        if green is not None and blue is not None:
            out["naip_idx_g_minus_b"] = (green - blue).astype(np.float32)
        return out

    base_name, base = choose_base_band(arrays)
    base_clean = nan_to_num_copy(base)
    base_tex = quantize_image(base_clean, levels=fe_cfg.naip.quantize_levels) if fe_cfg.naip.quantize_for_texture else base_clean

    if family_name == "texture":
        out["naip_tex_gradmag"] = gradient_magnitude(base_clean)
        out["naip_tex_localstd_5"] = local_std(base_clean, size=5)
        out["naip_tex_entropy"] = get_entropy_feature(
            base_tex,
            neighborhood_size=fe_cfg.naip.texture_entropy_window
        ).astype(np.float32)
        out[f"naip_tex_lbp_r{fe_cfg.naip.texture_lbp_radius}"] = get_fast_lbp_texture(
            base_tex, radius=fe_cfg.naip.texture_lbp_radius
        ).astype(np.float32)
        for size in fe_cfg.naip.texture_blur_sizes:
            out[f"naip_tex_blur_{size}"] = get_uniform_blur(base_clean, neighborhood_size=size).astype(np.float32)
        return out

    if family_name == "multiscale":
        selected = [name for name in ["red", "green", "nir"] if name in arrays]
        if not selected:
            selected = [base_name]
        for band_name in selected:
            band = nan_to_num_copy(arrays[band_name])
            for size in fe_cfg.naip.multiscale_sizes:
                out[f"naip_ms_mean_{band_name}_{size}"] = get_uniform_blur(band, neighborhood_size=size).astype(np.float32)
                out[f"naip_ms_std_{band_name}_{size}"] = local_std(band, size=size)
        return out

    if family_name == "color_diff":
        for kernel_name, kernel in get_simple_color_diff_kernels().items():
            out[f"naip_cd_{kernel_name}"] = get_color_diff(base_clean, kernel).astype(np.float32)
        return out

    if family_name == "granulometry":
        cube = get_granulometry_features(base_clean, scales=list(fe_cfg.naip.granulometry_scales))
        for i in range(cube.shape[2]):
            out[f"naip_gran_{i:02d}"] = cube[:, :, i].astype(np.float32)
        return out

    if family_name == "fractal":
        out["naip_frac_fd"] = get_fractal_dimension_map(base_clean, scales=list(fe_cfg.naip.fractal_scales)).astype(np.float32)
        return out

    if family_name == "wavelet":
        cube = get_wavelet_features(
            base_clean,
            wavelet_type=fe_cfg.naip.wavelet_type,
            level=fe_cfg.naip.wavelet_level,
        )
        for i in range(cube.shape[2]):
            out[f"naip_wav_{i:02d}"] = cube[:, :, i].astype(np.float32)
        return out

    if family_name == "gabor":
        idx = 0
        for freq in fe_cfg.naip.gabor_frequencies:
            for theta in fe_cfg.naip.gabor_thetas:
                out[f"naip_gabor_{idx:02d}"] = fast_cpu_gabor(base_clean, frequency=freq, theta=theta).astype(np.float32)
                idx += 1
        return out

    if family_name == "ldp":
        out["naip_ldp"] = get_ldp_feature(base_tex, k=fe_cfg.naip.ldp_k).astype(np.float32)
        return out

    if family_name == "morphology":
        for size in fe_cfg.naip.morphology_window_sizes:
            opened = grey_opening(base_clean, size=(size, size)).astype(np.float32)
            closed = grey_closing(base_clean, size=(size, size)).astype(np.float32)
            out[f"naip_morph_open_{size}"] = opened
            out[f"naip_morph_close_{size}"] = closed
            out[f"naip_morph_open_resid_{size}"] = (base_clean - opened).astype(np.float32)
            out[f"naip_morph_close_resid_{size}"] = (closed - base_clean).astype(np.float32)
        return out

    raise KeyError(f"Unsupported NAIP family: {family_name}")

In [42]:
def family_chunk_stage_cache_dir(site_id: str, source_name: str, family_name: str, chunk_id: str, data_sig: str, config_sig: str) -> Path:
    return stage_cache_dir(
        stage_name="family_compute",
        site_id=site_id,
        source_name=f"{source_name}__{family_name}__{chunk_id}",
        data_signature=data_sig,
        config_signature=config_sig,
    )


def family_chunk_signatures(
    *,
    site_id: str,
    source_name: str,
    family_name: str,
    chunk_record: ChunkRecord,
    band_names: Iterable[str],
) -> tuple[str, str]:
    data_sig = hash_payload(
        {
            "site_id": site_id,
            "source_name": source_name,
            "family_name": family_name,
            "chunk_id": chunk_record.chunk_id,
            "chunk_bounds": asdict(chunk_record),
            "band_names": sorted(list(band_names)),
        }
    )
    config_sig = hash_payload(
        {
            "family_name": family_name,
            "naip_config": asdict(fe_cfg.naip),
            "version": fe_cfg.version,
        }
    )
    return data_sig, config_sig

In [43]:
def load_npz_dict(path: str | Path) -> dict[str, np.ndarray]:
    data = np.load(path)
    return {k: data[k] for k in data.files}


def run_naip_family_on_chunk_with_cache(
    *,
    site_id: str,
    family_name: str,
    aligned_bundle: SourceRasterBundle,
    chunk_record: ChunkRecord,
    config_sig: str,
) -> tuple[dict[str, np.ndarray], PersistedArtifactRecord | None]:
    family_spec = NAIP_FAMILY_SPECS[family_name]
    chunk_arrays_expanded, expanded_bounds = slice_chunk_from_arrays(
        aligned_bundle.arrays,
        chunk_record,
        full_height=aligned_bundle.shape[0],
        full_width=aligned_bundle.shape[1],
        halo_px=family_spec.required_halo_px,
    )

    data_sig, family_cfg_sig = family_chunk_signatures(
        site_id=site_id,
        source_name="naip",
        family_name=family_name,
        chunk_record=chunk_record,
        band_names=chunk_arrays_expanded.keys(),
    )
    cache_dir = family_chunk_stage_cache_dir(
        site_id,
        "naip",
        family_name,
        chunk_record.chunk_id,
        data_sig,
        family_cfg_sig,
    )
    manifest_path = cache_dir / "stage_cache_manifest.json"

    rel_path = render_artifact_rel_path(
        "family_chunk_npz",
        site_id=site_id,
        config_signature=config_sig,
        source_name="naip",
        family_name=family_name,
        chunk_id=chunk_record.chunk_id,
    )
    local_npz = local_artifact_abs_path(rel_path)

    if is_valid_stage_cache(
        stage_cache_dir=cache_dir,
        expected_stage_name="family_compute",
        expected_data_signature=data_sig,
        expected_config_signature=family_cfg_sig,
    ):
        if local_npz.exists():
            LOGGER.info(
                "FAMILY CHUNK CACHE HIT (local) | site=%s | family=%s | chunk=%s",
                site_id, family_name, chunk_record.chunk_id
            )
            return load_npz_dict(local_npz), None

        if remote_artifact_exists(rel_path):
            LOGGER.info(
                "FAMILY CHUNK CACHE HIT (remote) | site=%s | family=%s | chunk=%s",
                site_id, family_name, chunk_record.chunk_id
            )
            pulled = artifact_store.pull(rel_path, local_path=local_npz)
            return load_npz_dict(pulled), None

    with timed_stage(
        "family_chunk_compute",
        site_id=site_id,
        source_name="naip",
        family_name=f"{family_name}:{chunk_record.chunk_id}",
        unit_amount=array_megapixels(next(iter(chunk_arrays_expanded.values()))),
    ):
        expanded_result = compute_naip_family_on_chunk(family_name, chunk_arrays_expanded)
        interior_result = crop_chunk_interior(expanded_result, chunk_record, expanded_bounds)

        persist_rec = None
        if fe_cfg.persistence.persist_chunk_outputs:
            persist_rec = persist_npz_artifact(
                interior_result,
                artifact_key="family_chunk_npz",
                site_id=site_id,
                config_sig=config_sig,
                source_name="naip",
                family_name=family_name,
                chunk_id=chunk_record.chunk_id,
            )

        write_stage_cache_manifest(
            stage_cache_dir=cache_dir,
            stage_name="family_compute",
            data_signature=data_sig,
            config_signature=family_cfg_sig,
            module_variants=[],
            artifact_paths={
                "family_chunk_rel_path": rel_path,
                "persisted_local_path": persist_rec.local_path if persist_rec else None,
                "persisted_remote_ref": persist_rec.remote_ref if persist_rec else None,
            },
            success=True,
            notes=[f"Computed family chunk for {family_name} / {chunk_record.chunk_id}"],
        )

        return interior_result, persist_rec

In [44]:
def stack_registry_cache_dir(site_id: str, config_sig: str) -> Path:
    return stage_cache_dir(
        stage_name="stack_finalize",
        site_id=site_id,
        source_name="stack_registry",
        data_signature=site_id,
        config_signature=config_sig,
    )


def load_or_init_stack_registry(site_id: str, config_sig: str) -> RasterStackRegistry:
    cache_dir = stack_registry_cache_dir(site_id, config_sig)
    path = cache_dir / "stack_registry.json"

    if path.exists():
        payload = read_json(path)
        layers = [RasterLayerRecord(**row) for row in payload["layers"]]
        return RasterStackRegistry(site_id=payload["site_id"], config_signature=payload["config_signature"], layers=layers)

    return RasterStackRegistry(site_id=site_id, config_signature=config_sig, layers=[])


def save_stack_registry(registry: RasterStackRegistry) -> PersistedArtifactRecord:
    cache_dir = stack_registry_cache_dir(registry.site_id, registry.config_signature)
    path = cache_dir / "stack_registry.json"

    write_json(
        path,
        {
            "site_id": registry.site_id,
            "config_signature": registry.config_signature,
            "layers": [asdict(layer) for layer in registry.layers],
        },
    )

    rel_path = render_artifact_rel_path(
        "stack_registry",
        site_id=registry.site_id,
        config_signature=registry.config_signature,
    )
    final_local = local_artifact_abs_path(rel_path)
    final_local.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(path, final_local)

    rec = push_artifact_if_needed(final_local, artifact_key="stack_registry", rel_path=rel_path)
    return rec


def register_family_chunk_outputs(
    registry: RasterStackRegistry,
    *,
    family_name: str,
    chunk_record: ChunkRecord,
    chunk_arrays: dict[str, np.ndarray],
    persist_rec: PersistedArtifactRecord | None,
):
    for layer_name, arr in chunk_arrays.items():
        registry.layers.append(
            RasterLayerRecord(
                site_id=registry.site_id,
                source_name="naip",
                family_name=family_name,
                layer_name=f"{layer_name}::{chunk_record.chunk_id}",
                local_path=persist_rec.local_path if persist_rec else None,
                remote_ref=persist_rec.remote_ref if persist_rec else None,
                chunked=True,
                dtype=str(arr.dtype),
                shape=tuple(arr.shape),
                notes=[chunk_record.chunk_id],
            )
        )

In [45]:
def run_naip_chunked_pipeline(
    site_id: str,
    *,
    assets: SiteAssetBundle | None = None,
    grid: CanonicalGrid | None = None,
    chunk_manifest: ChunkManifest | None = None,
) -> RasterStackRegistry:
    config_sig = fe_config_signature()

    if assets is None:
        assets = prepare_site_assets(site_id, force_refresh=fe_cfg.force_refresh_assets)
    if grid is None:
        grid = build_canonical_grid_for_site(site_id, assets=assets, force_refresh=fe_cfg.force_refresh_features)
    if chunk_manifest is None:
        chunk_manifest = build_chunk_manifest(grid, force_refresh=fe_cfg.force_rebuild_chunk_manifest)

    naip_path = assets.source_assets["naip"]
    raw_bundle = read_raster_bundle(
        naip_path,
        site_id=site_id,
        source_name="naip",
        band_names=infer_naip_band_names(naip_path),
    )
    aligned_bundle = align_bundle_to_grid(
        raw_bundle,
        dst_grid=grid,
        resampling=SOURCE_SPECS["naip"].default_resampling,
    )

    family_names = active_naip_family_names()
    registry = load_or_init_stack_registry(site_id, config_sig)

    LOGGER.info(
        "NAIP CHUNKED RUN | site=%s | families=%s | n_chunks=%d",
        site_id, family_names, len(chunk_manifest.records)
    )

    for family_name in family_names:
        LOGGER.info("NAIP FAMILY START | site=%s | family=%s", site_id, family_name)

        for idx, record in enumerate(chunk_manifest.records, start=1):
            est_remaining = estimate_remaining_time(
                "family_chunk_compute",
                remaining_units=max(len(chunk_manifest.records) - idx, 0),
            )
            if est_remaining is not None:
                LOGGER.info(
                    "NAIP ETA | site=%s | family=%s | chunk=%s | est_remaining_sec=%.2f",
                    site_id, family_name, record.chunk_id, est_remaining
                )

            chunk_arrays, persist_rec = run_naip_family_on_chunk_with_cache(
                site_id=site_id,
                family_name=family_name,
                aligned_bundle=aligned_bundle,
                chunk_record=record,
                config_sig=config_sig,
            )

            register_family_chunk_outputs(
                registry,
                family_name=family_name,
                chunk_record=record,
                chunk_arrays=chunk_arrays,
                persist_rec=persist_rec,
            )

        LOGGER.info("NAIP FAMILY DONE | site=%s | family=%s", site_id, family_name)

    save_stack_registry(registry)
    LOGGER.info("NAIP CHUNKED RUN COMPLETE | site=%s | registered_layers=%d", site_id, len(registry.layers))
    return registry

In [50]:
def refresh_artifact_store():
    global artifact_store
    artifact_store = build_artifact_store(fe_cfg.storage)
    LOGGER.info("Refreshed artifact store | type=%s", type(artifact_store).__name__)
    return artifact_store

In [51]:
fe_cfg.storage.enable_drive_store = True
fe_cfg.storage.use_hybrid_store = True
fe_cfg.storage.enable_local_store = True

fe_cfg.persistence.push_large_artifacts_to_remote = True
fe_cfg.persistence.prune_local_after_remote_push = True
fe_cfg.persistence.verify_remote_before_prune = True

artifact_store = refresh_artifact_store()
print(type(artifact_store).__name__)

2026-04-14 22:15:29,719 | INFO     | features.notebook | Using HybridArtifactStore
2026-04-14 22:15:29,720 | INFO     | features.notebook | Refreshed artifact store | type=HybridArtifactStore

HybridArtifactStore

In [ ]:
TEST_SITE = fe_cfg.sites[0]

naip_stack_registry = run_naip_chunked_pipeline(
    TEST_SITE,
    assets=site_assets,
    grid=canonical_grid,
    chunk_manifest=chunk_manifest,
)

print("Registered layers:", len(naip_stack_registry.layers))
display(pd.DataFrame([asdict(x) for x in naip_stack_registry.layers[:10]]))

2026-04-14 21:41:36,033 | INFO     | features.notebook | NAIP CHUNKED RUN | site=calaveras-big-trees | families=('raw', 'veg_idx', 'texture', 'multiscale') | n_chunks=48
2026-04-14 21:41:36,034 | INFO     | features.notebook | NAIP FAMILY START | site=calaveras-big-trees | family=raw
2026-04-14 21:41:36,117 | INFO     | features.notebook | START | stage=family_chunk_compute | site=calaveras-big-trees | source=naip | family=raw:chunk_00000
2026-04-14 21:41:36,341 | INFO     | features.notebook | END   | stage=family_chunk_compute | site=calaveras-big-trees | source=naip | family=raw:chunk_00000 | duration=0.22s | sec_per_unit=0.2131
2026-04-14 21:41:36,342 | INFO     | features.notebook | NAIP ETA | site=calaveras-big-trees | family=raw | chunk=chunk_00001 | est_remaining_sec=9.80
2026-04-14 21:41:36,383 | INFO     | features.notebook | START | stage=family_chunk_compute | site=calaveras-big-trees | source=naip | family=raw:chunk_00001
2026-04-14 21:41:36,500 | INFO     | features.notebook | END   | stage=family_chunk_compute | site=calaveras-big-trees | source=naip | family=raw:chunk_00001 | duration=0.12s | sec_per_unit=0.1108
2026-04-14 21:41:36,500 | INFO     | features.notebook | NAIP ETA | site=calaveras-big-trees | family=raw | chunk=chunk_00002 | est_remaining_sec=7.29
2026-04-14 21:41:36,545 | INFO     | features.notebook | START | stage=family_chunk_compute | site=calaveras-big-trees | source=naip | family=raw:chunk_00002
2026-04-14 21:41:36,655 | INFO     | features.notebook | END   | stage=family_chunk_compute | site=calaveras-big-trees | source=naip | family=raw:chunk_00002 | duration=0.11s | sec_per_unit=0.1050
2026-04-14 21:41:36,655 | INFO     | features.notebook | NAIP ETA | site=calaveras-big-trees | family=raw | chunk=chunk_00003 | est_remaining_sec=6.29
2026-04-14 21:41:36,698 | INFO     | features.notebook | START | stage=family_chunk_compute | site=calaveras-big-trees | source=naip | family=raw:chunk_00003
2026-04-14 21:41:36,808 | INFO     | features.notebook | END   | stage=family_chunk_compute | site=calaveras-big-trees | source=naip | family=raw:chunk_00003 | duration=0.11s | sec_per_unit=0.1047
2026-04-14 21:41:36,808 | INFO     | features.notebook | NAIP ETA | site=calaveras-big-trees | family=raw | chunk=chunk_00004 | est_remaining_sec=5.74
2026-04-14 21:41:36,850 | INFO     | features.notebook | START | stage=family_chunk_compute | site=calaveras-big-trees | source=naip | family=raw:chunk_00004
2026-04-14 21:41:37,181 | INFO     | features.notebook | END   | stage=family_chunk_compute | site=calaveras-big-trees | source=naip | family=raw:chunk_00004 | duration=0.33s | sec_per_unit=0.3157
2026-04-14 21:41:37,182 | INFO     | features.notebook | NAIP ETA | site=calaveras-big-trees | family=raw | chunk=chunk_00005 | est_remaining_sec=7.13
2026-04-14 21:41:37,226 | INFO     | features.notebook | START | stage=family_chunk_compute | site=calaveras-big-trees | source=naip | family=raw:chunk_00005
2026-04-14 21:41:38,063 | INFO     | features.notebook | END   | stage=family_chunk_compute | site=calaveras-big-trees | source=naip | family=raw:chunk_00005 | duration=0.84s | sec_per_unit=0.7978
2026-04-14 21:41:38,064 | INFO     | features.notebook | NAIP ETA | site=calaveras-big-trees | family=raw | chunk=chunk_00006 | est_remaining_sec=11.26
2026-04-14 21:41:38,108 | INFO     | features.notebook | START | stage=family_chunk_compute | site=calaveras-big-trees | source=naip | family=raw:chunk_00006
2026-04-14 21:41:39,689 | INFO     | features.notebook | END   | stage=family_chunk_compute | site=calaveras-big-trees | source=naip | family=raw:chunk_00006 | duration=1.58s | sec_per_unit=1.5078
2026-04-14 21:41:39,690 | INFO     | features.notebook | NAIP ETA | site=calaveras-big-trees | family=raw | chunk=chunk_00007 | est_remaining_sec=18.03
2026-04-14 21:41:39,738 | INFO     | features.notebook | START | stage=family_chunk_compute | site=calaveras-big-trees | source=naip | family=raw:chunk_00007
2026-04-14 21:41:39,893 | INFO     | features.notebook | END   | stage=family_chunk_compute | site=calaveras-big-trees | source=naip | family=raw:chunk_00007 | duration=0.16s | sec_per_unit=0.6594
2026-04-14 21:41:39,893 | INFO     | features.notebook | NAIP ETA | site=calaveras-big-trees | family=raw | chunk=chunk_00008 | est_remaining_sec=18.59
2026-04-14 21:41:39,937 | INFO     | features.notebook | START | stage=family_chunk_compute | site=calaveras-big-trees | source=naip | family=raw:chunk_00008
2026-04-14 21:41:40,048 | INFO     | features.notebook | END   | stage=family_chunk_compute | site=calaveras-big-trees | source=naip | family=raw:chunk_00008 | duration=0.11s | sec_per_unit=0.1061
2026-04-14 21:41:40,048 | INFO     | features.notebook | NAIP ETA | site=calaveras-big-trees | family=raw | chunk=chunk_00009 | est_remaining_sec=16.55
2026-04-14 21:41:40,094 | INFO     | features.notebook | START | stage=family_chunk_compute | site=calaveras-big-trees | source=naip | family=raw:chunk_00009
2026-04-14 21:41:40,204 | INFO     | features.notebook | END   | stage=family_chunk_compute | site=calaveras-big-trees | source=naip | family=raw:chunk_00009 | duration=0.11s | sec_per_unit=0.1054
2026-04-14 21:41:40,205 | INFO     | features.notebook | NAIP ETA | site=calaveras-big-trees | family=raw | chunk=chunk_00010 | est_remaining_sec=14.90
2026-04-14 21:41:40,248 | INFO     | features.notebook | START | stage=family_chunk_compute | site=calaveras-big-trees | source=naip | family=raw:chunk_00010
2026-04-14 21:41:40,379 | INFO     | features.notebook | END   | stage=family_chunk_compute | site=calaveras-big-trees | source=naip | family=raw:chunk_00010 | duration=0.13s | sec_per_unit=0.1244
2026-04-14 21:41:40,379 | INFO     | features.notebook | NAIP ETA | site=calaveras-big-trees | family=raw | chunk=chunk_00011 | est_remaining_sec=13.58
2026-04-14 21:41:40,422 | INFO     | features.notebook | START | stage=family_chunk_compute | site=calaveras-big-trees | source=naip | family=raw:chunk_00011
2026-04-14 21:41:41,361 | INFO     | features.notebook | END   | stage=family_chunk_compute | site=calaveras-big-trees | source=naip | family=raw:chunk_00011 | duration=0.94s | sec_per_unit=0.8957
2026-04-14 21:41:41,361 | INFO     | features.notebook | NAIP ETA | site=calaveras-big-trees | family=raw | chunk=chunk_00012 | est_remaining_sec=14.72
2026-04-14 21:41:41,439 | INFO     | features.notebook | START | stage=family_chunk_compute | site=calaveras-big-trees | source=naip | family=raw:chunk_00012
2026-04-14 21:41:43,035 | INFO     | features.notebook | END   | stage=family_chunk_compute | site=calaveras-big-trees | source=naip | family=raw:chunk_00012 | duration=1.60s | sec_per_unit=1.5220
2026-04-14 21:41:43,036 | INFO     | features.notebook | NAIP ETA | site=calaveras-big-trees | family=raw | chunk=chunk_00013 | est_remaining_sec=17.18
2026-04-14 21:41:43,077 | INFO     | features.notebook | START | stage=family_chunk_compute | site=calaveras-big-trees | source=naip | family=raw:chunk_00013
2026-04-14 21:41:44,681 | INFO     | features.notebook | END   | stage=family_chunk_compute | site=calaveras-big-trees | source=naip | family=raw:chunk_00013 | duration=1.60s | sec_per_unit=1.5296
2026-04-14 21:41:44,682 | INFO     | features.notebook | NAIP ETA | site=calaveras-big-trees | family=raw | chunk=chunk_00014 | est_remaining_sec=19.09
2026-04-14 21:41:44,724 | INFO     | features.notebook | START | stage=family_chunk_compute | site=calaveras-big-trees | source=naip | family=raw:chunk_00014
2026-04-14 21:41:45,403 | INFO     | features.notebook | END   | stage=family_chunk_compute | site=calaveras-big-trees | source=naip | family=raw:chunk_00014 | duration=0.68s | sec_per_unit=0.6471
2026-04-14 21:41:45,403 | INFO     | features.notebook | NAIP ETA | site=calaveras-big-trees | family=raw | chunk=chunk_00015 | est_remaining_sec=18.65
2026-04-14 21:41:45,445 | INFO     | features.notebook | START | stage=family_chunk_compute | site=calaveras-big-trees | source=naip | family=raw:chunk_00015
2026-04-14 21:41:45,487 | INFO     | features.notebook | END   | stage=family_chunk_compute | site=calaveras-big-trees | source=naip | family=raw:chunk_00015 | duration=0.04s | sec_per_unit=0.1758
2026-04-14 21:41:45,487 | INFO     | features.notebook | NAIP ETA | site=calaveras-big-trees | family=raw | chunk=chunk_00016 | est_remaining_sec=17.28
2026-04-14 21:41:45,534 | INFO     | features.notebook | START | stage=family_chunk_compute | site=calaveras-big-trees | source=naip | family=raw:chunk_00016
2026-04-14 21:41:45,644 | INFO     | features.notebook | END   | stage=family_chunk_compute | site=calaveras-big-trees | source=naip | family=raw:chunk_00016 | duration=0.11s | sec_per_unit=0.1049
2026-04-14 21:41:45,645 | INFO     | features.notebook | NAIP ETA | site=calaveras-big-trees | family=raw | chunk=chunk_00017 | est_remaining_sec=15.93
2026-04-14 21:41:45,882 | INFO     | features.notebook | START | stage=family_chunk_compute | site=calaveras-big-trees | source=naip | family=raw:chunk_00017
2026-04-14 21:41:46,039 | INFO     | features.notebook | END   | stage=family_chunk_compute | site=calaveras-big-trees | source=naip | family=raw:chunk_00017 | duration=0.16s | sec_per_unit=0.1490
2026-04-14 21:41:46,039 | INFO     | features.notebook | NAIP ETA | site=calaveras-big-trees | family=raw | chunk=chunk_00018 | est_remaining_sec=14.78
2026-04-14 21:41:46,081 | INFO     | features.notebook | START | stage=family_chunk_compute | site=calaveras-big-trees | source=naip | family=raw:chunk_00018
2026-04-14 21:41:47,275 | INFO     | features.notebook | END   | stage=family_chunk_compute | site=calaveras-big-trees | source=naip | family=raw:chunk_00018 | duration=1.19s | sec_per_unit=1.1384
2026-04-14 21:41:47,275 | INFO     | features.notebook | NAIP ETA | site=calaveras-big-trees | family=raw | chunk=chunk_00019 | est_remaining_sec=15.20
2026-04-14 21:41:47,319 | INFO     | features.notebook | START | stage=family_chunk_compute | site=calaveras-big-trees | source=naip | family=raw:chunk_00019
2026-04-14 21:41:48,956 | INFO     | features.notebook | END   | stage=family_chunk_compute | site=calaveras-big-trees | source=naip | family=raw:chunk_00019 | duration=1.64s | sec_per_unit=1.5607
2026-04-14 21:41:48,956 | INFO     | features.notebook | NAIP ETA | site=calaveras-big-trees | family=raw | chunk=chunk_00020 | est_remaining_sec=16.03
2026-04-14 21:41:49,012 | INFO     | features.notebook | START | stage=family_chunk_compute | site=calaveras-big-trees | source=naip | family=raw:chunk_00020
2026-04-14 21:41:50,733 | INFO     | features.notebook | END   | stage=family_chunk_compute | site=calaveras-big-trees | source=naip | family=raw:chunk_00020 | duration=1.72s | sec_per_unit=1.6405
2026-04-14 21:41:50,733 | INFO     | features.notebook | NAIP ETA | site=calaveras-big-trees | family=raw | chunk=chunk_00021 | est_remaining_sec=16.73
2026-04-14 21:41:50,807 | INFO     | features.notebook | START | stage=family_chunk_compute | site=calaveras-big-trees | source=naip | family=raw:chunk_00021
2026-04-14 21:41:51,552 | INFO     | features.notebook | END   | stage=family_chunk_compute | site=calaveras-big-trees | source=naip | family=raw:chunk_00021 | duration=0.74s | sec_per_unit=0.7103
2026-04-14 21:41:51,553 | INFO     | features.notebook | NAIP ETA | site=calaveras-big-trees | family=raw | chunk=chunk_00022 | est_remaining_sec=16.16
2026-04-14 21:41:51,595 | INFO     | features.notebook | START | stage=family_chunk_compute | site=calaveras-big-trees | source=naip | family=raw:chunk_00022
2026-04-14 21:41:51,719 | INFO     | features.notebook | END   | stage=family_chunk_compute | site=calaveras-big-trees | source=naip | family=raw:chunk_00022 | duration=0.12s | sec_per_unit=0.1183
2026-04-14 21:41:51,720 | INFO     | features.notebook | NAIP ETA | site=calaveras-big-trees | family=raw | chunk=chunk_00023 | est_remaining_sec=14.97
2026-04-14 21:41:52,000 | INFO     | features.notebook | START | stage=family_chunk_compute | site=calaveras-big-trees | source=naip | family=raw:chunk_00023
2026-04-14 21:41:52,042 | INFO     | features.notebook | END   | stage=family_chunk_compute | site=calaveras-big-trees | source=naip | family=raw:chunk_00023 | duration=0.04s | sec_per_unit=0.1763
2026-04-14 21:41:52,042 | INFO     | features.notebook | NAIP ETA | site=calaveras-big-trees | family=raw | chunk=chunk_00024 | est_remaining_sec=13.91
2026-04-14 21:41:52,084 | INFO     | features.notebook | START | stage=family_chunk_compute | site=calaveras-big-trees | source=naip | family=raw:chunk_00024
2026-04-14 21:41:53,161 | INFO     | features.notebook | END   | stage=family_chunk_compute | site=calaveras-big-trees | source=naip | family=raw:chunk_00024 | duration=1.08s | sec_per_unit=1.0274
2026-04-14 21:41:53,162 | INFO     | features.notebook | NAIP ETA | site=calaveras-big-trees | family=raw | chunk=chunk_00025 | est_remaining_sec=13.68
2026-04-14 21:41:53,205 | INFO     | features.notebook | START | stage=family_chunk_compute | site=calaveras-big-trees | source=naip | family=raw:chunk_00025
2026-04-14 21:41:54,503 | INFO     | features.notebook | END   | stage=family_chunk_compute | site=calaveras-big-trees | source=naip | family=raw:chunk_00025 | duration=1.30s | sec_per_unit=1.2375
2026-04-14 21:41:54,503 | INFO     | features.notebook | NAIP ETA | site=calaveras-big-trees | family=raw | chunk=chunk_00026 | est_remaining_sec=13.56
2026-04-14 21:41:54,545 | INFO     | features.notebook | START | stage=family_chunk_compute | site=calaveras-big-trees | source=naip | family=raw:chunk_00026
2026-04-14 21:41:56,211 | INFO     | features.notebook | END   | stage=family_chunk_compute | site=calaveras-big-trees | source=naip | family=raw:chunk_00026 | duration=1.67s | sec_per_unit=1.5890
2026-04-14 21:41:56,212 | INFO     | features.notebook | NAIP ETA | site=calaveras-big-trees | family=raw | chunk=chunk_00027 | est_remaining_sec=13.61
2026-04-14 21:41:56,264 | INFO     | features.notebook | START | stage=family_chunk_compute | site=calaveras-big-trees | source=naip | family=raw:chunk_00027
2026-04-14 21:41:57,866 | INFO     | features.notebook | END   | stage=family_chunk_compute | site=calaveras-big-trees | source=naip | family=raw:chunk_00027 | duration=1.60s | sec_per_unit=1.5281
2026-04-14 21:41:57,867 | INFO     | features.notebook | NAIP ETA | site=calaveras-big-trees | family=raw | chunk=chunk_00028 | est_remaining_sec=13.50
2026-04-14 21:41:57,909 | INFO     | features.notebook | START | stage=family_chunk_compute | site=calaveras-big-trees | source=naip | family=raw:chunk_00028
2026-04-14 21:41:58,284 | INFO     | features.notebook | END   | stage=family_chunk_compute | site=calaveras-big-trees | source=naip | family=raw:chunk_00028 | duration=0.38s | sec_per_unit=0.3581
2026-04-14 21:41:58,285 | INFO     | features.notebook | NAIP ETA | site=calaveras-big-trees | family=raw | chunk=chunk_00029 | est_remaining_sec=12.57
2026-04-14 21:41:58,327 | INFO     | features.notebook | START | stage=family_chunk_compute | site=calaveras-big-trees | source=naip | family=raw:chunk_00029
2026-04-14 21:41:58,437 | INFO     | features.notebook | END   | stage=family_chunk_compute | site=calaveras-big-trees | source=naip | family=raw:chunk_00029 | duration=0.11s | sec_per_unit=0.1049
2026-04-14 21:41:58,438 | INFO     | features.notebook | NAIP ETA | site=calaveras-big-trees | family=raw | chunk=chunk_00030 | est_remaining_sec=11.54
2026-04-14 21:41:58,484 | INFO     | features.notebook | START | stage=family_chunk_compute | site=calaveras-big-trees | source=naip | family=raw:chunk_00030
2026-04-14 21:41:58,594 | INFO     | features.notebook | END   | stage=family_chunk_compute | site=calaveras-big-trees | source=naip | family=raw:chunk_00030 | duration=0.11s | sec_per_unit=0.1051
2026-04-14 21:41:58,595 | INFO     | features.notebook | NAIP ETA | site=calaveras-big-trees | family=raw | chunk=chunk_00031 | est_remaining_sec=10.56
2026-04-14 21:41:58,639 | INFO     | features.notebook | START | stage=family_chunk_compute | site=calaveras-big-trees | source=naip | family=raw:chunk_00031
2026-04-14 21:41:58,681 | INFO     | features.notebook | END   | stage=family_chunk_compute | site=calaveras-big-trees | source=naip | family=raw:chunk_00031 | duration=0.04s | sec_per_unit=0.1768
2026-04-14 21:41:58,681 | INFO     | features.notebook | NAIP ETA | site=calaveras-big-trees | family=raw | chunk=chunk_00032 | est_remaining_sec=9.68
2026-04-14 21:41:58,723 | INFO     | features.notebook | START | stage=family_chunk_compute | site=calaveras-big-trees | source=naip | family=raw:chunk_00032
2026-04-14 21:42:00,101 | INFO     | features.notebook | END   | stage=family_chunk_compute | site=calaveras-big-trees | source=naip | family=raw:chunk_00032 | duration=1.38s | sec_per_unit=1.3143
2026-04-14 21:42:00,102 | INFO     | features.notebook | NAIP ETA | site=calaveras-big-trees | family=raw | chunk=chunk_00033 | est_remaining_sec=9.32
2026-04-14 21:42:00,195 | INFO     | features.notebook | START | stage=family_chunk_compute | site=calaveras-big-trees | source=naip | family=raw:chunk_00033
2026-04-14 21:42:01,885 | INFO     | features.notebook | END   | stage=family_chunk_compute | site=calaveras-big-trees | source=naip | family=raw:chunk_00033 | duration=1.69s | sec_per_unit=1.6123
2026-04-14 21:42:01,887 | INFO     | features.notebook | NAIP ETA | site=calaveras-big-trees | family=raw | chunk=chunk_00034 | est_remaining_sec=9.01
2026-04-14 21:42:01,940 | INFO     | features.notebook | START | stage=family_chunk_compute | site=calaveras-big-trees | source=naip | family=raw:chunk_00034
2026-04-14 21:42:03,010 | INFO     | features.notebook | END   | stage=family_chunk_compute | site=calaveras-big-trees | source=naip | family=raw:chunk_00034 | duration=1.07s | sec_per_unit=1.0203
2026-04-14 21:42:03,011 | INFO     | features.notebook | NAIP ETA | site=calaveras-big-trees | family=raw | chunk=chunk_00035 | est_remaining_sec=8.43
2026-04-14 21:42:03,055 | INFO     | features.notebook | START | stage=family_chunk_compute | site=calaveras-big-trees | source=naip | family=raw:chunk_00035
2026-04-14 21:42:03,481 | INFO     | features.notebook | END   | stage=family_chunk_compute | site=calaveras-big-trees | source=naip | family=raw:chunk_00035 | duration=0.43s | sec_per_unit=0.4064
2026-04-14 21:42:03,483 | INFO     | features.notebook | NAIP ETA | site=calaveras-big-trees | family=raw | chunk=chunk_00036 | est_remaining_sec=7.64
2026-04-14 21:42:03,526 | INFO     | features.notebook | START | stage=family_chunk_compute | site=calaveras-big-trees | source=naip | family=raw:chunk_00036
2026-04-14 21:42:03,637 | INFO     | features.notebook | END   | stage=family_chunk_compute | site=calaveras-big-trees | source=naip | family=raw:chunk_00036 | duration=0.11s | sec_per_unit=0.1054
2026-04-14 21:42:03,637 | INFO     | features.notebook | NAIP ETA | site=calaveras-big-trees | family=raw | chunk=chunk_00037 | est_remaining_sec=6.78
2026-04-14 21:42:03,831 | INFO     | features.notebook | START | stage=family_chunk_compute | site=calaveras-big-trees | source=naip | family=raw:chunk_00037
2026-04-14 21:42:03,941 | INFO     | features.notebook | END   | stage=family_chunk_compute | site=calaveras-big-trees | source=naip | family=raw:chunk_00037 | duration=0.11s | sec_per_unit=0.1049
2026-04-14 21:42:03,942 | INFO     | features.notebook | NAIP ETA | site=calaveras-big-trees | family=raw | chunk=chunk_00038 | est_remaining_sec=5.97
2026-04-14 21:42:03,983 | INFO     | features.notebook | START | stage=family_chunk_compute | site=calaveras-big-trees | source=naip | family=raw:chunk_00038
2026-04-14 21:42:04,093 | INFO     | features.notebook | END   | stage=family_chunk_compute | site=calaveras-big-trees | source=naip | family=raw:chunk_00038 | duration=0.11s | sec_per_unit=0.1047

Registered layers: 1536

,site_id,source_name,family_name,layer_name,local_path,remote_ref,chunked,dtype,shape,notes
0,calaveras-big-trees,naip,raw,naip_raw_red::chunk_00000,/home/jovyan/work/Dry-shRub/shrub/Final/artifa...,None,True,float32,"(1024, 1024)",[chunk_00000]
1,calaveras-big-trees,naip,raw,naip_raw_green::chunk_00000,/home/jovyan/work/Dry-shRub/shrub/Final/artifa...,None,True,float32,"(1024, 1024)",[chunk_00000]
2,calaveras-big-trees,naip,raw,naip_raw_blue::chunk_00000,/home/jovyan/work/Dry-shRub/shrub/Final/artifa...,None,True,float32,"(1024, 1024)",[chunk_00000]
3,calaveras-big-trees,naip,raw,naip_raw_nir::chunk_00000,/home/jovyan/work/Dry-shRub/shrub/Final/artifa...,None,True,float32,"(1024, 1024)",[chunk_00000]
4,calaveras-big-trees,naip,raw,naip_raw_red::chunk_00001,/home/jovyan/work/Dry-shRub/shrub/Final/artifa...,None,True,float32,"(1024, 1024)",[chunk_00001]
5,calaveras-big-trees,naip,raw,naip_raw_green::chunk_00001,/home/jovyan/work/Dry-shRub/shrub/Final/artifa...,None,True,float32,"(1024, 1024)",[chunk_00001]
6,calaveras-big-trees,naip,raw,naip_raw_blue::chunk_00001,/home/jovyan/work/Dry-shRub/shrub/Final/artifa...,None,True,float32,"(1024, 1024)",[chunk_00001]
7,calaveras-big-trees,naip,raw,naip_raw_nir::chunk_00001,/home/jovyan/work/Dry-shRub/shrub/Final/artifa...,None,True,float32,"(1024, 1024)",[chunk_00001]
8,calaveras-big-trees,naip,raw,naip_raw_red::chunk_00002,/home/jovyan/work/Dry-shRub/shrub/Final/artifa...,None,True,float32,"(1024, 1024)",[chunk_00002]
9,calaveras-big-trees,naip,raw,naip_raw_green::chunk_00002,/home/jovyan/work/Dry-shRub/shrub/Final/artifa...,None,True,float32,"(1024, 1024)",[chunk_00002]