# Setup

In [10]:
#!pip install -r requirements.txt

In [2]:
import sys
from pathlib import Path

repo_root = Path.cwd()
while not ((repo_root / "Final").exists() and (repo_root / "Sprint 3").exists()):
    if repo_root.parent == repo_root:
        raise RuntimeError("Could not locate repo root.")
    repo_root = repo_root.parent

if str(repo_root) not in sys.path:
    sys.path.insert(0, str(repo_root))

from dataclasses import asdict, dataclass, field
from pathlib import Path
import json
from datetime import datetime
from typing import Any
import pandas as pd

from Final.config import default_config
from Final.paths import FINAL_ROOT
from Final.shared_utils import setup_logging, get_logger

from Final.models import (
    ExperimentState,
)
from Final.experiment_controller import ExperimentController
from Final.grid_search import GridSearchController
from Final.pipeline_runtime import execute_pipeline_section
from Final.artifact_store import (
    LocalArtifactStore,
    DriveRegistryArtifactStore,
    HybridArtifactStore,
)
from Final.gating import (
    evaluate_module_card,
    decide_module_status,
    module_cards_to_frame,
)
from Final.labeling.pipeline import LabelingPipeline, LabelingPipelineConfig

In [3]:
cfg = default_config()

logger = setup_logging(
    name="shrub",
    log_dir=cfg.output.logs_root,
    log_filename="main_pipeline.log",
    force=True,
)

logger.info("Initialized main pipeline notebook.")
logger.info("FINAL_ROOT = %s", FINAL_ROOT)

MAIN_OUTPUT_ROOT = cfg.output.root / "main"
MAIN_OUTPUT_ROOT.mkdir(parents=True, exist_ok=True)

MAIN_ROOT = MAIN_OUTPUT_ROOT

MAIN_MANIFEST_DIR = MAIN_OUTPUT_ROOT / "manifests"
MAIN_MANIFEST_DIR.mkdir(parents=True, exist_ok=True)

EXPERIMENTS_ROOT = MAIN_ROOT / "experiments"
EXPERIMENTS_ROOT.mkdir(parents=True, exist_ok=True)

2026-04-15 20:59:58 | INFO     | shrub | Initialized main pipeline notebook.
2026-04-15 20:59:58 | INFO     | shrub | FINAL_ROOT = /home/jovyan/work/Dry-shRub/shrub/Final

In [4]:
controller = ExperimentController(
    experiment_root=cfg.output.root / "experiments",
    experiment_name="shrubwise_main",
)

state = controller.load_state()

pipelines = {}

local_store = LocalArtifactStore(
    repo_root=cfg.data.project_root,
    storage_root=cfg.output.root / "artifact_store_local",
)

USE_DRIVE = False

if USE_DRIVE:
    drive_store = DriveRegistryArtifactStore(
        repo_root=cfg.data.project_root,
        registry_path=cfg.output.root / "artifact_registry.yaml",
        drive_config_path=cfg.data.project_root / "drive_config.yaml",
        client_secrets_path=cfg.data.project_root / "client_secrets.json",
        credentials_path=cfg.data.project_root / "pydrive_credentials.json",
    )
    artifact_store = HybridArtifactStore(
        local_store=local_store,
        remote_store=drive_store,
    )
else:
    artifact_store = local_store

grid = GridSearchController(controller=controller)

## Labeling

In [8]:
labeling_cfg = LabelingPipelineConfig(
    sprint3_variant="revised",
    sprint3_variants=("original", "revised"),
    run_sprint3=True,
    max_ptx_per_site=1,
    force_rerun_sprint3=False,
    require_success_artifacts_sprint3=True,
    cleanup_ptx_after_all_variants=True,
    cleanup_stale_ptx_before_run=True,
    stale_ptx_days=2,
    use_shape_descriptors=True,
    use_temporal_confidence=True,
    use_boundary_confidence=True,
    boundary_confidence_mode="universal",
    use_transform_confidence=False,
    use_object_subspace_filter=False,
    rasterization_mode="circle",
    multires=cfg.raster.create_multires,
    site_reference_dates={},
    subspace_min_component_pixels=4,
    subspace_min_object_confidence=0.55,
    subspace_min_transform_confidence=0.50,
    subspace_min_temporal_confidence=0.40,
    subspace_max_height_m=3.5,
    force_rerun_sprint4=False,
    force_refresh_site_assets=False,
    nonfatal_qa_overlay=True,
    allow_adopt_global_outputs=False,
)

cfg.labeling_runtime.storage.enable_local_store = True
cfg.labeling_runtime.storage.enable_drive_store = True
cfg.labeling_runtime.storage.use_hybrid_store = True

cfg.labeling_runtime.storage_policy.push_large_artifacts_to_remote = True
cfg.labeling_runtime.storage_policy.prune_local_after_remote_push = False
cfg.labeling_runtime.storage_policy.verify_remote_before_prune = True

labeling_pipeline = LabelingPipeline(cfg, pipeline_config=labeling_cfg)

pipelines["labeling"] = labeling_pipeline

print("Artifact store type:", type(labeling_pipeline.artifact_store).__name__)
print("Local store enabled:", cfg.labeling_runtime.storage.enable_local_store)
print("Drive store enabled:", cfg.labeling_runtime.storage.enable_drive_store)
print("Hybrid mode:", cfg.labeling_runtime.storage.use_hybrid_store)

2026-04-15 21:01:12 | INFO     | shrub.labeling.pipeline | Using HybridArtifactStore for labeling pipeline
Artifact store type: HybridArtifactStore
Local store enabled: True
Drive store enabled: True
Hybrid mode: True

In [13]:
storage_cfg = cfg.artifact_store

print("client_secrets exists:", Path(storage_cfg.drive_client_secrets_path).exists(), storage_cfg.drive_client_secrets_path)
print("drive_config exists:", Path(storage_cfg.drive_config_path).exists(), storage_cfg.drive_config_path)
print("credentials exists:", Path(storage_cfg.drive_client_secrets_path).exists(), storage_cfg.drive_client_secrets_path)
print("drive_registry exists:", Path(storage_cfg.drive_registry_path).exists(), storage_cfg.drive_registry_path)

store = labeling_pipeline.artifact_store
print("Resolved artifact store:", type(store).__name__)

if hasattr(store, "local_store"):
    print("Hybrid local store root:", store.local_store.storage_root)
if hasattr(store, "remote_store"):
    print("Hybrid remote store type:", type(store.remote_store).__name__)
elif type(store).__name__ != "LocalArtifactStore":
    print("Remote store active:", type(store).__name__)

client_secrets exists: True /home/jovyan/work/Dry-shRub/shrub/client_secrets.json
drive_config exists: True /home/jovyan/work/Dry-shRub/shrub/drive_config.yaml
credentials exists: True /home/jovyan/work/Dry-shRub/shrub/client_secrets.json
drive_registry exists: True /home/jovyan/work/Dry-shRub/shrub/Final/artifact_registry.yaml
Resolved artifact store: HybridArtifactStore
Hybrid local store root: /home/jovyan/work/Dry-shRub/shrub/Final/artifact_store_local
Hybrid remote store type: DriveRegistryArtifactStore

In [14]:
#display(labeling_pipeline.pipeline_spec)
display(labeling_pipeline.runtime_report())
display(grid.pipeline_module_state_frame(labeling_pipeline))

RuntimeCapabilityReport(detected_image_key='intelimon-shrubs', detected_image_alias='pramonettivega/intelimon-shrubs', detected_conda_env=None, capabilities=['runtime:intelimon_sprint3', 'runtime:rasterio', 'runtime:rscript'], available_executables=['Rscript'], available_python_modules=['numpy', 'pandas', 'rasterio', 'scipy'], marker_files_found=[], marker_env_matches={'JUPYTER_IMAGE_SPEC': 'pramonettivega/intelimon-shrubs'}, notes=[])

,pipeline,stage_name,module_name,enabled,variant_name,params
0,labeling,sprint3,labeling.sprint3.execution,True,"('original', 'revised')","{'max_ptx_per_site': 1, 'force_rerun_sprint3':..."
1,labeling,standardize,labeling.standardize.base,True,default,{}
2,labeling,refine,labeling.refine.shape_descriptors,True,enabled,{}
3,labeling,refine,labeling.refine.temporal_confidence,True,enabled,{'site_reference_dates': {}}
4,labeling,refine,labeling.refine.object_subspace_filter,False,disabled,"{'subspace_min_object_confidence': 0.55, 'subs..."
5,labeling,transfer,labeling.transfer.base,True,default,{}
6,labeling,rasterize,labeling.rasterize.mode,True,circle,{}
7,labeling,rasterize,labeling.boundary_confidence,True,universal,{}
8,labeling,rasterize,labeling.mask_subspace_reduction,False,disabled,{'subspace_min_component_pixels': 4}
9,labeling,rasterize,labeling.multires_export,True,default,"{'multires': (1.0, 2.0, 5.0, 10.0)}"

In [15]:
labeling_space_df = grid.section_space_frame(labeling_pipeline).copy()
display(labeling_space_df)
print("Total labeling variants:", len(labeling_space_df))

,config_signature,sprint3_variants,use_temporal_confidence,boundary_confidence_mode,use_object_subspace_filter,max_ptx_per_site
0,074f2c2dc3a8,"original,revised",True,universal,True,1
1,0b9cdfd5f781,"original,revised",True,radial,False,1
2,16774e5c5bc7,"original,revised",True,radial,True,1
3,248d471f5527,revised,True,radial,False,1
4,38814738feeb,revised,True,universal,True,1
5,5725ea41a55c,"original,revised",False,radial,False,1
6,6930be0cde08,"original,revised",False,universal,True,1
7,88fb2c6936cb,"original,revised",True,universal,False,1
8,893d374e5995,"original,revised",False,universal,False,1
9,8d0d163a7065,revised,False,radial,True,1
10,a70cedd9d966,revised,True,radial,True,1
11,c3d868cf458c,revised,False,universal,False,1
12,c6a1b032292a,revised,False,universal,True,1
13,d26a3343dc97,"original,revised",False,radial,True,1
14,e104475dd343,revised,True,universal,False,1
15,fd1d94f36a28,revised,False,radial,False,1

Total labeling variants: 16

In [16]:
TRIAL_ID = "labeling_only_trial_001"

trial_path = controller.trial_path(TRIAL_ID)
if trial_path.exists():
    trial = controller.load_trial(TRIAL_ID)
else:
    trial = controller.create_trial(trial_id=TRIAL_ID)

trial

TrialRecord(trial_id='labeling_only_trial_001', created_at='2026-04-15T02:30:58+00:00', status='section_failed:labeling', section_configs={'labeling': {'sprint3_variant': 'revised', 'use_shape_descriptors': True, 'use_temporal_confidence': True, 'use_boundary_confidence': True, 'use_transform_confidence': False, 'use_object_subspace_filter': False, 'rasterization_mode': 'circle', 'multires': [1.0, 2.0, 5.0, 10.0], 'force_rerun_sprint4': False, 'force_refresh_site_assets': False, 'nonfatal_qa_overlay': True, 'storage': {'enable_local_store': True, 'enable_drive_store': True, 'use_hybrid_store': True, 'push_large_artifacts_to_remote': True, 'prune_local_after_remote_push': True, 'verify_remote_before_prune': True, 'local_storage_root': '/home/jovyan/work/Dry-shRub/shrub/Final/artifacts/labeling/artifact_store_local', 'drive_registry_path': '/home/jovyan/work/Dry-shRub/shrub/Final/artifact_registry.yaml', 'drive_config_path': '/home/jovyan/work/Dry-shRub/shrub/drive_config.yaml', 'client_secrets_path': '/home/jovyan/work/Dry-shRub/shrub/client_secrets.json', 'credentials_path': '/home/jovyan/work/Dry-shRub/shrub/pydrive_credentials.json', 'fail_if_drive_missing': False}, 'run_sprint3': True, 'sprint3_variants': ['original', 'revised'], 'max_ptx_per_site': 1, 'force_rerun_sprint3': False, 'require_success_artifacts_sprint3': True, 'cleanup_ptx_after_all_variants': True, 'cleanup_stale_ptx_before_run': True, 'stale_ptx_days': 2, 'boundary_confidence_mode': 'universal', 'site_reference_dates': {}, 'subspace_min_component_pixels': 4, 'subspace_min_object_confidence': 0.55, 'subspace_min_transform_confidence': 0.5, 'subspace_min_temporal_confidence': 0.4, 'subspace_max_height_m': 3.5, 'allow_adopt_global_outputs': False}}, section_runs={'labeling': SectionRunRecord(section_name='labeling', config_signature='d67331ee1b6f', status='empty_outputs', started_at=None, finished_at='2026-04-15T10:07:15+00:00', metrics={'n_object_rows': 0, 'n_artifact_rows': 0, 'n_sites': 0, 'stage_cache_manifest_count': 2, 'runtime_wall_seconds': 55.588680546032265, 'runtime_max_rss_mb': 284.285, 'runtime_cache_hits': 0, 'runtime_cache_misses': 0}, qa_outputs={'objects_csv': '/home/jovyan/work/Dry-shRub/shrub/Final/artifacts/labeling/pipeline_runs/d67331ee1b6f/summaries/objects_all.csv', 'artifacts_csv': '/home/jovyan/work/Dry-shRub/shrub/Final/artifacts/labeling/pipeline_runs/d67331ee1b6f/summaries/artifacts_all.csv', 'artifacts_manifest_csv': '/home/jovyan/work/Dry-shRub/shrub/Final/artifacts/labeling/manifests/sprint4_artifacts.csv'}, notes=[])}, score_summary={}, notes=[])

In [17]:
controller.set_section_config(
    trial,
    "labeling",
    labeling_pipeline.config_dict(),
)
controller.save_trial(trial)
trial

TrialRecord(trial_id='labeling_only_trial_001', created_at='2026-04-15T02:30:58+00:00', status='section_failed:labeling', section_configs={'labeling': {'sprint3_variant': 'revised', 'use_shape_descriptors': True, 'use_temporal_confidence': True, 'use_boundary_confidence': True, 'use_transform_confidence': False, 'use_object_subspace_filter': False, 'rasterization_mode': 'circle', 'multires': (1.0, 2.0, 5.0, 10.0), 'force_rerun_sprint4': False, 'force_refresh_site_assets': False, 'nonfatal_qa_overlay': True, 'run_sprint3': True, 'sprint3_variants': ('original', 'revised'), 'max_ptx_per_site': 1, 'force_rerun_sprint3': False, 'require_success_artifacts_sprint3': True, 'cleanup_ptx_after_all_variants': True, 'cleanup_stale_ptx_before_run': True, 'stale_ptx_days': 2, 'boundary_confidence_mode': 'universal', 'site_reference_dates': {}, 'subspace_min_component_pixels': 4, 'subspace_min_object_confidence': 0.55, 'subspace_min_transform_confidence': 0.5, 'subspace_min_temporal_confidence': 0.4, 'subspace_max_height_m': 3.5, 'allow_adopt_global_outputs': False}}, section_runs={'labeling': SectionRunRecord(section_name='labeling', config_signature='d67331ee1b6f', status='empty_outputs', started_at=None, finished_at='2026-04-15T10:07:15+00:00', metrics={'n_object_rows': 0, 'n_artifact_rows': 0, 'n_sites': 0, 'stage_cache_manifest_count': 2, 'runtime_wall_seconds': 55.588680546032265, 'runtime_max_rss_mb': 284.285, 'runtime_cache_hits': 0, 'runtime_cache_misses': 0}, qa_outputs={'objects_csv': '/home/jovyan/work/Dry-shRub/shrub/Final/artifacts/labeling/pipeline_runs/d67331ee1b6f/summaries/objects_all.csv', 'artifacts_csv': '/home/jovyan/work/Dry-shRub/shrub/Final/artifacts/labeling/pipeline_runs/d67331ee1b6f/summaries/artifacts_all.csv', 'artifacts_manifest_csv': '/home/jovyan/work/Dry-shRub/shrub/Final/artifacts/labeling/manifests/sprint4_artifacts.csv'}, notes=[])}, score_summary={}, notes=[])

In [20]:
print("Experiment state:")
display(state)

print("Trial:")
display(trial)

print("Completed trials:")
display(grid.completed_trials_frame())

Experiment state:

ExperimentState(experiment_name='shrubwise_main', active_modules=["labeling.sprint3.execution:('original', 'revised')", 'labeling.standardize.base:default', 'labeling.refine.shape_descriptors:enabled', 'labeling.refine.temporal_confidence:enabled', 'labeling.transfer.base:default', 'labeling.rasterize.mode:circle', 'labeling.boundary_confidence:universal', 'labeling.multires_export:default'], notes='', raster_outputs=CanonicalRasterOutputs(labels=Empty DataFrame
Columns: []
Index: [], features=None, predictions=None, qa_overlays=None), object_outputs=CanonicalObjectOutputs(objects=Empty DataFrame
Columns: []
Index: [], predicted_objects=None, source_provenance=None, quality_flags=None), qa_outputs={'labeling': {'objects_csv': '/home/jovyan/work/Dry-shRub/shrub/Final/artifacts/labeling/pipeline_runs/88fb2c6936cb/summaries/objects_all.csv', 'artifacts_csv': '/home/jovyan/work/Dry-shRub/shrub/Final/artifacts/labeling/pipeline_runs/88fb2c6936cb/summaries/artifacts_all.csv', 'artifacts_manifest_csv': '/home/jovyan/work/Dry-shRub/shrub/Final/artifacts/labeling/manifests/sprint4_artifacts.csv', 'runtime_report': {'detected_image_key': 'intelimon-shrubs', 'detected_image_alias': 'pramonettivega/intelimon-shrubs', 'detected_conda_env': None, 'capabilities': ['runtime:intelimon_sprint3', 'runtime:rasterio', 'runtime:rscript'], 'available_executables': ['Rscript'], 'available_python_modules': ['numpy', 'pandas', 'rasterio', 'scipy'], 'marker_files_found': [], 'marker_env_matches': {'JUPYTER_IMAGE_SPEC': 'pramonettivega/intelimon-shrubs'}, 'notes': []}, 'executed_stages': ['sprint3'], 'skipped_stages': {'standardize': "labeling.standardize.base: missing=['runtime:python']", 'refine': "labeling.refine.shape_descriptors: missing=['runtime:python']; labeling.refine.temporal_confidence: missing=['runtime:python']; labeling.refine.object_subspace_filter: missing=['runtime:python']", 'transfer': "labeling.transfer.base: missing=['runtime:labeling_transfer']", 'rasterize': "labeling.rasterize.mode: missing=['runtime:labeling_transfer']; labeling.boundary_confidence: missing=['runtime:labeling_transfer']; labeling.mask_subspace_reduction: missing=['runtime:labeling_transfer']; labeling.multires_export: missing=['runtime:labeling_transfer']"}}}, section_status={'labeling': 'partial_or_empty_outputs'})

Trial:

TrialRecord(trial_id='labeling_only_trial_001', created_at='2026-04-15T02:30:58+00:00', status='section_failed:labeling', section_configs={'labeling': {'sprint3_variant': 'revised', 'use_shape_descriptors': True, 'use_temporal_confidence': True, 'use_boundary_confidence': True, 'use_transform_confidence': False, 'use_object_subspace_filter': False, 'rasterization_mode': 'circle', 'multires': (1.0, 2.0, 5.0, 10.0), 'force_rerun_sprint4': False, 'force_refresh_site_assets': False, 'nonfatal_qa_overlay': True, 'run_sprint3': True, 'sprint3_variants': ('original', 'revised'), 'max_ptx_per_site': 1, 'force_rerun_sprint3': False, 'require_success_artifacts_sprint3': True, 'cleanup_ptx_after_all_variants': True, 'cleanup_stale_ptx_before_run': True, 'stale_ptx_days': 2, 'boundary_confidence_mode': 'universal', 'site_reference_dates': {}, 'subspace_min_component_pixels': 4, 'subspace_min_object_confidence': 0.55, 'subspace_min_transform_confidence': 0.5, 'subspace_min_temporal_confidence': 0.4, 'subspace_max_height_m': 3.5, 'allow_adopt_global_outputs': False}}, section_runs={'labeling': SectionRunRecord(section_name='labeling', config_signature='88fb2c6936cb', status='partial_or_empty_outputs', started_at=None, finished_at='2026-04-15T21:05:25+00:00', metrics={'n_object_rows': 0, 'n_artifact_rows': 0, 'n_sites': 0, 'stage_cache_manifest_count': 2, 'n_executed_stages': 1, 'n_skipped_stages': 4, 'runtime_wall_seconds': 57.95617453800514, 'runtime_max_rss_mb': 267.797, 'runtime_cache_hits': 0, 'runtime_cache_misses': 0}, qa_outputs={'objects_csv': '/home/jovyan/work/Dry-shRub/shrub/Final/artifacts/labeling/pipeline_runs/88fb2c6936cb/summaries/objects_all.csv', 'artifacts_csv': '/home/jovyan/work/Dry-shRub/shrub/Final/artifacts/labeling/pipeline_runs/88fb2c6936cb/summaries/artifacts_all.csv', 'artifacts_manifest_csv': '/home/jovyan/work/Dry-shRub/shrub/Final/artifacts/labeling/manifests/sprint4_artifacts.csv', 'runtime_report': {'detected_image_key': 'intelimon-shrubs', 'detected_image_alias': 'pramonettivega/intelimon-shrubs', 'detected_conda_env': None, 'capabilities': ['runtime:intelimon_sprint3', 'runtime:rasterio', 'runtime:rscript'], 'available_executables': ['Rscript'], 'available_python_modules': ['numpy', 'pandas', 'rasterio', 'scipy'], 'marker_files_found': [], 'marker_env_matches': {'JUPYTER_IMAGE_SPEC': 'pramonettivega/intelimon-shrubs'}, 'notes': []}, 'executed_stages': ['sprint3'], 'skipped_stages': {'standardize': "labeling.standardize.base: missing=['runtime:python']", 'refine': "labeling.refine.shape_descriptors: missing=['runtime:python']; labeling.refine.temporal_confidence: missing=['runtime:python']; labeling.refine.object_subspace_filter: missing=['runtime:python']", 'transfer': "labeling.transfer.base: missing=['runtime:labeling_transfer']", 'rasterize': "labeling.rasterize.mode: missing=['runtime:labeling_transfer']; labeling.boundary_confidence: missing=['runtime:labeling_transfer']; labeling.mask_subspace_reduction: missing=['runtime:labeling_transfer']; labeling.multires_export: missing=['runtime:labeling_transfer']"}}, notes=['runtime_image=intelimon-shrubs', 'runtime_capabilities=runtime:intelimon_sprint3,runtime:rasterio,runtime:rscript'])}, score_summary={}, notes=[])

Completed trials:

                  trial_id                   status  n_section_runs
0  labeling_only_trial_001  section_failed:labeling               1

In [19]:
labeling_result, state, runtime_stats = execute_pipeline_section(
    labeling_pipeline,
    state=state,
    artifact_store=artifact_store,
    push_remote=USE_DRIVE,
)

controller.record_section_result(
    trial,
    section_name="labeling",
    config_signature=labeling_pipeline.config_signature(),
    result=labeling_result,
)
controller.save_trial(trial)
controller.save_state(state)

labeling_result, runtime_stats

[artifact_store] Refreshing expired Google Drive credentials.
2026-04-15 21:04:31 | INFO     | shrub.labeling.sprint3_runner | Discovering remote PTX files for site=calaveras-big-trees at https://wifire-data.sdsc.edu/nc/public.php/dav/files/ucca-calaveras-big-trees/original_TLS
2026-04-15 21:04:32 | INFO     | shrub.labeling.sprint3_runner | Discovering remote PTX files for site=dl-bliss at https://wifire-data.sdsc.edu/nc/public.php/dav/files/ucca-dl-bliss/original_TLS
2026-04-15 21:04:32 | INFO     | shrub.labeling.sprint3_runner | Discovering remote PTX files for site=independence-lake at https://wifire-data.sdsc.edu/nc/public.php/dav/files/ucca-independence-lake/original_TLS
2026-04-15 21:04:32 | INFO     | shrub.labeling.sprint3_runner | Discovering remote PTX files for site=pacific-union-college at https://wifire-data.sdsc.edu/nc/public.php/dav/files/ucca-pacific-union-college/original_TLS
2026-04-15 21:04:33 | INFO     | shrub.labeling.sprint3_runner | Discovering remote PTX files for site=sedgwick at https://wifire-data.sdsc.edu/nc/public.php/dav/files/ucca-sedgwick/original_TLS
2026-04-15 21:04:33 | INFO     | shrub.labeling.sprint3_runner | Discovering remote PTX files for site=shaver-lake at https://wifire-data.sdsc.edu/nc/public.php/dav/files/ucca-shaver-lake/original_TLS
2026-04-15 21:04:33 | INFO     | shrub.labeling.pipeline | Sprint 3 PTX discovery selected 6 PTX row(s) across 6 site(s)
2026-04-15 21:04:33 | INFO     | shrub.labeling.sprint3_runner | Downloading PTX for site=calaveras-big-trees from https://wifire-data.sdsc.edu/nc/public.php/dav/files/ucca-calaveras-big-trees/original_TLS/CATCU_0009_20250615_1.ptx
2026-04-15 21:04:36 | INFO     | shrub.labeling.sprint3_runner | Downloaded PTX to /home/jovyan/work/Dry-shRub/shrub/Final/artifacts/labeling/ptx_cache/calaveras-big-trees/CATCU_0009_20250615_1.ptx
2026-04-15 21:04:37 | INFO     | shrub.labeling.pipeline | Starting Sprint 3 | site=calaveras-big-trees | variant=original | ptx=CATCU_0009_20250615_1.ptx
2026-04-15 21:04:38 | INFO     | shrub.labeling.sprint3_runner | Using cached Sprint 3 outputs for site=calaveras-big-trees variant=original ptx=CATCU_0009_20250615_1.ptx
2026-04-15 21:04:38 | INFO     | shrub.labeling.pipeline | Completed Sprint 3 | site=calaveras-big-trees | variant=original | ptx=CATCU_0009_20250615_1.ptx | cache=True
2026-04-15 21:04:38 | INFO     | shrub.labeling.pipeline | Starting Sprint 3 | site=calaveras-big-trees | variant=revised | ptx=CATCU_0009_20250615_1.ptx
2026-04-15 21:04:39 | INFO     | shrub.labeling.sprint3_runner | Using cached Sprint 3 outputs for site=calaveras-big-trees variant=revised ptx=CATCU_0009_20250615_1.ptx
2026-04-15 21:04:40 | INFO     | shrub.labeling.pipeline | Completed Sprint 3 | site=calaveras-big-trees | variant=revised | ptx=CATCU_0009_20250615_1.ptx | cache=True
2026-04-15 21:04:40 | INFO     | shrub.labeling.sprint3_runner | Deleted PTX after processing: /home/jovyan/work/Dry-shRub/shrub/Final/artifacts/labeling/ptx_cache/calaveras-big-trees/CATCU_0009_20250615_1.ptx (529864075 bytes)
2026-04-15 21:04:40 | INFO     | shrub.labeling.sprint3_runner | Downloading PTX for site=dl-bliss from https://wifire-data.sdsc.edu/nc/public.php/dav/files/ucca-dl-bliss/original_TLS/CAAEU_0027_20250728_1.ptx
2026-04-15 21:04:42 | INFO     | shrub.labeling.sprint3_runner | Downloaded PTX to /home/jovyan/work/Dry-shRub/shrub/Final/artifacts/labeling/ptx_cache/dl-bliss/CAAEU_0027_20250728_1.ptx
2026-04-15 21:04:42 | INFO     | shrub.labeling.pipeline | Starting Sprint 3 | site=dl-bliss | variant=original | ptx=CAAEU_0027_20250728_1.ptx
2026-04-15 21:04:44 | INFO     | shrub.labeling.sprint3_runner | Using cached Sprint 3 outputs for site=dl-bliss variant=original ptx=CAAEU_0027_20250728_1.ptx
2026-04-15 21:04:44 | INFO     | shrub.labeling.pipeline | Completed Sprint 3 | site=dl-bliss | variant=original | ptx=CAAEU_0027_20250728_1.ptx | cache=True
2026-04-15 21:04:44 | INFO     | shrub.labeling.pipeline | Starting Sprint 3 | site=dl-bliss | variant=revised | ptx=CAAEU_0027_20250728_1.ptx
2026-04-15 21:04:45 | INFO     | shrub.labeling.sprint3_runner | Using cached Sprint 3 outputs for site=dl-bliss variant=revised ptx=CAAEU_0027_20250728_1.ptx
2026-04-15 21:04:45 | INFO     | shrub.labeling.pipeline | Completed Sprint 3 | site=dl-bliss | variant=revised | ptx=CAAEU_0027_20250728_1.ptx | cache=True
2026-04-15 21:04:45 | INFO     | shrub.labeling.sprint3_runner | Deleted PTX after processing: /home/jovyan/work/Dry-shRub/shrub/Final/artifacts/labeling/ptx_cache/dl-bliss/CAAEU_0027_20250728_1.ptx (505609992 bytes)
2026-04-15 21:04:45 | INFO     | shrub.labeling.sprint3_runner | Downloading PTX for site=independence-lake from https://wifire-data.sdsc.edu/nc/public.php/dav/files/ucca-independence-lake/original_TLS/CATNF_6118_20250820_1.ptx
2026-04-15 21:04:48 | INFO     | shrub.labeling.sprint3_runner | Downloaded PTX to /home/jovyan/work/Dry-shRub/shrub/Final/artifacts/labeling/ptx_cache/independence-lake/CATNF_6118_20250820_1.ptx
2026-04-15 21:04:48 | INFO     | shrub.labeling.pipeline | Starting Sprint 3 | site=independence-lake | variant=original | ptx=CATNF_6118_20250820_1.ptx
2026-04-15 21:04:49 | INFO     | shrub.labeling.sprint3_runner | Using cached Sprint 3 outputs for site=independence-lake variant=original ptx=CATNF_6118_20250820_1.ptx
2026-04-15 21:04:50 | INFO     | shrub.labeling.pipeline | Completed Sprint 3 | site=independence-lake | variant=original | ptx=CATNF_6118_20250820_1.ptx | cache=True
2026-04-15 21:04:50 | INFO     | shrub.labeling.pipeline | Starting Sprint 3 | site=independence-lake | variant=revised | ptx=CATNF_6118_20250820_1.ptx
2026-04-15 21:04:51 | INFO     | shrub.labeling.sprint3_runner | Using cached Sprint 3 outputs for site=independence-lake variant=revised ptx=CATNF_6118_20250820_1.ptx
2026-04-15 21:04:51 | INFO     | shrub.labeling.pipeline | Completed Sprint 3 | site=independence-lake | variant=revised | ptx=CATNF_6118_20250820_1.ptx | cache=True
2026-04-15 21:04:51 | INFO     | shrub.labeling.sprint3_runner | Deleted PTX after processing: /home/jovyan/work/Dry-shRub/shrub/Final/artifacts/labeling/ptx_cache/independence-lake/CATNF_6118_20250820_1.ptx (451162395 bytes)
2026-04-15 21:04:51 | INFO     | shrub.labeling.sprint3_runner | Downloading PTX for site=pacific-union-college from https://wifire-data.sdsc.edu/nc/public.php/dav/files/ucca-pacific-union-college/original_TLS/CALNU_0039_20250810_1.ptx
2026-04-15 21:04:54 | INFO     | shrub.labeling.sprint3_runner | Downloaded PTX to /home/jovyan/work/Dry-shRub/shrub/Final/artifacts/labeling/ptx_cache/pacific-union-college/CALNU_0039_20250810_1.ptx
2026-04-15 21:04:54 | INFO     | shrub.labeling.pipeline | Starting Sprint 3 | site=pacific-union-college | variant=original | ptx=CALNU_0039_20250810_1.ptx
2026-04-15 21:04:55 | INFO     | shrub.labeling.sprint3_runner | Using cached Sprint 3 outputs for site=pacific-union-college variant=original ptx=CALNU_0039_20250810_1.ptx
2026-04-15 21:04:56 | INFO     | shrub.labeling.pipeline | Completed Sprint 3 | site=pacific-union-college | variant=original | ptx=CALNU_0039_20250810_1.ptx | cache=True
2026-04-15 21:04:56 | INFO     | shrub.labeling.pipeline | Starting Sprint 3 | site=pacific-union-college | variant=revised | ptx=CALNU_0039_20250810_1.ptx
2026-04-15 21:04:57 | INFO     | shrub.labeling.sprint3_runner | Using cached Sprint 3 outputs for site=pacific-union-college variant=revised ptx=CALNU_0039_20250810_1.ptx
2026-04-15 21:04:57 | INFO     | shrub.labeling.pipeline | Completed Sprint 3 | site=pacific-union-college | variant=revised | ptx=CALNU_0039_20250810_1.ptx | cache=True
2026-04-15 21:04:57 | INFO     | shrub.labeling.sprint3_runner | Deleted PTX after processing: /home/jovyan/work/Dry-shRub/shrub/Final/artifacts/labeling/ptx_cache/pacific-union-college/CALNU_0039_20250810_1.ptx (556223905 bytes)
2026-04-15 21:04:57 | INFO     | shrub.labeling.sprint3_runner | Downloading PTX for site=sedgwick from https://wifire-data.sdsc.edu/nc/public.php/dav/files/ucca-sedgwick/original_TLS/CASBC_0087_20250712_1.ptx
2026-04-15 21:05:00 | INFO     | shrub.labeling.sprint3_runner | Downloaded PTX to /home/jovyan/work/Dry-shRub/shrub/Final/artifacts/labeling/ptx_cache/sedgwick/CASBC_0087_20250712_1.ptx
2026-04-15 21:05:00 | INFO     | shrub.labeling.pipeline | Starting Sprint 3 | site=sedgwick | variant=original | ptx=CASBC_0087_20250712_1.ptx
2026-04-15 21:05:01 | INFO     | shrub.labeling.sprint3_runner | Using cached Sprint 3 outputs for site=sedgwick variant=original ptx=CASBC_0087_20250712_1.ptx
2026-04-15 21:05:01 | INFO     | shrub.labeling.pipeline | Completed Sprint 3 | site=sedgwick | variant=original | ptx=CASBC_0087_20250712_1.ptx | cache=True
2026-04-15 21:05:01 | INFO     | shrub.labeling.pipeline | Starting Sprint 3 | site=sedgwick | variant=revised | ptx=CASBC_0087_20250712_1.ptx
2026-04-15 21:05:03 | INFO     | shrub.labeling.sprint3_runner | Using cached Sprint 3 outputs for site=sedgwick variant=revised ptx=CASBC_0087_20250712_1.ptx
2026-04-15 21:05:03 | INFO     | shrub.labeling.pipeline | Completed Sprint 3 | site=sedgwick | variant=revised | ptx=CASBC_0087_20250712_1.ptx | cache=True
2026-04-15 21:05:03 | INFO     | shrub.labeling.sprint3_runner | Deleted PTX after processing: /home/jovyan/work/Dry-shRub/shrub/Final/artifacts/labeling/ptx_cache/sedgwick/CASBC_0087_20250712_1.ptx (565277605 bytes)
2026-04-15 21:05:03 | INFO     | shrub.labeling.sprint3_runner | Downloading PTX for site=shaver-lake from https://wifire-data.sdsc.edu/nc/public.php/dav/files/ucca-shaver-lake/original_TLS/CAFKU_0096_20240804_1.ptx
2026-04-15 21:05:06 | INFO     | shrub.labeling.sprint3_runner | Downloaded PTX to /home/jovyan/work/Dry-shRub/shrub/Final/artifacts/labeling/ptx_cache/shaver-lake/CAFKU_0096_20240804_1.ptx
2026-04-15 21:05:06 | INFO     | shrub.labeling.pipeline | Starting Sprint 3 | site=shaver-lake | variant=original | ptx=CAFKU_0096_20240804_1.ptx
2026-04-15 21:05:07 | INFO     | shrub.labeling.sprint3_runner | Using cached Sprint 3 outputs for site=shaver-lake variant=original ptx=CAFKU_0096_20240804_1.ptx
2026-04-15 21:05:08 | INFO     | shrub.labeling.pipeline | Completed Sprint 3 | site=shaver-lake | variant=original | ptx=CAFKU_0096_20240804_1.ptx | cache=True
2026-04-15 21:05:08 | INFO     | shrub.labeling.pipeline | Starting Sprint 3 | site=shaver-lake | variant=revised | ptx=CAFKU_0096_20240804_1.ptx
2026-04-15 21:05:09 | INFO     | shrub.labeling.sprint3_runner | Using cached Sprint 3 outputs for site=shaver-lake variant=revised ptx=CAFKU_0096_20240804_1.ptx
2026-04-15 21:05:09 | INFO     | shrub.labeling.pipeline | Completed Sprint 3 | site=shaver-lake | variant=revised | ptx=CAFKU_0096_20240804_1.ptx | cache=True
2026-04-15 21:05:09 | INFO     | shrub.labeling.sprint3_runner | Deleted PTX after processing: /home/jovyan/work/Dry-shRub/shrub/Final/artifacts/labeling/ptx_cache/shaver-lake/CAFKU_0096_20240804_1.ptx (475304103 bytes)
2026-04-15 21:05:09 | INFO     | shrub.labeling.pipeline | Sprint 3 stage complete | manifest_rows=12 | manifest_csv=/home/jovyan/work/Dry-shRub/shrub/Final/artifacts/labeling/manifests/sprint3_runs.csv
2026-04-15 21:05:09 | INFO     | shrub.labeling.pipeline | Skipping stage=standardize | reason=labeling.standardize.base: missing=['runtime:python']
2026-04-15 21:05:09 | INFO     | shrub.labeling.pipeline | Skipping stage=refine | reason=labeling.refine.shape_descriptors: missing=['runtime:python']; labeling.refine.temporal_confidence: missing=['runtime:python']; labeling.refine.object_subspace_filter: missing=['runtime:python']
2026-04-15 21:05:09 | INFO     | shrub.labeling.pipeline | Skipping stage=transfer | reason=labeling.transfer.base: missing=['runtime:labeling_transfer']
2026-04-15 21:05:09 | INFO     | shrub.labeling.pipeline | Skipping stage=rasterize | reason=labeling.rasterize.mode: missing=['runtime:labeling_transfer']; labeling.boundary_confidence: missing=['runtime:labeling_transfer']; labeling.mask_subspace_reduction: missing=['runtime:labeling_transfer']; labeling.multires_export: missing=['runtime:labeling_transfer']
2026-04-15 21:05:09 | INFO     | shrub.labeling.pipeline | PUSH ARTIFACT | key=objects_summary | rel_path=labeling/88fb2c6936cb/summaries/objects_all.csv
[artifact_store] Creating new Drive artifact for labeling/88fb2c6936cb/summaries/objects_all.csv
2026-04-15 21:05:16 | INFO     | shrub.labeling.pipeline | PUSH ARTIFACT | key=artifacts_summary | rel_path=labeling/88fb2c6936cb/summaries/artifacts_all.csv
[artifact_store] Creating new Drive artifact for labeling/88fb2c6936cb/summaries/artifacts_all.csv
2026-04-15 21:05:19 | INFO     | shrub.labeling.pipeline | Saved labeling summaries for signature=88fb2c6936cb to /home/jovyan/work/Dry-shRub/shrub/Final/artifacts/labeling/pipeline_runs/88fb2c6936cb/summaries/objects_all.csv and /home/jovyan/work/Dry-shRub/shrub/Final/artifacts/labeling/pipeline_runs/88fb2c6936cb/summaries/artifacts_all.csv
2026-04-15 21:05:22 | INFO     | shrub.labeling.pipeline | Saved pipeline run result to /home/jovyan/work/Dry-shRub/shrub/Final/artifacts/labeling/pipeline_runs/88fb2c6936cb/labeling_run_result.json
2026-04-15 21:05:22 | INFO     | shrub.labeling.pipeline | PUSH ARTIFACT | key=run_manifest | rel_path=labeling/88fb2c6936cb/run_manifest.json
[artifact_store] Creating new Drive artifact for labeling/88fb2c6936cb/run_manifest.json
2026-04-15 21:05:25 | INFO     | shrub.labeling.pipeline | Saved labeling run manifest to /home/jovyan/work/Dry-shRub/shrub/Final/artifacts/labeling/pipeline_runs/88fb2c6936cb/run_manifest.json

(PipelineRunResult(pipeline_name='labeling', success=False, status='partial_or_empty_outputs', raster_outputs=CanonicalRasterOutputs(labels=Empty DataFrame
 Columns: []
 Index: [], features=None, predictions=None, qa_overlays=None), object_outputs=CanonicalObjectOutputs(objects=Empty DataFrame
 Columns: []
 Index: [], predicted_objects=None, source_provenance=None, quality_flags=None), qa_outputs={'objects_csv': '/home/jovyan/work/Dry-shRub/shrub/Final/artifacts/labeling/pipeline_runs/88fb2c6936cb/summaries/objects_all.csv', 'artifacts_csv': '/home/jovyan/work/Dry-shRub/shrub/Final/artifacts/labeling/pipeline_runs/88fb2c6936cb/summaries/artifacts_all.csv', 'artifacts_manifest_csv': '/home/jovyan/work/Dry-shRub/shrub/Final/artifacts/labeling/manifests/sprint4_artifacts.csv', 'runtime_report': {'detected_image_key': 'intelimon-shrubs', 'detected_image_alias': 'pramonettivega/intelimon-shrubs', 'detected_conda_env': None, 'capabilities': ['runtime:intelimon_sprint3', 'runtime:rasterio', 'runtime:rscript'], 'available_executables': ['Rscript'], 'available_python_modules': ['numpy', 'pandas', 'rasterio', 'scipy'], 'marker_files_found': [], 'marker_env_matches': {'JUPYTER_IMAGE_SPEC': 'pramonettivega/intelimon-shrubs'}, 'notes': []}, 'executed_stages': ['sprint3'], 'skipped_stages': {'standardize': "labeling.standardize.base: missing=['runtime:python']", 'refine': "labeling.refine.shape_descriptors: missing=['runtime:python']; labeling.refine.temporal_confidence: missing=['runtime:python']; labeling.refine.object_subspace_filter: missing=['runtime:python']", 'transfer': "labeling.transfer.base: missing=['runtime:labeling_transfer']", 'rasterize': "labeling.rasterize.mode: missing=['runtime:labeling_transfer']; labeling.boundary_confidence: missing=['runtime:labeling_transfer']; labeling.mask_subspace_reduction: missing=['runtime:labeling_transfer']; labeling.multires_export: missing=['runtime:labeling_transfer']"}}, metrics={'n_object_rows': 0, 'n_artifact_rows': 0, 'n_sites': 0, 'stage_cache_manifest_count': 2, 'n_executed_stages': 1, 'n_skipped_stages': 4, 'runtime_wall_seconds': 57.95617453800514, 'runtime_max_rss_mb': 267.797, 'runtime_cache_hits': 0, 'runtime_cache_misses': 0}, notes=['runtime_image=intelimon-shrubs', 'runtime_capabilities=runtime:intelimon_sprint3,runtime:rasterio,runtime:rscript']),
 RuntimeStats(started_at='2026-04-15T21:04:27+00:00', finished_at='2026-04-15T21:05:25+00:00', wall_seconds=57.95617453800514, max_rss_mb=267.797, bytes_written_local=0, bytes_pruned_local=0, cache_hits=0, cache_misses=0, notes=[]))

In [ ]:
# stderr_path = "/home/jovyan/work/Dry-shRub/shrub/Final/artifacts/labeling/calaveras-big-trees/sprint3/original/CATCU_0009_20250615_1/stderr.log"
# stdout_path = "/home/jovyan/work/Dry-shRub/shrub/Final/artifacts/labeling/calaveras-big-trees/sprint3/original/CATCU_0009_20250615_1/stdout.log"

# print("================ FULL STDERR ================")
# if os.path.exists(stderr_path):
#     with open(stderr_path, 'r') as f:
#         print(f.read())
# else:
#     print("stderr.log not found!")

# print("\n================ FULL STDOUT ================")
# if os.path.exists(stdout_path):
#     with open(stdout_path, 'r') as f:
#         print(f.read())
# else:
#     print("stdout.log not found!")

In [21]:
print("Experiment state:")
display(state)

print("Trial:")
display(trial)

print("Completed trials:")
display(grid.completed_trials_frame())

Experiment state:

ExperimentState(experiment_name='shrubwise_main', active_modules=["labeling.sprint3.execution:('original', 'revised')", 'labeling.standardize.base:default', 'labeling.refine.shape_descriptors:enabled', 'labeling.refine.temporal_confidence:enabled', 'labeling.transfer.base:default', 'labeling.rasterize.mode:circle', 'labeling.boundary_confidence:universal', 'labeling.multires_export:default'], notes='', raster_outputs=CanonicalRasterOutputs(labels=Empty DataFrame
Columns: []
Index: [], features=None, predictions=None, qa_overlays=None), object_outputs=CanonicalObjectOutputs(objects=Empty DataFrame
Columns: []
Index: [], predicted_objects=None, source_provenance=None, quality_flags=None), qa_outputs={'labeling': {'objects_csv': '/home/jovyan/work/Dry-shRub/shrub/Final/artifacts/labeling/pipeline_runs/88fb2c6936cb/summaries/objects_all.csv', 'artifacts_csv': '/home/jovyan/work/Dry-shRub/shrub/Final/artifacts/labeling/pipeline_runs/88fb2c6936cb/summaries/artifacts_all.csv', 'artifacts_manifest_csv': '/home/jovyan/work/Dry-shRub/shrub/Final/artifacts/labeling/manifests/sprint4_artifacts.csv', 'runtime_report': {'detected_image_key': 'intelimon-shrubs', 'detected_image_alias': 'pramonettivega/intelimon-shrubs', 'detected_conda_env': None, 'capabilities': ['runtime:intelimon_sprint3', 'runtime:rasterio', 'runtime:rscript'], 'available_executables': ['Rscript'], 'available_python_modules': ['numpy', 'pandas', 'rasterio', 'scipy'], 'marker_files_found': [], 'marker_env_matches': {'JUPYTER_IMAGE_SPEC': 'pramonettivega/intelimon-shrubs'}, 'notes': []}, 'executed_stages': ['sprint3'], 'skipped_stages': {'standardize': "labeling.standardize.base: missing=['runtime:python']", 'refine': "labeling.refine.shape_descriptors: missing=['runtime:python']; labeling.refine.temporal_confidence: missing=['runtime:python']; labeling.refine.object_subspace_filter: missing=['runtime:python']", 'transfer': "labeling.transfer.base: missing=['runtime:labeling_transfer']", 'rasterize': "labeling.rasterize.mode: missing=['runtime:labeling_transfer']; labeling.boundary_confidence: missing=['runtime:labeling_transfer']; labeling.mask_subspace_reduction: missing=['runtime:labeling_transfer']; labeling.multires_export: missing=['runtime:labeling_transfer']"}}}, section_status={'labeling': 'partial_or_empty_outputs'})

Trial:

TrialRecord(trial_id='labeling_only_trial_001', created_at='2026-04-15T02:30:58+00:00', status='section_failed:labeling', section_configs={'labeling': {'sprint3_variant': 'revised', 'use_shape_descriptors': True, 'use_temporal_confidence': True, 'use_boundary_confidence': True, 'use_transform_confidence': False, 'use_object_subspace_filter': False, 'rasterization_mode': 'circle', 'multires': (1.0, 2.0, 5.0, 10.0), 'force_rerun_sprint4': False, 'force_refresh_site_assets': False, 'nonfatal_qa_overlay': True, 'run_sprint3': True, 'sprint3_variants': ('original', 'revised'), 'max_ptx_per_site': 1, 'force_rerun_sprint3': False, 'require_success_artifacts_sprint3': True, 'cleanup_ptx_after_all_variants': True, 'cleanup_stale_ptx_before_run': True, 'stale_ptx_days': 2, 'boundary_confidence_mode': 'universal', 'site_reference_dates': {}, 'subspace_min_component_pixels': 4, 'subspace_min_object_confidence': 0.55, 'subspace_min_transform_confidence': 0.5, 'subspace_min_temporal_confidence': 0.4, 'subspace_max_height_m': 3.5, 'allow_adopt_global_outputs': False}}, section_runs={'labeling': SectionRunRecord(section_name='labeling', config_signature='88fb2c6936cb', status='partial_or_empty_outputs', started_at=None, finished_at='2026-04-15T21:05:25+00:00', metrics={'n_object_rows': 0, 'n_artifact_rows': 0, 'n_sites': 0, 'stage_cache_manifest_count': 2, 'n_executed_stages': 1, 'n_skipped_stages': 4, 'runtime_wall_seconds': 57.95617453800514, 'runtime_max_rss_mb': 267.797, 'runtime_cache_hits': 0, 'runtime_cache_misses': 0}, qa_outputs={'objects_csv': '/home/jovyan/work/Dry-shRub/shrub/Final/artifacts/labeling/pipeline_runs/88fb2c6936cb/summaries/objects_all.csv', 'artifacts_csv': '/home/jovyan/work/Dry-shRub/shrub/Final/artifacts/labeling/pipeline_runs/88fb2c6936cb/summaries/artifacts_all.csv', 'artifacts_manifest_csv': '/home/jovyan/work/Dry-shRub/shrub/Final/artifacts/labeling/manifests/sprint4_artifacts.csv', 'runtime_report': {'detected_image_key': 'intelimon-shrubs', 'detected_image_alias': 'pramonettivega/intelimon-shrubs', 'detected_conda_env': None, 'capabilities': ['runtime:intelimon_sprint3', 'runtime:rasterio', 'runtime:rscript'], 'available_executables': ['Rscript'], 'available_python_modules': ['numpy', 'pandas', 'rasterio', 'scipy'], 'marker_files_found': [], 'marker_env_matches': {'JUPYTER_IMAGE_SPEC': 'pramonettivega/intelimon-shrubs'}, 'notes': []}, 'executed_stages': ['sprint3'], 'skipped_stages': {'standardize': "labeling.standardize.base: missing=['runtime:python']", 'refine': "labeling.refine.shape_descriptors: missing=['runtime:python']; labeling.refine.temporal_confidence: missing=['runtime:python']; labeling.refine.object_subspace_filter: missing=['runtime:python']", 'transfer': "labeling.transfer.base: missing=['runtime:labeling_transfer']", 'rasterize': "labeling.rasterize.mode: missing=['runtime:labeling_transfer']; labeling.boundary_confidence: missing=['runtime:labeling_transfer']; labeling.mask_subspace_reduction: missing=['runtime:labeling_transfer']; labeling.multires_export: missing=['runtime:labeling_transfer']"}}, notes=['runtime_image=intelimon-shrubs', 'runtime_capabilities=runtime:intelimon_sprint3,runtime:rasterio,runtime:rscript'])}, score_summary={}, notes=[])

Completed trials:

                  trial_id                   status  n_section_runs
0  labeling_only_trial_001  section_failed:labeling               1

## Features

In [ ]:
features_cfg = {
    "enabled": False,
    "feature_families": [],
    "notes": "Placeholder only for now.",
}

trial.features_config = features_cfg

save_trial(EXPERIMENT_NAME, trial)

trial.features_config

In [ ]:
trial.features_result = {
    "success": None,
    "status": "placeholder_not_run",
    "metrics": {},
    "qa_outputs": {"placeholder": True},
    "notes": ["Features pipeline not implemented yet."],
}

state.section_status["features"] = "placeholder_not_run"
state.qa_outputs["features"] = trial.features_result["qa_outputs"]

save_trial(EXPERIMENT_NAME, trial)
trial.features_result

# Modeling

In [ ]:
modeling_cfg = {
    "enabled": False,
    "model_family": None,
    "notes": "Placeholder only for now.",
}

trial.modeling_config = modeling_cfg

save_trial(EXPERIMENT_NAME, trial)

trial.modeling_config

In [ ]:
trial.modeling_result = {
    "success": None,
    "status": "placeholder_not_run",
    "metrics": {},
    "qa_outputs": {"placeholder": True},
    "notes": ["Modeling pipeline not implemented yet."],
}

state.section_status["modeling"] = "placeholder_not_run"
state.qa_outputs["modeling"] = trial.modeling_result["qa_outputs"]

save_trial(EXPERIMENT_NAME, trial)
trial.modeling_result

# Post-processing

In [ ]:
postprocessing_cfg = {
    "enabled": False,
    "steps": [],
    "notes": "Placeholder only for now.",
}

trial.postprocessing_config = postprocessing_cfg

save_trial(EXPERIMENT_NAME, trial)

trial.postprocessing_config

In [ ]:
trial.postprocessing_result = {
    "success": None,
    "status": "placeholder_not_run",
    "metrics": {},
    "qa_outputs": {"placeholder": True},
    "notes": ["Postprocessing pipeline not implemented yet."],
}

state.section_status["postprocessing"] = "placeholder_not_run"
state.qa_outputs["postprocessing"] = trial.postprocessing_result["qa_outputs"]

save_trial(EXPERIMENT_NAME, trial)
trial.postprocessing_result

# Finalize Trial

In [ ]:
trial.qa_summary = {
    "integrity": {
        "labeling": trial.labeling_result.get("status"),
        "features": trial.features_result.get("status"),
        "modeling": trial.modeling_result.get("status"),
        "postprocessing": trial.postprocessing_result.get("status"),
    },
    "section_level": {
        "labeling": "placeholder",
        "features": "placeholder",
        "modeling": "placeholder",
        "postprocessing": "placeholder",
    },
    "cross_section": {
        "label_to_model_feedback": "placeholder",
        "feature_to_model_feedback": "placeholder",
        "end_to_end_feedback": "placeholder",
    },
}

save_trial(EXPERIMENT_NAME, trial)
trial.qa_summary

In [ ]:
labeling_object_rows = trial.labeling_result.get("metrics", {}).get("n_object_rows", 0)
labeling_artifact_rows = trial.labeling_result.get("metrics", {}).get("n_artifact_rows", 0)

trial.score_summary = {
    "labeling_score_placeholder": float(labeling_object_rows > 0) + float(labeling_artifact_rows > 0),
    "features_score_placeholder": None,
    "modeling_score_placeholder": None,
    "postprocessing_score_placeholder": None,
    "composite_score_placeholder": float(labeling_object_rows > 0) + float(labeling_artifact_rows > 0),
}

save_trial(EXPERIMENT_NAME, trial)
trial.score_summary

In [ ]:
trial.status = "partial" if (
    trial.features_result.get("status") == "placeholder_not_run"
    or trial.modeling_result.get("status") == "placeholder_not_run"
    or trial.postprocessing_result.get("status") == "placeholder_not_run"
) else "completed"

save_trial(EXPERIMENT_NAME, trial)

trial

In [ ]:
trial_record_min = {
    "trial_id": trial.trial_id,
    "created_at": trial.created_at,
    "status": trial.status,
    "labeling_config": trial.labeling_config,
    "features_config": trial.features_config,
    "modeling_config": trial.modeling_config,
    "postprocessing_config": trial.postprocessing_config,
    "score_summary": trial.score_summary,
}

registry.trials = [t for t in registry.trials if t["trial_id"] != trial.trial_id]
registry.trials.append(trial_record_min)

score = trial.score_summary.get("composite_score_placeholder")
if score is not None:
    if registry.best_score is None or score > registry.best_score:
        registry.best_score = score
        registry.best_trial_id = trial.trial_id

save_registry(registry)

registry

In [ ]:
trials_df = pd.DataFrame(registry.trials)

if not trials_df.empty:
    if "score_summary" in trials_df.columns:
        trials_df["composite_score_placeholder"] = trials_df["score_summary"].apply(
            lambda x: x.get("composite_score_placeholder") if isinstance(x, dict) else None
        )

    display(
        trials_df[
            ["trial_id", "created_at", "status", "composite_score_placeholder"]
        ].sort_values("trial_id")
    )

    print("Best trial:", registry.best_trial_id)
    print("Best score:", registry.best_score)
else:
    print("No trials recorded yet.")

In [ ]:
INSPECT_TRIAL_ID = trial.trial_id  # change manually

inspect_trial = load_trial(EXPERIMENT_NAME, INSPECT_TRIAL_ID)
inspect_trial