# Setup

In [2]:
#!pip install -r requirements.txt

In [13]:
import sys
from pathlib import Path

repo_root = Path.cwd()
while not ((repo_root / "Final").exists() and (repo_root / "Sprint 3").exists()):
    if repo_root.parent == repo_root:
        raise RuntimeError("Could not locate repo root.")
    repo_root = repo_root.parent

if str(repo_root) not in sys.path:
    sys.path.insert(0, str(repo_root))

from dataclasses import asdict, dataclass, field
from pathlib import Path
import json
from datetime import datetime
from typing import Any
import pandas as pd

from Final.config import default_config
from Final.paths import FINAL_ROOT
from Final.shared_utils import setup_logging, get_logger

from Final.models import (
    ExperimentState,
)
from Final.experiment_controller import ExperimentController
from Final.grid_search import GridSearchController
from Final.pipeline_runtime import execute_pipeline_section
from Final.artifact_store import (
    LocalArtifactStore,
    DriveRegistryArtifactStore,
    HybridArtifactStore,
)
from Final.gating import (
    evaluate_module_card,
    decide_module_status,
    module_cards_to_frame,
)
from Final.labeling.pipeline import LabelingPipeline, LabelingPipelineConfig

In [14]:
cfg = default_config()

logger = setup_logging(
    name="shrub",
    log_dir=cfg.output.logs_root,
    log_filename="main_pipeline.log",
    force=True,
)

logger.info("Initialized main pipeline notebook.")
logger.info("FINAL_ROOT = %s", FINAL_ROOT)

MAIN_OUTPUT_ROOT = cfg.output.root / "main"
MAIN_OUTPUT_ROOT.mkdir(parents=True, exist_ok=True)

MAIN_ROOT = MAIN_OUTPUT_ROOT

MAIN_MANIFEST_DIR = MAIN_OUTPUT_ROOT / "manifests"
MAIN_MANIFEST_DIR.mkdir(parents=True, exist_ok=True)

EXPERIMENTS_ROOT = MAIN_ROOT / "experiments"
EXPERIMENTS_ROOT.mkdir(parents=True, exist_ok=True)

2026-04-15 02:30:56 | INFO     | shrub | Initialized main pipeline notebook.
2026-04-15 02:30:56 | INFO     | shrub | FINAL_ROOT = /home/jovyan/work/Dry-shRub/shrub/Final

In [15]:
controller = ExperimentController(
    experiment_root=cfg.output.root / "experiments",
    experiment_name="shrubwise_main",
)

state = controller.load_state()

pipelines = {}

local_store = LocalArtifactStore(
    repo_root=cfg.data.project_root,
    storage_root=cfg.output.root / "artifact_store_local",
)

USE_DRIVE = False

if USE_DRIVE:
    drive_store = DriveRegistryArtifactStore(
        repo_root=cfg.data.project_root,
        registry_path=cfg.output.root / "artifact_registry.yaml",
        drive_config_path=cfg.data.project_root / "drive_config.yaml",
        client_secrets_path=cfg.data.project_root / "client_secrets.json",
        credentials_path=cfg.data.project_root / "pydrive_credentials.json",
    )
    artifact_store = HybridArtifactStore(
        local_store=local_store,
        remote_store=drive_store,
    )
else:
    artifact_store = local_store

grid = GridSearchController(controller=controller)

## Labeling

In [16]:
labeling_cfg = LabelingPipelineConfig(
    sprint3_variant="revised",
    sprint3_variants=("original", "revised"),
    run_sprint3=True,
    max_ptx_per_site=1,
    force_rerun_sprint3=False,
    require_success_artifacts_sprint3=True,
    cleanup_ptx_after_all_variants=True,
    cleanup_stale_ptx_before_run=True,
    stale_ptx_days=2,
    use_shape_descriptors=True,
    use_temporal_confidence=True,
    use_boundary_confidence=True,
    boundary_confidence_mode="universal",
    use_transform_confidence=False,
    use_object_subspace_filter=False,
    rasterization_mode="circle",
    multires=cfg.raster.create_multires,
    site_reference_dates={},
    subspace_min_component_pixels=4,
    subspace_min_object_confidence=0.55,
    subspace_min_transform_confidence=0.50,
    subspace_min_temporal_confidence=0.40,
    subspace_max_height_m=3.5,
    force_rerun_sprint4=False,
    force_refresh_site_assets=False,
    nonfatal_qa_overlay=True,
    allow_adopt_global_outputs=False,
)

In [17]:
labeling_pipeline = LabelingPipeline(
    cfg,
    pipeline_config=labeling_cfg,
)

pipelines["labeling"] = labeling_pipeline

In [18]:
display(labeling_pipeline.pipeline_spec)
display(grid.pipeline_module_state_frame(labeling_pipeline))

PipelineSpec(pipeline_name='labeling', domain=<PipelineDomain.LABELING: 'label_engineering'>, stages=[StageSpec(name='sprint3', module_keys=['labeling.sprint3.execution'], cache_policy=CachePolicy(require_manifest=False, allow_legacy_reuse=False, retention_mode=<CacheRetentionMode.LEAN: 'lean'>, artifact_keys_to_prune=(), prune_after_success=False)), StageSpec(name='standardize', module_keys=['labeling.standardize.base'], cache_policy=CachePolicy(require_manifest=True, allow_legacy_reuse=False, retention_mode=<CacheRetentionMode.LEAN: 'lean'>, artifact_keys_to_prune=(), prune_after_success=False)), StageSpec(name='refine', module_keys=['labeling.refine.shape_descriptors', 'labeling.refine.temporal_confidence', 'labeling.refine.object_subspace_filter'], cache_policy=CachePolicy(require_manifest=True, allow_legacy_reuse=False, retention_mode=<CacheRetentionMode.LEAN: 'lean'>, artifact_keys_to_prune=(), prune_after_success=False)), StageSpec(name='transfer', module_keys=['labeling.transfer.base'], cache_policy=CachePolicy(require_manifest=True, allow_legacy_reuse=False, retention_mode=<CacheRetentionMode.LEAN: 'lean'>, artifact_keys_to_prune=(), prune_after_success=False)), StageSpec(name='rasterize', module_keys=['labeling.rasterize.mode', 'labeling.boundary_confidence', 'labeling.mask_subspace_reduction', 'labeling.multires_export'], cache_policy=CachePolicy(require_manifest=True, allow_legacy_reuse=False, retention_mode=<CacheRetentionMode.LEAN: 'lean'>, artifact_keys_to_prune=(), prune_after_success=False))], modules={'labeling.sprint3.execution': ModuleSpec(key='labeling.sprint3.execution', stage_name='sprint3', enabled_key=None, variant_key='sprint3_variants', param_keys=('max_ptx_per_site', 'force_rerun_sprint3', 'require_success_artifacts_sprint3'), include_in_state=True), 'labeling.standardize.base': ModuleSpec(key='labeling.standardize.base', stage_name='standardize', enabled_key=None, variant_key=None, param_keys=(), include_in_state=True), 'labeling.refine.shape_descriptors': ModuleSpec(key='labeling.refine.shape_descriptors', stage_name='refine', enabled_key='use_shape_descriptors', variant_key=None, param_keys=(), include_in_state=True), 'labeling.refine.temporal_confidence': ModuleSpec(key='labeling.refine.temporal_confidence', stage_name='refine', enabled_key='use_temporal_confidence', variant_key=None, param_keys=('site_reference_dates',), include_in_state=True), 'labeling.refine.object_subspace_filter': ModuleSpec(key='labeling.refine.object_subspace_filter', stage_name='refine', enabled_key='use_object_subspace_filter', variant_key=None, param_keys=('subspace_min_object_confidence', 'subspace_min_transform_confidence', 'subspace_min_temporal_confidence', 'subspace_max_height_m'), include_in_state=True), 'labeling.transfer.base': ModuleSpec(key='labeling.transfer.base', stage_name='transfer', enabled_key=None, variant_key=None, param_keys=(), include_in_state=True), 'labeling.rasterize.mode': ModuleSpec(key='labeling.rasterize.mode', stage_name='rasterize', enabled_key=None, variant_key='rasterization_mode', param_keys=(), include_in_state=True), 'labeling.boundary_confidence': ModuleSpec(key='labeling.boundary_confidence', stage_name='rasterize', enabled_key='use_boundary_confidence', variant_key='boundary_confidence_mode', param_keys=(), include_in_state=True), 'labeling.mask_subspace_reduction': ModuleSpec(key='labeling.mask_subspace_reduction', stage_name='rasterize', enabled_key='use_object_subspace_filter', variant_key=None, param_keys=('subspace_min_component_pixels',), include_in_state=True), 'labeling.multires_export': ModuleSpec(key='labeling.multires_export', stage_name='rasterize', enabled_key=None, variant_key=None, param_keys=('multires',), include_in_state=True)}, search_axes=[SearchAxis(key='sprint3_variants', values=[('revised',), ('original', 'revised')], stage_name='sprint3', module_key='labeling.sprint3.execution'), SearchAxis(key='use_temporal_confidence', values=[False, True], stage_name='refine', module_key='labeling.refine.temporal_confidence'), SearchAxis(key='boundary_confidence_mode', values=['radial', 'universal'], stage_name='rasterize', module_key='labeling.boundary_confidence'), SearchAxis(key='use_object_subspace_filter', values=[False, True], stage_name='refine', module_key='labeling.refine.object_subspace_filter'), SearchAxis(key='max_ptx_per_site', values=[1], stage_name='sprint3', module_key='labeling.sprint3.execution')])

,pipeline,stage_name,module_name,enabled,variant_name,params
0,labeling,sprint3,labeling.sprint3.execution,True,"('original', 'revised')","{'max_ptx_per_site': 1, 'force_rerun_sprint3':..."
1,labeling,standardize,labeling.standardize.base,True,default,{}
2,labeling,refine,labeling.refine.shape_descriptors,True,enabled,{}
3,labeling,refine,labeling.refine.temporal_confidence,True,enabled,{'site_reference_dates': {}}
4,labeling,refine,labeling.refine.object_subspace_filter,False,disabled,"{'subspace_min_object_confidence': 0.55, 'subs..."
5,labeling,transfer,labeling.transfer.base,True,default,{}
6,labeling,rasterize,labeling.rasterize.mode,True,circle,{}
7,labeling,rasterize,labeling.boundary_confidence,True,universal,{}
8,labeling,rasterize,labeling.mask_subspace_reduction,False,disabled,{'subspace_min_component_pixels': 4}
9,labeling,rasterize,labeling.multires_export,True,default,"{'multires': (1.0, 2.0, 5.0, 10.0)}"

In [19]:
labeling_space_df = grid.section_space_frame(labeling_pipeline).copy()
display(labeling_space_df)
print("Total labeling variants:", len(labeling_space_df))

,config_signature,sprint3_variants,use_temporal_confidence,boundary_confidence_mode,use_object_subspace_filter,max_ptx_per_site
0,074f2c2dc3a8,"original,revised",True,universal,True,1
1,0b9cdfd5f781,"original,revised",True,radial,False,1
2,16774e5c5bc7,"original,revised",True,radial,True,1
3,248d471f5527,revised,True,radial,False,1
4,38814738feeb,revised,True,universal,True,1
5,5725ea41a55c,"original,revised",False,radial,False,1
6,6930be0cde08,"original,revised",False,universal,True,1
7,88fb2c6936cb,"original,revised",True,universal,False,1
8,893d374e5995,"original,revised",False,universal,False,1
9,8d0d163a7065,revised,False,radial,True,1
10,a70cedd9d966,revised,True,radial,True,1
11,c3d868cf458c,revised,False,universal,False,1
12,c6a1b032292a,revised,False,universal,True,1
13,d26a3343dc97,"original,revised",False,radial,True,1
14,e104475dd343,revised,True,universal,False,1
15,fd1d94f36a28,revised,False,radial,False,1

Total labeling variants: 16

In [20]:
TRIAL_ID = "labeling_only_trial_001"

trial_path = controller.trial_path(TRIAL_ID)
if trial_path.exists():
    trial = controller.load_trial(TRIAL_ID)
else:
    trial = controller.create_trial(trial_id=TRIAL_ID)

trial

TrialRecord(trial_id='labeling_only_trial_001', created_at='2026-04-15T02:30:58+00:00', status='created', section_configs={}, section_runs={}, score_summary={}, notes=[])

In [21]:
controller.set_section_config(
    trial,
    "labeling",
    labeling_pipeline.config_dict(),
)
controller.save_trial(trial)
trial

TrialRecord(trial_id='labeling_only_trial_001', created_at='2026-04-15T02:30:58+00:00', status='created', section_configs={'labeling': {'sprint3_variant': 'revised', 'use_shape_descriptors': True, 'use_temporal_confidence': True, 'use_boundary_confidence': True, 'use_transform_confidence': False, 'use_object_subspace_filter': False, 'rasterization_mode': 'circle', 'multires': (1.0, 2.0, 5.0, 10.0), 'force_rerun_sprint4': False, 'force_refresh_site_assets': False, 'nonfatal_qa_overlay': True, 'run_sprint3': True, 'sprint3_variants': ('original', 'revised'), 'max_ptx_per_site': 1, 'force_rerun_sprint3': False, 'require_success_artifacts_sprint3': True, 'cleanup_ptx_after_all_variants': True, 'cleanup_stale_ptx_before_run': True, 'stale_ptx_days': 2, 'boundary_confidence_mode': 'universal', 'site_reference_dates': {}, 'subspace_min_component_pixels': 4, 'subspace_min_object_confidence': 0.55, 'subspace_min_transform_confidence': 0.5, 'subspace_min_temporal_confidence': 0.4, 'subspace_max_height_m': 3.5, 'allow_adopt_global_outputs': False}}, section_runs={}, score_summary={}, notes=[])

In [22]:
print("Experiment state:")
display(state)

print("Trial:")
display(trial)

print("Completed trials:")
display(grid.completed_trials_frame())

Experiment state:

ExperimentState(experiment_name='shrubwise_main', active_modules=[], notes='', raster_outputs=CanonicalRasterOutputs(labels=None, features=None, predictions=None, qa_overlays=None), object_outputs=CanonicalObjectOutputs(objects=None, predicted_objects=None, source_provenance=None, quality_flags=None), qa_outputs={}, section_status={})

Trial:

TrialRecord(trial_id='labeling_only_trial_001', created_at='2026-04-15T02:30:58+00:00', status='created', section_configs={'labeling': {'sprint3_variant': 'revised', 'use_shape_descriptors': True, 'use_temporal_confidence': True, 'use_boundary_confidence': True, 'use_transform_confidence': False, 'use_object_subspace_filter': False, 'rasterization_mode': 'circle', 'multires': (1.0, 2.0, 5.0, 10.0), 'force_rerun_sprint4': False, 'force_refresh_site_assets': False, 'nonfatal_qa_overlay': True, 'run_sprint3': True, 'sprint3_variants': ('original', 'revised'), 'max_ptx_per_site': 1, 'force_rerun_sprint3': False, 'require_success_artifacts_sprint3': True, 'cleanup_ptx_after_all_variants': True, 'cleanup_stale_ptx_before_run': True, 'stale_ptx_days': 2, 'boundary_confidence_mode': 'universal', 'site_reference_dates': {}, 'subspace_min_component_pixels': 4, 'subspace_min_object_confidence': 0.55, 'subspace_min_transform_confidence': 0.5, 'subspace_min_temporal_confidence': 0.4, 'subspace_max_height_m': 3.5, 'allow_adopt_global_outputs': False}}, section_runs={}, score_summary={}, notes=[])

Completed trials:

                  trial_id   status  n_section_runs
0  labeling_only_trial_001  created               0

In [33]:
import os

# The exact paths the pipeline is using
scripts_to_patch = [
    "/home/jovyan/work/Dry-shRub/shrub/Final/labeling/IntELiMon_1_1_1.R",
    "/home/jovyan/work/Dry-shRub/shrub/Final/labeling/IntELiMon_1_1_1_revised.R"
]

for script_path in scripts_to_patch:
    if os.path.exists(script_path):
        with open(script_path, 'r') as file:
            script_content = file.read()
        
        # Replace the strict dplyr bind with base R cbind
        patched_content = script_content.replace("bind_cols", "cbind")
        
        with open(script_path, 'w') as file:
            file.write(patched_content)
            
        print(f"Successfully patched: {script_path}")
    else:
        print(f"Could not find: {script_path}")

ERROR! Session/line number was not unique in database. History logging moved to new session 15
Successfully patched: /home/jovyan/work/Dry-shRub/shrub/Final/labeling/IntELiMon_1_1_1.R
Successfully patched: /home/jovyan/work/Dry-shRub/shrub/Final/labeling/IntELiMon_1_1_1_revised.R

In [35]:
import os

scripts_to_trace = [
    "/home/jovyan/work/Dry-shRub/shrub/Sprint 3/Base/IntELiMon_1_1_1.R",
    "/home/jovyan/work/Dry-shRub/shrub/Sprint 3/Base/IntELiMon_1_1_1_revised.R"
]

# R code to print the exact function calls leading up to a crash
traceback_code = 'options(error = function() { cat("\\n--- TRACEBACK ---\\n"); print(sys.calls()); q("no", status=1) })\n'

for script_path in scripts_to_trace:
    if os.path.exists(script_path):
        with open(script_path, 'r') as file:
            content = file.read()
        
        # Inject the traceback handler at the very top
        if "--- TRACEBACK ---" not in content:
            with open(script_path, 'w') as file:
                file.write(traceback_code + content)
            print(f"Added traceback handler to: {script_path}")
        else:
            print(f"Traceback handler already in: {script_path}")
    else:
        print(f"Could not find: {script_path}")

Added traceback handler to: /home/jovyan/work/Dry-shRub/shrub/Sprint 3/Base/IntELiMon_1_1_1.R
Added traceback handler to: /home/jovyan/work/Dry-shRub/shrub/Sprint 3/Base/IntELiMon_1_1_1_revised.R

In [37]:
import os

scripts_to_trace = [
    "/home/jovyan/work/Dry-shRub/shrub/Sprint 3/Base/IntELiMon_1_1_1.R",
    "/home/jovyan/work/Dry-shRub/shrub/Sprint 3/Base/IntELiMon_1_1_1_revised.R"
]

traceback_code = """
options(rlang_backtrace_on_error = "full")
options(error = function() {
    sink(stderr())
    cat("\\n================ TRACEBACK START ================\\n")
    print(sys.calls())
    if (requireNamespace("rlang", quietly = TRUE)) {
        cat("\\n--- RLANG TRACE ---\\n")
        print(rlang::trace_back(bottom = NULL))
    }
    cat("\\n=================================================\\n")
    sink()
    q("no", status=1)
})
"""

for script_path in scripts_to_trace:
    if os.path.exists(script_path):
        with open(script_path, 'r') as file:
            content = file.read()
            
        with open(script_path, 'w') as file:
            # We prepend it so the last options(error) defined wins
            file.write(traceback_code + content)
            
        print(f"Added stderr traceback handler to: {script_path}")
    else:
        print(f"Could not find: {script_path}")

Added stderr traceback handler to: /home/jovyan/work/Dry-shRub/shrub/Sprint 3/Base/IntELiMon_1_1_1.R
Added stderr traceback handler to: /home/jovyan/work/Dry-shRub/shrub/Sprint 3/Base/IntELiMon_1_1_1_revised.R

In [55]:
# Updated shim that handles the terra-to-raster conversion for legacy lidR
terra_bridge_shim = """
# --- Berkeley TLS Pipeline: Terra-to-Raster Bridge ---
if (!exists("tlsNormalize2")) {
  tlsNormalize2 <- function(las, dtm, min_res = 0.5, keep_ground = TRUE) {
    message("Using shimmed tlsNormalize2 (with Terra Bridge)...")
    
    # lidR v3 (legacy) only accepts 'RasterLayer' from the 'raster' package.
    # We must convert the modern 'SpatRaster' (terra) back to the old format.
    if (inherits(dtm, "SpatRaster")) {
      dtm <- raster::raster(dtm)
    }
    
    # Perform normalization using the converted DTM
    las <- lidR::lasnormalize(las, dtm)
    
    if (!keep_ground) {
      las <- lidR::filter_poi(las, Classification != 2)
    }
    if (min_res > 0) {
      las <- lidR::lasfilterdecimate(las, lidR::random(1/min_res))
    }
    return(las)
  }
}

# Ensure other shims also respect the requested package format
if (!exists("rasterize_terrain")) {
  rasterize_terrain <- function(las, res, algorithm = lidR::tin(), pkg = "terra", ...) {
    dtm <- lidR::grid_terrain(las, res = res, algorithm = algorithm, ...)
    if (pkg == "terra") return(terra::rast(dtm))
    return(dtm)
  }
}

if (!exists("rasterize_canopy")) {
  rasterize_canopy <- function(las, res, algorithm = lidR::p2r(), pkg = "terra", ...) {
    chm <- lidR::grid_canopy(las, res = res, algorithm = algorithm, ...)
    if (pkg == "terra") return(terra::rast(chm))
    return(chm)
  }
}
# ----------------------------------------------------
"""

scripts = [
    "/home/jovyan/work/Dry-shRub/shrub/Sprint 3/Base/IntELiMon_1_1_1.R",
    "/home/jovyan/work/Dry-shRub/shrub/Sprint 3/Base/IntELiMon_1_1_1_revised.R"
]

for script_path in scripts:
    with open(script_path, 'r') as f:
        content = f.read()
    
    # Remove all older shim versions
    import re
    content = re.sub(r"# --- Berkeley TLS.*?# ----------------------------------------------------", "", content, flags=re.DOTALL)
    content = re.sub(r"# --- lidR v3.*?# -------------------------------------------", "", content, flags=re.DOTALL)
    
    # Inject the bridge shim
    if "library(lidR)" in content:
        new_content = content.replace("library(lidR)", "library(lidR)" + terra_bridge_shim)
        with open(script_path, 'w') as f:
            f.write(new_content)
        print(f"Terra Bridge applied to: {script_path}")

Terra Bridge applied to: /home/jovyan/work/Dry-shRub/shrub/Sprint 3/Base/IntELiMon_1_1_1.R
Terra Bridge applied to: /home/jovyan/work/Dry-shRub/shrub/Sprint 3/Base/IntELiMon_1_1_1_revised.R

In [61]:
import os

scripts = [
    "/home/jovyan/work/Dry-shRub/shrub/Sprint 3/Base/IntELiMon_1_1_1.R",
    "/home/jovyan/work/Dry-shRub/shrub/Sprint 3/Base/IntELiMon_1_1_1_revised.R"
]

# The problematic line that triggers the defunct vctrs error
target_code = "dplyr::if_else(x == 0 & y == 0 & z == 0, 0, 1)"
# The safe replacement using base R
safe_replacement = "ifelse(x == 0 & y == 0 & z == 0, 0, 1)"

for script_path in scripts:
    if not os.path.exists(script_path):
        print(f"Skipping (not found): {script_path}")
        continue
        
    with open(script_path, 'r') as f:
        content = f.read()
    
    if target_code in content:
        new_content = content.replace(target_code, safe_replacement)
        with open(script_path, 'w') as f:
            f.write(new_content)
        print(f"Successfully patched defunct code in: {os.path.basename(script_path)}")
    else:
        # Check if it was already patched or has a slightly different format
        if "ifelse(x == 0 & y == 0 & z == 0, 0, 1)" in content:
             print(f"Code already patched in: {os.path.basename(script_path)}")
        else:
             print(f"Could not find target line in: {os.path.basename(script_path)}")

print("\nPatching complete. Please re-run your pipeline cell.")

Could not find target line in: IntELiMon_1_1_1.R
Could not find target line in: IntELiMon_1_1_1_revised.R

Patching complete. Please re-run your pipeline cell.

In [59]:
labeling_result, state, runtime_stats = execute_pipeline_section(
    labeling_pipeline,
    state=state,
    artifact_store=artifact_store,
    push_remote=USE_DRIVE,
)

controller.record_section_result(
    trial,
    section_name="labeling",
    config_signature=labeling_pipeline.config_signature(),
    result=labeling_result,
)
controller.save_trial(trial)
controller.save_state(state)

labeling_result, runtime_stats

2026-04-15 04:02:03 | INFO     | shrub.labeling.sprint3_runner | Discovering remote PTX files for site=calaveras-big-trees at https://wifire-data.sdsc.edu/nc/public.php/dav/files/ucca-calaveras-big-trees/original_TLS
2026-04-15 04:02:04 | INFO     | shrub.labeling.sprint3_runner | Discovering remote PTX files for site=dl-bliss at https://wifire-data.sdsc.edu/nc/public.php/dav/files/ucca-dl-bliss/original_TLS
2026-04-15 04:02:04 | INFO     | shrub.labeling.sprint3_runner | Discovering remote PTX files for site=independence-lake at https://wifire-data.sdsc.edu/nc/public.php/dav/files/ucca-independence-lake/original_TLS
2026-04-15 04:02:04 | INFO     | shrub.labeling.sprint3_runner | Discovering remote PTX files for site=pacific-union-college at https://wifire-data.sdsc.edu/nc/public.php/dav/files/ucca-pacific-union-college/original_TLS
2026-04-15 04:02:05 | INFO     | shrub.labeling.sprint3_runner | Discovering remote PTX files for site=sedgwick at https://wifire-data.sdsc.edu/nc/public.php/dav/files/ucca-sedgwick/original_TLS
2026-04-15 04:02:05 | INFO     | shrub.labeling.sprint3_runner | Discovering remote PTX files for site=shaver-lake at https://wifire-data.sdsc.edu/nc/public.php/dav/files/ucca-shaver-lake/original_TLS
2026-04-15 04:02:05 | INFO     | shrub.labeling.pipeline | Sprint 3 PTX discovery selected 6 PTX row(s) across 6 site(s)
2026-04-15 04:02:05 | INFO     | shrub.labeling.sprint3_runner | Using cached PTX for site=calaveras-big-trees: /home/jovyan/work/Dry-shRub/shrub/Final/artifacts/labeling/ptx_cache/calaveras-big-trees/CATCU_0009_20250615_1.ptx
2026-04-15 04:02:05 | INFO     | shrub.labeling.pipeline | Starting Sprint 3 | site=calaveras-big-trees | variant=original | ptx=CATCU_0009_20250615_1.ptx
2026-04-15 04:02:05 | INFO     | shrub.labeling.sprint3_runner | Running Sprint 3 for site=calaveras-big-trees variant=original
2026-04-15 04:02:05 | INFO     | shrub.labeling.sprint3_runner | PTX: /home/jovyan/work/Dry-shRub/shrub/Final/artifacts/labeling/ptx_cache/calaveras-big-trees/CATCU_0009_20250615_1.ptx
2026-04-15 04:02:05 | INFO     | shrub.labeling.sprint3_runner | Script: /home/jovyan/work/Dry-shRub/shrub/Sprint 3/Base/IntELiMon_1_1_1.R
2026-04-15 04:02:05 | INFO     | shrub.labeling.sprint3_runner | Output dir: /home/jovyan/work/Dry-shRub/shrub/Final/artifacts/labeling/calaveras-big-trees/sprint3/original/CATCU_0009_20250615_1
2026-04-15 04:02:05 | INFO     | shrub.labeling.sprint3_runner | Command: /opt/conda/bin/Rscript /home/jovyan/work/Dry-shRub/shrub/Sprint 3/Base/IntELiMon_1_1_1.R /home/jovyan/work/Dry-shRub/shrub/Final/artifacts/labeling/ptx_cache/calaveras-big-trees/CATCU_0009_20250615_1.ptx /home/jovyan/work/Dry-shRub/shrub/Final/artifacts/labeling/calaveras-big-trees/sprint3/original/CATCU_0009_20250615_1
2026-04-15 04:03:09 | INFO     | shrub.labeling.sprint3_runner | Sprint 3 finished with returncode=1 | shrub_csv=None | metrics_csv=None | tree_inventory_csv=None | cache=False
2026-04-15 04:03:09 | ERROR    | shrub.labeling.sprint3_runner | Sprint 3 failed for site=calaveras-big-trees variant=original
2026-04-15 04:03:09 | ERROR    | shrub.labeling.sprint3_runner | stderr tail:

Linking to GEOS 3.14.1, GDAL 3.12.2, PROJ 9.7.1; sf_use_s2() is TRUE

Attaching package: ‘Morpho’

The following object is masked from ‘package:terra’:

    classify

Loading required package: magrittr

Attaching package: ‘magrittr’

The following object is masked from ‘package:raster’:

    extract

The following objects are masked from ‘package:terra’:

    extract, inset

Warning messages:
1: In rgl.init(initValue, onlyNULL) : RGL: unable to open X11 display
2: 'rgl.init' failed, will use the null device.
See '?rgl.useNULL' for ways to avoid this warning.
3: In dir.create(file.path(outDir, "metrics"), recursive = TRUE) :
  '/home/jovyan/work/Dry-shRub/shrub/Final/artifacts/labeling/calaveras-big-trees/sprint3/original/CATCU_0009_20250615_1/metrics' already exists
4: In dir.create(file.path(outDir, "dtm"), recursive = TRUE) :
  '/home/jovyan/work/Dry-shRub/shrub/Final/artifacts/labeling/calaveras-big-trees/sprint3/original/CATCU_0009_20250615_1/dtm' already exists
5: In dir.create(file.path(outDir, "chm"), recursive = TRUE) :
  '/home/jovyan/work/Dry-shRub/shrub/Final/artifacts/labeling/calaveras-big-trees/sprint3/original/CATCU_0009_20250615_1/chm' already exists
6: In dir.create(file.path(outDir, "Fuels"), recursive = TRUE) :
  '/home/jovyan/work/Dry-shRub/shrub/Final/artifacts/labeling/calaveras-big-trees/sprint3/original/CATCU_0009_20250615_1/Fuels' already exists
7: In dir.create(file.path(outDir, "Shrubs"), recursive = TRUE) :
  '/home/jovyan/work/Dry-shRub/shrub/Final/artifacts/labeling/calaveras-big-trees/sprint3/original/CATCU_0009_20250615_1/Shrubs' already exists
8: In dir.create(file.path(outDir, "Inventory"), recursive = TRUE) :
  '/home/jovyan/work/Dry-shRub/shrub/Final/artifacts/labeling/calaveras-big-trees/sprint3/original/CATCU_0009_20250615_1/Inventory' already exists
Using shimmed tlsNormalize2 (with Terra Bridge)...
Error in `mutate()`:
! Problem while computing `returned = dplyr::if_else(x == 0 & y == 0 & z
  == 0, 0, 1)`.
Caused by error:
! `vec_is_vector()` is defunct.
Backtrace:
     ▆
  1. ├─global getDist(dat)
  2. │ └─pts %>% ...
  3. ├─dplyr::mutate(...)
  4. ├─dplyr:::mutate.data.frame(., returned = dplyr::if_else(x == 0 & y == 0 & z == 0, 0, 1))
  5. │ └─dplyr:::mutate_cols(.data, dplyr_quosures(...), caller_env = caller_env())
  6. │   ├─base::withCallingHandlers(...)
  7. │   └─mask$eval_all_mutate(quo)
  8. └─base::.handleSimpleError(...)
  9.   └─dplyr (local) h(simpleError(msg, call))
 10.     └─rlang::abort(...)
Warning messages:
1: There were 5728 degenerated ground points. Some X Y Z coordinates were repeated. They were removed.
2: There were 179685 degenerated ground points. Some X Y coordinates were repeated but with different Z coordinates. min Z were retained.
3: lidR::lasnormalize is deprecated. Use normalize_height instead.
4: lidR::lasfilterdecimate is deprecated. Use decimate_points instead.
2026-04-15 04:03:09 | ERROR    | shrub.labeling.pipeline | Sprint 3 failed | site=calaveras-big-trees | variant=original | ptx=CATCU_0009_20250615_1.ptx
Traceback (most recent call last):
  File "/home/jovyan/work/Dry-shRub/shrub/Final/labeling/pipeline.py", line 623, in stage_run_sprint3
    result = run_sprint3_for_ptx(
             ^^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/work/Dry-shRub/shrub/Final/labeling/sprint3_runner.py", line 465, in run_sprint3_for_ptx
    raise RuntimeError(
RuntimeError: Sprint 3 failed for site=calaveras-big-trees, variant=original, returncode=1.
stderr tail:

Linking to GEOS 3.14.1, GDAL 3.12.2, PROJ 9.7.1; sf_use_s2() is TRUE

Attaching package: ‘Morpho’

The following object is masked from ‘package:terra’:

    classify

Loading required package: magrittr

Attaching package: ‘magrittr’

The following object is masked from ‘package:raster’:

    extract

The following objects are masked from ‘package:terra’:

    extract, inset

Warning messages:
1: In rgl.init(initValue, onlyNULL) : RGL: unable to open X11 display
2: 'rgl.init' failed, will use the null device.
See '?rgl.useNULL' for ways to avoid this warning.
3: In dir.create(file.path(outDir, "metrics"), recursive = TRUE) :
  '/home/jovyan/work/Dry-shRub/shrub/Final/artifacts/labeling/calaveras-big-trees/sprint3/original/CATCU_0009_20250615_1/metrics' already exists
4: In dir.create(file.path(outDir, "dtm"), recursive = TRUE) :
  '/home/jovyan/work/Dry-shRub/shrub/Final/artifacts/labeling/calaveras-big-trees/sprint3/original/CATCU_0009_20250615_1/dtm' already exists
5: In dir.create(file.path(outDir, "chm"), recursive = TRUE) :
  '/home/jovyan/work/Dry-shRub/shrub/Final/artifacts/labeling/calaveras-big-trees/sprint3/original/CATCU_0009_20250615_1/chm' already exists
6: In dir.create(file.path(outDir, "Fuels"), recursive = TRUE) :
  '/home/jovyan/work/Dry-shRub/shrub/Final/artifacts/labeling/calaveras-big-trees/sprint3/original/CATCU_0009_20250615_1/Fuels' already exists
7: In dir.create(file.path(outDir, "Shrubs"), recursive = TRUE) :
  '/home/jovyan/work/Dry-shRub/shrub/Final/artifacts/labeling/calaveras-big-trees/sprint3/original/CATCU_0009_20250615_1/Shrubs' already exists
8: In dir.create(file.path(outDir, "Inventory"), recursive = TRUE) :
  '/home/jovyan/work/Dry-shRub/shrub/Final/artifacts/labeling/calaveras-big-trees/sprint3/original/CATCU_0009_20250615_1/Inventory' already exists
Using shimmed tlsNormalize2 (with Terra Bridge)...
Error in `mutate()`:
! Problem while computing `returned = dplyr::if_else(x == 0 & y == 0 & z
  == 0, 0, 1)`.
Caused by error:
! `vec_is_vector()` is defunct.
Backtrace:
     ▆
  1. ├─global getDist(dat)
  2. │ └─pts %>% ...
  3. ├─dplyr::mutate(...)
  4. ├─dplyr:::mutate.data.frame(., returned = dplyr::if_else(x == 0 & y == 0 & z == 0, 0, 1))
  5. │ └─dplyr:::mutate_cols(.data, dplyr_quosures(...), caller_env = caller_env())
  6. │   ├─base::withCallingHandlers(...)
  7. │   └─mask$eval_all_mutate(quo)
  8. └─base::.handleSimpleError(...)
  9.   └─dplyr (local) h(simpleError(msg, call))
 10.     └─rlang::abort(...)
Warning messages:
1: There were 5728 degenerated ground points. Some X Y Z coordinates were repeated. They were removed.
2: There were 179685 degenerated ground points. Some X Y coordinates were repeated but with different Z coordinates. min Z were retained.
3: lidR::lasnormalize is deprecated. Use normalize_height instead.
4: lidR::lasfilterdecimate is deprecated. Use decimate_points instead.
2026-04-15 04:03:09 | INFO     | shrub.labeling.pipeline | Starting Sprint 3 | site=calaveras-big-trees | variant=revised | ptx=CATCU_0009_20250615_1.ptx
2026-04-15 04:03:09 | INFO     | shrub.labeling.sprint3_runner | Running Sprint 3 for site=calaveras-big-trees variant=revised
2026-04-15 04:03:09 | INFO     | shrub.labeling.sprint3_runner | PTX: /home/jovyan/work/Dry-shRub/shrub/Final/artifacts/labeling/ptx_cache/calaveras-big-trees/CATCU_0009_20250615_1.ptx
2026-04-15 04:03:09 | INFO     | shrub.labeling.sprint3_runner | Script: /home/jovyan/work/Dry-shRub/shrub/Sprint 3/Base/IntELiMon_1_1_1_revised.R
2026-04-15 04:03:09 | INFO     | shrub.labeling.sprint3_runner | Output dir: /home/jovyan/work/Dry-shRub/shrub/Final/artifacts/labeling/calaveras-big-trees/sprint3/revised/CATCU_0009_20250615_1
2026-04-15 04:03:09 | INFO     | shrub.labeling.sprint3_runner | Command: /opt/conda/bin/Rscript /home/jovyan/work/Dry-shRub/shrub/Sprint 3/Base/IntELiMon_1_1_1_revised.R /home/jovyan/work/Dry-shRub/shrub/Final/artifacts/labeling/ptx_cache/calaveras-big-trees/CATCU_0009_20250615_1.ptx /home/jovyan/work/Dry-shRub/shrub/Final/artifacts/labeling/calaveras-big-trees/sprint3/revised/CATCU_0009_20250615_1

KeyboardInterrupt:

KeyboardInterrupt:

In [60]:
import os

stderr_path = "/home/jovyan/work/Dry-shRub/shrub/Final/artifacts/labeling/calaveras-big-trees/sprint3/original/CATCU_0009_20250615_1/stderr.log"
stdout_path = "/home/jovyan/work/Dry-shRub/shrub/Final/artifacts/labeling/calaveras-big-trees/sprint3/original/CATCU_0009_20250615_1/stdout.log"

print("================ FULL STDERR ================")
if os.path.exists(stderr_path):
    with open(stderr_path, 'r') as f:
        print(f.read())
else:
    print("stderr.log not found!")

print("\n================ FULL STDOUT ================")
if os.path.exists(stdout_path):
    with open(stdout_path, 'r') as f:
        print(f.read())
else:
    print("stdout.log not found!")

================ FULL STDERR ================

Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union


Attaching package: ‘data.table’

The following objects are masked from ‘package:dplyr’:

    between, first, last

terra 1.9.11

Attaching package: ‘terra’

The following object is masked from ‘package:data.table’:

    shift

Loading required package: raster
Loading required package: sp

Attaching package: ‘raster’

The following object is masked from ‘package:dplyr’:

    select


Attaching package: ‘lidR’

The following objects are masked from ‘package:terra’:

    is.empty, watershed


Attaching package: ‘e1071’

The following object is masked from ‘package:raster’:

    interpolate

The following object is masked from ‘package:terra’:

    interpolate

Linking to GEOS 3.14.1, GDAL 3.12.2, PROJ 9.7.1; sf_use_s2() is TRUE

Attaching package: ‘Morpho’

The following object is masked from ‘package:terra’:

    classify

Loading required package: magrittr

Attaching package: ‘magrittr’

The following object is masked from ‘package:raster’:

    extract

The following objects are masked from ‘package:terra’:

    extract, inset

Warning messages:
1: In rgl.init(initValue, onlyNULL) : RGL: unable to open X11 display
2: 'rgl.init' failed, will use the null device.
See '?rgl.useNULL' for ways to avoid this warning.
3: In dir.create(file.path(outDir, "metrics"), recursive = TRUE) :
  '/home/jovyan/work/Dry-shRub/shrub/Final/artifacts/labeling/calaveras-big-trees/sprint3/original/CATCU_0009_20250615_1/metrics' already exists
4: In dir.create(file.path(outDir, "dtm"), recursive = TRUE) :
  '/home/jovyan/work/Dry-shRub/shrub/Final/artifacts/labeling/calaveras-big-trees/sprint3/original/CATCU_0009_20250615_1/dtm' already exists
5: In dir.create(file.path(outDir, "chm"), recursive = TRUE) :
  '/home/jovyan/work/Dry-shRub/shrub/Final/artifacts/labeling/calaveras-big-trees/sprint3/original/CATCU_0009_20250615_1/chm' already exists
6: In dir.create(file.path(outDir, "Fuels"), recursive = TRUE) :
  '/home/jovyan/work/Dry-shRub/shrub/Final/artifacts/labeling/calaveras-big-trees/sprint3/original/CATCU_0009_20250615_1/Fuels' already exists
7: In dir.create(file.path(outDir, "Shrubs"), recursive = TRUE) :
  '/home/jovyan/work/Dry-shRub/shrub/Final/artifacts/labeling/calaveras-big-trees/sprint3/original/CATCU_0009_20250615_1/Shrubs' already exists
8: In dir.create(file.path(outDir, "Inventory"), recursive = TRUE) :
  '/home/jovyan/work/Dry-shRub/shrub/Final/artifacts/labeling/calaveras-big-trees/sprint3/original/CATCU_0009_20250615_1/Inventory' already exists
Using shimmed tlsNormalize2 (with Terra Bridge)...
Error in `mutate()`:
! Problem while computing `returned = dplyr::if_else(x == 0 & y == 0 & z
  == 0, 0, 1)`.
Caused by error:
! `vec_is_vector()` is defunct.
Backtrace:
     ▆
  1. ├─global getDist(dat)
  2. │ └─pts %>% ...
  3. ├─dplyr::mutate(...)
  4. ├─dplyr:::mutate.data.frame(., returned = dplyr::if_else(x == 0 & y == 0 & z == 0, 0, 1))
  5. │ └─dplyr:::mutate_cols(.data, dplyr_quosures(...), caller_env = caller_env())
  6. │   ├─base::withCallingHandlers(...)
  7. │   └─mask$eval_all_mutate(quo)
  8. └─base::.handleSimpleError(...)
  9.   └─dplyr (local) h(simpleError(msg, call))
 10.     └─rlang::abort(...)
Warning messages:
1: There were 5728 degenerated ground points. Some X Y Z coordinates were repeated. They were removed.
2: There were 179685 degenerated ground points. Some X Y coordinates were repeated but with different Z coordinates. min Z were retained.
3: lidR::lasnormalize is deprecated. Use normalize_height instead.
4: lidR::lasfilterdecimate is deprecated. Use decimate_points instead.


================ FULL STDOUT ================
ERROR! Session/line number was not unique in database. History logging moved to new session 19
Delaunay rasterization[===========================================-------] 86% (4 threads)
Delaunay rasterization[===========================================-------] 87% (4 threads)
Delaunay rasterization[============================================------] 88% (4 threads)
Delaunay rasterization[============================================------] 89% (4 threads)
Delaunay rasterization[=============================================-----] 90% (4 threads)
Delaunay rasterization[=============================================-----] 91% (4 threads)
Delaunay rasterization[==============================================----] 92% (4 threads)
Delaunay rasterization[==============================================----] 93% (4 threads)
Delaunay rasterization[===============================================---] 94% (4 threads)
Delaunay rasterization[===============================================---] 95% (4 threads)
Delaunay rasterization[================================================--] 96% (4 threads)
Delaunay rasterization[================================================--] 97% (4 threads)
Delaunay rasterization[=================================================-] 98% (4 threads)
Delaunay rasterization[=================================================-] 99% (4 threads)
Delaunay rasterization[==================================================] 100% (4 threads)
--- TRACEBACK ---
[[1]]
getDist(dat)

[[2]]
pts %>% mutate(returned = dplyr::if_else(x == 0 & y == 0 & z ==
    0, 0, 1))

[[3]]
mutate(., returned = dplyr::if_else(x == 0 & y == 0 & z == 0,
    0, 1))

[[4]]
mutate.data.frame(., returned = dplyr::if_else(x == 0 & y ==
    0 & z == 0, 0, 1))

[[5]]
mutate_cols(.data, dplyr_quosures(...), caller_env = caller_env())

[[6]]
withCallingHandlers({
    for (i in seq_along(dots)) {
        context_poke("column", old_current_column)
        quosures <- expand_across(dots[[i]])
        quosures_results <- vector(mode = "list", length = length(quosures))
        for (k in seq_along(quosures)) {
            quo <- quosures[[k]]
            quo_data <- attr(quo, "dplyr:::data")
            if (!is.null(quo_data$column)) {
                context_poke("column", quo_data$column)
            }
            chunks <- NULL
            result <- NULL
            if (quo_is_symbol(quo)) {
                name <- as_string(quo_get_expr(quo))
                if (name %in% names(new_columns)) {
                  result <- new_columns[[name]]
                  chunks <- mask$resolve(name)
                }
                else if (name %in% names(.data)) {
                  result <- .data[[name]]
                  chunks <- mask$resolve(name)
                }
                if (inherits(.data, "rowwise_df") && vec_is_list(result)) {
                  sizes <- list_sizes(result)
                  wrong <- which(sizes != 1)
                  if (length(wrong)) {
                    group <- wrong[1L]
                    mask$set_current_group(group)
                    abort(class = c("dplyr:::mutate_incompatible_size",
                      "dplyr:::internal_error"), dplyr_error_data = list(result_size = sizes[group],
                      expected_size = 1))
                  }
                }
            }
            else if (!quo_is_symbolic(quo) && !is.null(quo_get_expr(quo))) {
                result <- quo_get_expr(quo)
                result <- withCallingHandlers(vec_recycle(result,
                  vec_size(.data)), error = function(cnd) {
                  abort(class = c("dplyr:::mutate_constant_recycle_error",
                    "dplyr:::internal_error"), constant_size = vec_size(result),
                    data_size = vec_size(.data))
                })
                chunks <- vec_chop(result, rows)
            }
            if (is.null(chunks)) {
                if (is.null(quo_data$column)) {
                  chunks <- mask$eval_all_mutate(quo)
                }
                else {
                  chunks <- withCallingHandlers(mask$eval_all_mutate(quo),
                    error = function(cnd) {
                      msg <- glue("Problem while computing column `{quo_data$name_auto}`.")
                      abort(msg, call = call("across"), parent = cnd)
                    })
                }
            }
            if (is.null(chunks)) {
                next
            }
            if (is.null(result)) {
                if (length(rows) == 1) {
                  result <- chunks[[1]]
                }
                else {
                  chunks <- dplyr_vec_cast_common(chunks, quo_data$name_auto)
                  result <- vec_unchop(chunks, rows)
                }
            }
            quosures_results[[k]] <- list(result = result, chunks = chunks)
        }
        for (k in seq_along(quosures)) {
            quo <- quosures[[k]]
            quo_data <- attr(quo, "dplyr:::data")
            quo_result <- quosures_results[[k]]
            if (is.null(quo_result)) {
                if (quo_data$is_named) {
                  name <- quo_data$name_given
                  new_columns[[name]] <- zap()
                  mask$remove(name)
                }
                next
            }
            result <- quo_result$result
            chunks <- quo_result$chunks
            if (!quo_data$is_named && is.data.frame(result)) {
                types <- vec_ptype(result)
                types_names <- names(types)
                chunks_extracted <- .Call(dplyr_extract_chunks,
                  chunks, types)
                for (j in seq_along(types)) {
                  mask$add_one(types_names[j], chunks_extracted[[j]],
                    result = result[[j]])
                }
                new_columns[types_names] <- result
            }
            else {
                name <- quo_data$name_auto
                mask$add_one(name = name, chunks = chunks, result = result)
                new_columns[[name]] <- result
            }
        }
    }
}, error = function(e) {
    local_error_context(dots = dots, .index = i, mask = mask)
    bullets <- c(cnd_bullet_header("computing"), mutate_bullets(e))
    abort(bullets, class = "dplyr:::mutate_error", parent = skip_internal_condition(e),
        bullets = bullets, call = error_call)
}, warning = function(w) {
    if (check_muffled_warning(w)) {
        maybe_restart("muffleWarning")
    }
    local_error_context(dots = dots, .index = i, mask = mask)
    warn(c(cnd_bullet_header("computing"), i = cnd_header(w),
        i = cnd_bullet_cur_group_label(what = "warning")))
    maybe_restart("muffleWarning")
})

[[7]]
mask$eval_all_mutate(quo)

[[8]]
.handleSimpleError(function (e)
{
    local_error_context(dots = dots, .index = i, mask = mask)
    bullets <- c(cnd_bullet_header("computing"), mutate_bullets(e))
    abort(bullets, class = "dplyr:::mutate_error", parent = skip_internal_condition(e),
        bullets = bullets, call = error_call)
}, "`vec_is_vector()` is defunct.", base::quote(NULL))

[[9]]
h(simpleError(msg, call))

[[10]]
abort(bullets, class = "dplyr:::mutate_error", parent = skip_internal_condition(e),
    bullets = bullets, call = error_call)

[[11]]
signal_abort(cnd, .file)

[[12]]
stop(fallback)

[[13]]
(function ()
{
    cat("\n--- TRACEBACK ---\n")
    print(sys.calls())
    q("no", status = 1)
})()

In [ ]:
print("Experiment state:")
display(state)

print("Trial:")
display(trial)

print("Completed trials:")
display(grid.completed_trials_frame())

## Features

In [ ]:
features_cfg = {
    "enabled": False,
    "feature_families": [],
    "notes": "Placeholder only for now.",
}

trial.features_config = features_cfg

save_trial(EXPERIMENT_NAME, trial)

trial.features_config

In [ ]:
trial.features_result = {
    "success": None,
    "status": "placeholder_not_run",
    "metrics": {},
    "qa_outputs": {"placeholder": True},
    "notes": ["Features pipeline not implemented yet."],
}

state.section_status["features"] = "placeholder_not_run"
state.qa_outputs["features"] = trial.features_result["qa_outputs"]

save_trial(EXPERIMENT_NAME, trial)
trial.features_result

# Modeling

In [ ]:
modeling_cfg = {
    "enabled": False,
    "model_family": None,
    "notes": "Placeholder only for now.",
}

trial.modeling_config = modeling_cfg

save_trial(EXPERIMENT_NAME, trial)

trial.modeling_config

In [ ]:
trial.modeling_result = {
    "success": None,
    "status": "placeholder_not_run",
    "metrics": {},
    "qa_outputs": {"placeholder": True},
    "notes": ["Modeling pipeline not implemented yet."],
}

state.section_status["modeling"] = "placeholder_not_run"
state.qa_outputs["modeling"] = trial.modeling_result["qa_outputs"]

save_trial(EXPERIMENT_NAME, trial)
trial.modeling_result

# Post-processing

In [ ]:
postprocessing_cfg = {
    "enabled": False,
    "steps": [],
    "notes": "Placeholder only for now.",
}

trial.postprocessing_config = postprocessing_cfg

save_trial(EXPERIMENT_NAME, trial)

trial.postprocessing_config

In [ ]:
trial.postprocessing_result = {
    "success": None,
    "status": "placeholder_not_run",
    "metrics": {},
    "qa_outputs": {"placeholder": True},
    "notes": ["Postprocessing pipeline not implemented yet."],
}

state.section_status["postprocessing"] = "placeholder_not_run"
state.qa_outputs["postprocessing"] = trial.postprocessing_result["qa_outputs"]

save_trial(EXPERIMENT_NAME, trial)
trial.postprocessing_result

# Finalize Trial

In [ ]:
trial.qa_summary = {
    "integrity": {
        "labeling": trial.labeling_result.get("status"),
        "features": trial.features_result.get("status"),
        "modeling": trial.modeling_result.get("status"),
        "postprocessing": trial.postprocessing_result.get("status"),
    },
    "section_level": {
        "labeling": "placeholder",
        "features": "placeholder",
        "modeling": "placeholder",
        "postprocessing": "placeholder",
    },
    "cross_section": {
        "label_to_model_feedback": "placeholder",
        "feature_to_model_feedback": "placeholder",
        "end_to_end_feedback": "placeholder",
    },
}

save_trial(EXPERIMENT_NAME, trial)
trial.qa_summary

In [ ]:
labeling_object_rows = trial.labeling_result.get("metrics", {}).get("n_object_rows", 0)
labeling_artifact_rows = trial.labeling_result.get("metrics", {}).get("n_artifact_rows", 0)

trial.score_summary = {
    "labeling_score_placeholder": float(labeling_object_rows > 0) + float(labeling_artifact_rows > 0),
    "features_score_placeholder": None,
    "modeling_score_placeholder": None,
    "postprocessing_score_placeholder": None,
    "composite_score_placeholder": float(labeling_object_rows > 0) + float(labeling_artifact_rows > 0),
}

save_trial(EXPERIMENT_NAME, trial)
trial.score_summary

In [ ]:
trial.status = "partial" if (
    trial.features_result.get("status") == "placeholder_not_run"
    or trial.modeling_result.get("status") == "placeholder_not_run"
    or trial.postprocessing_result.get("status") == "placeholder_not_run"
) else "completed"

save_trial(EXPERIMENT_NAME, trial)

trial

In [ ]:
trial_record_min = {
    "trial_id": trial.trial_id,
    "created_at": trial.created_at,
    "status": trial.status,
    "labeling_config": trial.labeling_config,
    "features_config": trial.features_config,
    "modeling_config": trial.modeling_config,
    "postprocessing_config": trial.postprocessing_config,
    "score_summary": trial.score_summary,
}

registry.trials = [t for t in registry.trials if t["trial_id"] != trial.trial_id]
registry.trials.append(trial_record_min)

score = trial.score_summary.get("composite_score_placeholder")
if score is not None:
    if registry.best_score is None or score > registry.best_score:
        registry.best_score = score
        registry.best_trial_id = trial.trial_id

save_registry(registry)

registry

In [ ]:
trials_df = pd.DataFrame(registry.trials)

if not trials_df.empty:
    if "score_summary" in trials_df.columns:
        trials_df["composite_score_placeholder"] = trials_df["score_summary"].apply(
            lambda x: x.get("composite_score_placeholder") if isinstance(x, dict) else None
        )

    display(
        trials_df[
            ["trial_id", "created_at", "status", "composite_score_placeholder"]
        ].sort_values("trial_id")
    )

    print("Best trial:", registry.best_trial_id)
    print("Best score:", registry.best_score)
else:
    print("No trials recorded yet.")

In [ ]:
INSPECT_TRIAL_ID = trial.trial_id  # change manually

inspect_trial = load_trial(EXPERIMENT_NAME, INSPECT_TRIAL_ID)
inspect_trial